// Seed products 401-440 (auto-generated split)
export const SEED_PRODUCTS_11 = [
  {
    "name": "Dinamax x 30 cap",
    "genericName": "Biotina",
    "laboratorio": "Dinamax",
    "concentracion": "x 30 cap",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 1,
    "barcode": "7590000000401",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000401.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
  {
    "name": "Walife x 60 tab",
    "genericName": "Colágeno",
    "laboratorio": "Walife",
    "concentracion": "x 60 tab",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 1,
    "barcode": "7590000000402",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000402.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
  {
    "name": "Cojín Abductor de Cadera",
    "genericName": "Cojín Abductor de Cadera",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "otros",
    "priceUsd": 45.0,
    "costUsd": 29.25,
    "stock": 2,
    "barcode": "7590000000403",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000403.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Nebulizador Compresor",
    "genericName": "Nebulizador Compresor",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Equipo",
    "category": "otros",
    "priceUsd": 65.0,
    "costUsd": 42.25,
    "stock": 1,
    "barcode": "7590000000404",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000404.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Regulador de Oxígeno",
    "genericName": "Regulador de Oxígeno",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Equipo",
    "category": "otros",
    "priceUsd": 90.0,
    "costUsd": 58.5,
    "stock": 1,
    "barcode": "7590000000405",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000405.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Pistola Masajeadora",
    "genericName": "Pistola Masajeadora",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Equipo",
    "category": "otros",
    "priceUsd": 30.0,
    "costUsd": 19.5,
    "stock": 1,
    "barcode": "7590000000406",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000406.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Mini Masajeador",
    "genericName": "Mini Masajeador",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Equipo",
    "category": "otros",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 1,
    "barcode": "7590000000407",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000407.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Medias de Compresión 15-20 M",
    "genericName": "Medias de Compresión 15-20 M",
    "laboratorio": "Genérico",
    "concentracion": "15-20 mmHg",
    "presentacion": "Par",
    "category": "otros",
    "priceUsd": 30.0,
    "costUsd": 19.5,
    "stock": 4,
    "barcode": "7590000000408",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000408.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Medias de Compresión 20-30 M",
    "genericName": "Medias de Compresión 20-30 M",
    "laboratorio": "Genérico",
    "concentracion": "20-30 mmHg",
    "presentacion": "Par",
    "category": "otros",
    "priceUsd": 30.0,
    "costUsd": 19.5,
    "stock": 2,
    "barcode": "7590000000409",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000409.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Medias Antiembolia 18-21",
    "genericName": "Medias Antiembolia 18-21",
    "laboratorio": "Genérico",
    "concentracion": "18-21 mmHg",
    "presentacion": "Par",
    "category": "otros",
    "priceUsd": 40.0,
    "costUsd": 26.0,
    "stock": 1,
    "barcode": "7590000000410",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000410.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Medias de Compresión 23-32 R",
    "genericName": "Medias de Compresión 23-32 R",
    "laboratorio": "Genérico",
    "concentracion": "23-32 mmHg",
    "presentacion": "Par",
    "category": "otros",
    "priceUsd": 40.0,
    "costUsd": 26.0,
    "stock": 1,
    "barcode": "7590000000411",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000411.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Medias de Compresión 15-21 R",
    "genericName": "Medias de Compresión 15-21 R",
    "laboratorio": "Genérico",
    "concentracion": "15-21 mmHg",
    "presentacion": "Par",
    "category": "otros",
    "priceUsd": 40.0,
    "costUsd": 26.0,
    "stock": 1,
    "barcode": "7590000000412",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000412.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Medias Baja Compresión",
    "genericName": "Medias Baja Compresión",
    "laboratorio": "Genérico",
    "concentracion": "Baja",
    "presentacion": "Par",
    "category": "otros",
    "priceUsd": 30.0,
    "costUsd": 19.5,
    "stock": 1,
    "barcode": "7590000000413",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000413.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Estetoscopio",
    "genericName": "Estetoscopio",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "otros",
    "priceUsd": 20.0,
    "costUsd": 13.0,
    "stock": 1,
    "barcode": "7590000000414",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000414.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Brazalete Digital Tensiómetro",
    "genericName": "Brazalete Digital Tensiómetro",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "otros",
    "priceUsd": 20.0,
    "costUsd": 13.0,
    "stock": 1,
    "barcode": "7590000000415",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000415.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Tensiómetro Manual",
    "genericName": "Tensiómetro Manual",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Equipo",
    "category": "otros",
    "priceUsd": 30.0,
    "costUsd": 19.5,
    "stock": 2,
    "barcode": "7590000000416",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000416.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Tensiómetro Digital Brazo",
    "genericName": "Tensiómetro Digital Brazo",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Equipo",
    "category": "otros",
    "priceUsd": 35.0,
    "costUsd": 22.75,
    "stock": 1,
    "barcode": "7590000000417",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000417.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Tensiómetro Digital Muñeca",
    "genericName": "Tensiómetro Digital Muñeca",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Equipo",
    "category": "otros",
    "priceUsd": 45.0,
    "costUsd": 29.25,
    "stock": 1,
    "barcode": "7590000000418",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000418.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Tiras Reactivas Moradas 286",
    "genericName": "Tiras Reactivas Moradas 286",
    "laboratorio": "Genérico",
    "concentracion": "286",
    "presentacion": "Caja",
    "category": "otros",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 4,
    "barcode": "7590000000419",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000419.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Tiras Reactivas Moradas 306",
    "genericName": "Tiras Reactivas Moradas 306",
    "laboratorio": "Genérico",
    "concentracion": "306",
    "presentacion": "Caja",
    "category": "otros",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 1,
    "barcode": "7590000000420",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000420.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Tiras Reactivas Pote",
    "genericName": "Tiras Reactivas Pote",
    "laboratorio": "Blood Good",
    "concentracion": "Pote",
    "presentacion": "Pote",
    "category": "otros",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 2,
    "barcode": "7590000000421",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000421.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Glucómetro Verde",
    "genericName": "Glucómetro Verde",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Equipo",
    "category": "otros",
    "priceUsd": 35.0,
    "costUsd": 22.75,
    "stock": 2,
    "barcode": "7590000000422",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000422.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Glucómetro",
    "genericName": "Glucómetro",
    "laboratorio": "Blood Good",
    "concentracion": "",
    "presentacion": "Equipo",
    "category": "otros",
    "priceUsd": 55.0,
    "costUsd": 35.75,
    "stock": 2,
    "barcode": "7590000000423",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000423.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Triflo (Ejercitador Pulmonar)",
    "genericName": "Triflo (Ejercitador Pulmonar)",
    "laboratorio": "Triflo",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "otros",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 2,
    "barcode": "7590000000424",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000424.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Nebulizador Digital",
    "genericName": "Nebulizador Digital",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Equipo",
    "category": "otros",
    "priceUsd": 20.0,
    "costUsd": 13.0,
    "stock": 1,
    "barcode": "7590000000425",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000425.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Otoscopio",
    "genericName": "Otoscopio",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Equipo",
    "category": "otros",
    "priceUsd": 40.0,
    "costUsd": 26.0,
    "stock": 1,
    "barcode": "7590000000426",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000426.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Oxímetro",
    "genericName": "Oxímetro",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Equipo",
    "category": "otros",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 2,
    "barcode": "7590000000427",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000427.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Frío Pak Grande",
    "genericName": "Frío Pak Grande",
    "laboratorio": "Genérico",
    "concentracion": "Grande",
    "presentacion": "Unidad",
    "category": "otros",
    "priceUsd": 20.0,
    "costUsd": 13.0,
    "stock": 2,
    "barcode": "7590000000428",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000428.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Frío Pak Pequeño",
    "genericName": "Frío Pak Pequeño",
    "laboratorio": "Genérico",
    "concentracion": "Pequeño",
    "presentacion": "Unidad",
    "category": "otros",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 2,
    "barcode": "7590000000429",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000429.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Kinesiotape Original",
    "genericName": "Kinesiotape Original",
    "laboratorio": "Genérico",
    "concentracion": "Rollo",
    "presentacion": "Rollo",
    "category": "otros",
    "priceUsd": 50.0,
    "costUsd": 32.5,
    "stock": 1,
    "barcode": "7590000000430",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000430.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Kinesiotape Económico",
    "genericName": "Kinesiotape Económico",
    "laboratorio": "Genérico",
    "concentracion": "Rollo",
    "presentacion": "Rollo",
    "category": "otros",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 2,
    "barcode": "7590000000431",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000431.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Inmovilizador de Dedo",
    "genericName": "Inmovilizador de Dedo",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "otros",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 5,
    "barcode": "7590000000432",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000432.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Pera de Tensiómetro",
    "genericName": "Pera de Tensiómetro",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "otros",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 1,
    "barcode": "7590000000433",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000433.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Extractor Eléctrico",
    "genericName": "Extractor Eléctrico",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Equipo",
    "category": "otros",
    "priceUsd": 30.0,
    "costUsd": 19.5,
    "stock": 1,
    "barcode": "7590000000434",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000434.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Faja Lumbosacra",
    "genericName": "Faja Lumbosacra",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "otros",
    "priceUsd": 50.0,
    "costUsd": 32.5,
    "stock": 2,
    "barcode": "7590000000435",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000435.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Rodillera King",
    "genericName": "Rodillera King",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "otros",
    "priceUsd": 25.0,
    "costUsd": 16.25,
    "stock": 1,
    "barcode": "7590000000436",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000436.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Tobillera con Férula",
    "genericName": "Tobillera con Férula",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "otros",
    "priceUsd": 30.0,
    "costUsd": 19.5,
    "stock": 4,
    "barcode": "7590000000437",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000437.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Collarín Blando",
    "genericName": "Collarín Blando",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "otros",
    "priceUsd": 25.0,
    "costUsd": 16.25,
    "stock": 3,
    "barcode": "7590000000438",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000438.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Muñequera Elástica",
    "genericName": "Muñequera Elástica",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "otros",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 6,
    "barcode": "7590000000439",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000439.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Muñequera Inmovilizadora Pulgar",
    "genericName": "Muñequera Inmovilizadora Pulgar",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "otros",
    "priceUsd": 20.0,
    "costUsd": 13.0,
    "stock": 2,
    "barcode": "7590000000440",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000440.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
];
