// Seed products 121-160 (auto-generated split)
export const SEED_PRODUCTS_04 = [
  {
    "name": "Kmplus 40 mg",
    "genericName": "Furosemida",
    "laboratorio": "Kmplus",
    "concentracion": "40 mg",
    "presentacion": "Tab x 10",
    "category": "cardiovascular",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 6,
    "barcode": "7590000000121",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000121.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Furosemida 40 mg",
    "genericName": "Furosemida",
    "laboratorio": "Genérico",
    "concentracion": "40 mg",
    "presentacion": "Tab x 10",
    "category": "cardiovascular",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 9,
    "barcode": "7590000000122",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000122.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Fludil 10 mg",
    "genericName": "Flunarizina",
    "laboratorio": "Fludil",
    "concentracion": "10 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 3,
    "barcode": "7590000000123",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000123.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Fluconazol 200 mg",
    "genericName": "Fluconazol",
    "laboratorio": "Genérico",
    "concentracion": "200 mg",
    "presentacion": "Cap x 4",
    "category": "analgesicos",
    "priceUsd": 7.0,
    "costUsd": 4.55,
    "stock": 3,
    "barcode": "7590000000124",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000124.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Fluconazol 150 mg",
    "genericName": "Fluconazol",
    "laboratorio": "Genérico",
    "concentracion": "150 mg",
    "presentacion": "Cap x 1",
    "category": "analgesicos",
    "priceUsd": 2.5,
    "costUsd": 1.62,
    "stock": 3,
    "barcode": "7590000000125",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000125.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Fluoxetina 20 mg (Drotafarma)",
    "genericName": "Fluoxetina",
    "laboratorio": "Drotafarma",
    "concentracion": "20 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 3,
    "barcode": "7590000000126",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000126.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "BioTech 20 mg",
    "genericName": "Fluoxetina",
    "laboratorio": "BioTech",
    "concentracion": "20 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 2,
    "barcode": "7590000000127",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000127.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Milax Sobre",
    "genericName": "Polietilenglicol 3350",
    "laboratorio": "Milax Sobre",
    "concentracion": "",
    "presentacion": "Sobre",
    "category": "analgesicos",
    "priceUsd": 4.5,
    "costUsd": 2.93,
    "stock": 4,
    "barcode": "7590000000128",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000128.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Milax Pote",
    "genericName": "Polietilenglicol 3350",
    "laboratorio": "Milax Pote",
    "concentracion": "",
    "presentacion": "Pote",
    "category": "analgesicos",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 2,
    "barcode": "7590000000129",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000129.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Macrodantina",
    "genericName": "Nitrofurantoína",
    "laboratorio": "Macrodantina",
    "concentracion": "",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 6,
    "barcode": "7590000000130",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000130.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Madecassol 10 mg",
    "genericName": "Centella Asiática",
    "laboratorio": "Madecassol",
    "concentracion": "10 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 4,
    "barcode": "7590000000131",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000131.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Metformina 500 mg (Drotafarma)",
    "genericName": "Metformina",
    "laboratorio": "Drotafarma",
    "concentracion": "500 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 7,
    "barcode": "7590000000132",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000132.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Land 500 mg",
    "genericName": "Metformina",
    "laboratorio": "Land",
    "concentracion": "500 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 2,
    "barcode": "7590000000133",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000133.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Brixmedic 850 mg",
    "genericName": "Metformina",
    "laboratorio": "Brixmedic",
    "concentracion": "850 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 4,
    "barcode": "7590000000134",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000134.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Metoclopramida 10 mg (Drotafarma)",
    "genericName": "Metoclopramida",
    "laboratorio": "Drotafarma",
    "concentracion": "10 mg",
    "presentacion": "Tab x 10",
    "category": "gastrointestinal",
    "priceUsd": 3.5,
    "costUsd": 2.27,
    "stock": 7,
    "barcode": "7590000000135",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000135.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Martesia 25 mg",
    "genericName": "Pregabalina",
    "laboratorio": "Martesia",
    "concentracion": "25 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 4.5,
    "costUsd": 2.93,
    "stock": 3,
    "barcode": "7590000000136",
    "requiresPrescription": true,
    "isControlled": false,
    "image": "/products/7590000000136.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Memantina 10 mg",
    "genericName": "Memantina",
    "laboratorio": "Genérico",
    "concentracion": "10 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 7.0,
    "costUsd": 4.55,
    "stock": 4,
    "barcode": "7590000000137",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000137.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Memantina 5 mg",
    "genericName": "Memantina",
    "laboratorio": "Genérico",
    "concentracion": "5 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 3,
    "barcode": "7590000000138",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000138.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "La Santé 7.5 mg",
    "genericName": "Meloxicam",
    "laboratorio": "La Santé",
    "concentracion": "7.5 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 4.5,
    "costUsd": 2.93,
    "stock": 2,
    "barcode": "7590000000139",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000139.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Meloxicam 15 mg (Drotafarma)",
    "genericName": "Meloxicam",
    "laboratorio": "Drotafarma",
    "concentracion": "15 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 5,
    "barcode": "7590000000140",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000140.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Migra Dorixina",
    "genericName": "Clonixinato + Ergotamina",
    "laboratorio": "Megalabs",
    "concentracion": "",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 2,
    "barcode": "7590000000141",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000141.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Vincenti 4 mg",
    "genericName": "Montelukast",
    "laboratorio": "Vincenti",
    "concentracion": "4 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 3,
    "barcode": "7590000000142",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000142.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Grenfarma Pediátrico",
    "genericName": "Montelukast + Desloratadina",
    "laboratorio": "Grenfarma",
    "concentracion": "",
    "presentacion": "Tab x 10",
    "category": "antihistaminicos",
    "priceUsd": 9.0,
    "costUsd": 5.85,
    "stock": 3,
    "barcode": "7590000000143",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000143.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Grenfarma Adulto",
    "genericName": "Montelukast + Desloratadina",
    "laboratorio": "Grenfarma",
    "concentracion": "",
    "presentacion": "Tab x 10",
    "category": "antihistaminicos",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 3,
    "barcode": "7590000000144",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000144.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Kwality 10 mg",
    "genericName": "Montelukast",
    "laboratorio": "Kwality",
    "concentracion": "10 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 7,
    "barcode": "7590000000145",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000145.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Dynalab 10 mg",
    "genericName": "Montelukast",
    "laboratorio": "Dynalab",
    "concentracion": "10 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 2,
    "barcode": "7590000000146",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000146.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Mudar 30/5 mg",
    "genericName": "Montelukast + Levocetirizina",
    "laboratorio": "Mudar",
    "concentracion": "30/5 mg",
    "presentacion": "Tab x 10",
    "category": "antihistaminicos",
    "priceUsd": 7.0,
    "costUsd": 4.55,
    "stock": 2,
    "barcode": "7590000000147",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000147.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Multiviral",
    "genericName": "Antigripal",
    "laboratorio": "Siegfried",
    "concentracion": "",
    "presentacion": "Tab x 6",
    "category": "analgesicos",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 14,
    "barcode": "7590000000148",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000148.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Disbroxol Forte",
    "genericName": "Ambroxol + Clenbuterol",
    "laboratorio": "MC",
    "concentracion": "",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 7.0,
    "costUsd": 4.55,
    "stock": 4,
    "barcode": "7590000000149",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000149.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Airon Pediátrico",
    "genericName": "Montelukast",
    "laboratorio": "Airon Pediátrico",
    "concentracion": "",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 5,
    "barcode": "7590000000150",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000150.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Airon Adulto",
    "genericName": "Montelukast",
    "laboratorio": "Airon Adulto",
    "concentracion": "",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 3,
    "barcode": "7590000000151",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000151.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Montrax 4 mg",
    "genericName": "Montelukast",
    "laboratorio": "Montrax",
    "concentracion": "4 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 6,
    "barcode": "7590000000152",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000152.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Moxifloxacina 400 mg",
    "genericName": "Moxifloxacina",
    "laboratorio": "Genérico",
    "concentracion": "400 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 9.0,
    "costUsd": 5.85,
    "stock": 1,
    "barcode": "7590000000153",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000153.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Miovit (Tab x 10)",
    "genericName": "Vitaminas Complejo B",
    "laboratorio": "Cofasa",
    "concentracion": "",
    "presentacion": "Tab x 10",
    "category": "vitaminas",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 3,
    "barcode": "7590000000154",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000154.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Migren",
    "genericName": "Ergotamina Compuesta",
    "laboratorio": "Migren",
    "concentracion": "",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 3,
    "barcode": "7590000000155",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000155.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Metildopa 250 mg",
    "genericName": "Metildopa",
    "laboratorio": "Genérico",
    "concentracion": "250 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 8.5,
    "costUsd": 5.53,
    "stock": 3,
    "barcode": "7590000000156",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000156.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "La Santé 40 mg",
    "genericName": "Olmesartán",
    "laboratorio": "La Santé",
    "concentracion": "40 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 1,
    "barcode": "7590000000157",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000157.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Olmesartán + HCT 40/12.5 mg",
    "genericName": "Olmesartán + HCT",
    "laboratorio": "Genérico",
    "concentracion": "40/12.5 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 2,
    "barcode": "7590000000158",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000158.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Olmesartán + HCT 20/12.5 mg",
    "genericName": "Olmesartán + HCT",
    "laboratorio": "Genérico",
    "concentracion": "20/12.5 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 7.0,
    "costUsd": 4.55,
    "stock": 2,
    "barcode": "7590000000159",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000159.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "La Santé 20 mg",
    "genericName": "Olmesartán",
    "laboratorio": "La Santé",
    "concentracion": "20 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 2,
    "barcode": "7590000000160",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000160.jpg",
    "originalCategory": "Medicamentos Orales"
  },
];
