// Seed products 81-120 (auto-generated split)
export const SEED_PRODUCTS_03 = [
  {
    "name": "Plaquinol 200 mg",
    "genericName": "Hidroxicloroquina",
    "laboratorio": "Plaquinol",
    "concentracion": "200 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 14.0,
    "costUsd": 9.1,
    "stock": 2,
    "barcode": "7590000000081",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000081.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Rivemol 10 mg",
    "genericName": "Rivaroxabán",
    "laboratorio": "Rivemol",
    "concentracion": "10 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 3,
    "barcode": "7590000000082",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000082.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Pharmatinex",
    "genericName": "Extracto Renal",
    "laboratorio": "Pharmatinex",
    "concentracion": "",
    "presentacion": "Caja",
    "category": "analgesicos",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 1,
    "barcode": "7590000000083",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000083.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Secnidazol 500 mg",
    "genericName": "Secnidazol",
    "laboratorio": "Genérico",
    "concentracion": "500 mg",
    "presentacion": "Tab x 4",
    "category": "antiparasitarios",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 6,
    "barcode": "7590000000084",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000084.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Sucralfato 1 g",
    "genericName": "Sucralfato",
    "laboratorio": "Genérico",
    "concentracion": "1 g",
    "presentacion": "Sobres",
    "category": "analgesicos",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 8,
    "barcode": "7590000000085",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000085.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Esomeprazol 40 mg",
    "genericName": "Esomeprazol",
    "laboratorio": "Genérico",
    "concentracion": "40 mg",
    "presentacion": "Blister x 10",
    "category": "gastrointestinal",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 7,
    "barcode": "7590000000086",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000086.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Esomeprazol 20 mg",
    "genericName": "Esomeprazol",
    "laboratorio": "Genérico",
    "concentracion": "20 mg",
    "presentacion": "Blister x 10",
    "category": "gastrointestinal",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 3,
    "barcode": "7590000000087",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000087.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Ulgarin 20 mg",
    "genericName": "Esomeprazol",
    "laboratorio": "Ulgarin",
    "concentracion": "20 mg",
    "presentacion": "Blister x 4",
    "category": "gastrointestinal",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 4,
    "barcode": "7590000000088",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000088.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Epitral 25 mg",
    "genericName": "Lamotrigina",
    "laboratorio": "Epitral",
    "concentracion": "25 mg",
    "presentacion": "Blister x 15",
    "category": "analgesicos",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 4,
    "barcode": "7590000000089",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000089.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Epivital Cap x 15",
    "genericName": "Multivitamínico Prenatal",
    "laboratorio": "Epivital",
    "concentracion": "Cap x 15",
    "presentacion": "Caja",
    "category": "analgesicos",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 2,
    "barcode": "7590000000090",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000090.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Zuzu 500 mg",
    "genericName": "Eritromicina",
    "laboratorio": "Zuzu",
    "concentracion": "500 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 1,
    "barcode": "7590000000091",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000091.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Bionapril 5 mg",
    "genericName": "Enalapril",
    "laboratorio": "Bionapril",
    "concentracion": "5 mg",
    "presentacion": "Blister x 10",
    "category": "cardiovascular",
    "priceUsd": 3.5,
    "costUsd": 2.27,
    "stock": 8,
    "barcode": "7590000000092",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000092.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Enalapril 10 mg (PlusAndex)",
    "genericName": "Enalapril",
    "laboratorio": "PlusAndex",
    "concentracion": "10 mg",
    "presentacion": "Blister x 10",
    "category": "cardiovascular",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 4,
    "barcode": "7590000000093",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000093.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Enalapril 10 mg (Genven)",
    "genericName": "Enalapril",
    "laboratorio": "Genven",
    "concentracion": "10 mg",
    "presentacion": "Blister x 10",
    "category": "cardiovascular",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 7,
    "barcode": "7590000000094",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000094.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Enalapril 20 mg (Genven)",
    "genericName": "Enalapril",
    "laboratorio": "Genven",
    "concentracion": "20 mg",
    "presentacion": "Blister x 10",
    "category": "cardiovascular",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 1,
    "barcode": "7590000000095",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000095.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Kimiceg 20 mg",
    "genericName": "Enalapril",
    "laboratorio": "Kimiceg",
    "concentracion": "20 mg",
    "presentacion": "Blister x 10",
    "category": "cardiovascular",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 2,
    "barcode": "7590000000096",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000096.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Eurofarma 60 mg",
    "genericName": "Etoricoxib",
    "laboratorio": "Eurofarma",
    "concentracion": "60 mg",
    "presentacion": "Tab x 14",
    "category": "analgesicos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 1,
    "barcode": "7590000000097",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000097.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Etoricoxib 60 mg (Drotafarma)",
    "genericName": "Etoricoxib",
    "laboratorio": "Drotafarma",
    "concentracion": "60 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 3,
    "barcode": "7590000000098",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000098.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Lattan 90 mg",
    "genericName": "Etoricoxib",
    "laboratorio": "Lattan",
    "concentracion": "90 mg",
    "presentacion": "Blister x 7",
    "category": "analgesicos",
    "priceUsd": 14.0,
    "costUsd": 9.1,
    "stock": 4,
    "barcode": "7590000000099",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000099.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Evigax 125 mg",
    "genericName": "Simeticona",
    "laboratorio": "Vivax",
    "concentracion": "125 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 9.0,
    "costUsd": 5.85,
    "stock": 1,
    "barcode": "7590000000100",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000100.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Siegfried 25 mg",
    "genericName": "Espironolactona",
    "laboratorio": "Siegfried",
    "concentracion": "25 mg",
    "presentacion": "Tab x 10",
    "category": "cardiovascular",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 4,
    "barcode": "7590000000101",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000101.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Espironolactona 25 mg (Drotafarma)",
    "genericName": "Espironolactona",
    "laboratorio": "Drotafarma",
    "concentracion": "25 mg",
    "presentacion": "Tab x 10",
    "category": "cardiovascular",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 1,
    "barcode": "7590000000102",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000102.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Farma D 1000 UI",
    "genericName": "Vitamina D3",
    "laboratorio": "Farma D",
    "concentracion": "1000 UI",
    "presentacion": "Blister x 10",
    "category": "vitaminas",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 8,
    "barcode": "7590000000103",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000103.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Farma D 2000 UI",
    "genericName": "Vitamina D3",
    "laboratorio": "Farma D",
    "concentracion": "2000 UI",
    "presentacion": "Blister x 10",
    "category": "vitaminas",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 3,
    "barcode": "7590000000104",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000104.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Flatoril 125 mg",
    "genericName": "Simeticona",
    "laboratorio": "Elmor",
    "concentracion": "125 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 9.0,
    "costUsd": 5.85,
    "stock": 2,
    "barcode": "7590000000105",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000105.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Festal (Tab x 10)",
    "genericName": "Enzimas Digestivas",
    "laboratorio": "Calox",
    "concentracion": "",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 9.0,
    "costUsd": 5.85,
    "stock": 2,
    "barcode": "7590000000106",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000106.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Flemibar 10/250 mg",
    "genericName": "Ambroxol + Clenbuterol",
    "laboratorio": "Rowe",
    "concentracion": "10/250 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 9.0,
    "costUsd": 5.85,
    "stock": 2,
    "barcode": "7590000000107",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000107.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Femmex Ultra",
    "genericName": "Ibuprofeno + Cafeína",
    "laboratorio": "Femmex Ultra",
    "concentracion": "",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 2,
    "barcode": "7590000000108",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000108.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Femmex Trío",
    "genericName": "Antiespasmódico",
    "laboratorio": "Femmex Trío",
    "concentracion": "",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 1,
    "barcode": "7590000000109",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000109.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Flavoxato 200 mg (Drotafarma)",
    "genericName": "Flavoxato",
    "laboratorio": "Drotafarma",
    "concentracion": "200 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 3,
    "barcode": "7590000000110",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000110.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Genurín 200 mg",
    "genericName": "Flavoxato",
    "laboratorio": "Elmor",
    "concentracion": "200 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 1,
    "barcode": "7590000000111",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000111.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Febrex 650 mg",
    "genericName": "Paracetamol",
    "laboratorio": "Klinos",
    "concentracion": "650 mg",
    "presentacion": "Tab x 7",
    "category": "analgesicos",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 2,
    "barcode": "7590000000112",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000112.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Nio 120 mg",
    "genericName": "Fexofenadina",
    "laboratorio": "Nio",
    "concentracion": "120 mg",
    "presentacion": "Tab x 10",
    "category": "antihistaminicos",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 2,
    "barcode": "7590000000113",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000113.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Dynalab 120 mg",
    "genericName": "Fexofenadina",
    "laboratorio": "Dynalab",
    "concentracion": "120 mg",
    "presentacion": "Tab x 10",
    "category": "antihistaminicos",
    "priceUsd": 7.0,
    "costUsd": 4.55,
    "stock": 1,
    "barcode": "7590000000114",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000114.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Ferroce",
    "genericName": "Antianémico",
    "laboratorio": "Ferroce",
    "concentracion": "",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 7.0,
    "costUsd": 4.55,
    "stock": 11,
    "barcode": "7590000000115",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000115.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Caplin Point 100 mg",
    "genericName": "Fenitoína",
    "laboratorio": "Caplin Point",
    "concentracion": "100 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 3,
    "barcode": "7590000000116",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000116.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Ferganic 40 mg",
    "genericName": "Hierro Polimaltosado",
    "laboratorio": "Ferganic",
    "concentracion": "40 mg",
    "presentacion": "Cap x 6",
    "category": "vitaminas",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 4,
    "barcode": "7590000000117",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000117.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Ferganic Folic 40/350 mg",
    "genericName": "Hierro + Ácido Fólico",
    "laboratorio": "Ferganic Folic",
    "concentracion": "40/350 mg",
    "presentacion": "Blister",
    "category": "vitaminas",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 3,
    "barcode": "7590000000118",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000118.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Uroprín 3 g",
    "genericName": "Fosfomicina",
    "laboratorio": "Uroprín",
    "concentracion": "3 g",
    "presentacion": "Sobre x 1",
    "category": "analgesicos",
    "priceUsd": 22.0,
    "costUsd": 14.3,
    "stock": 1,
    "barcode": "7590000000119",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000119.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Siegfried 20 mg",
    "genericName": "Furosemida",
    "laboratorio": "Siegfried",
    "concentracion": "20 mg",
    "presentacion": "Tab x 12",
    "category": "cardiovascular",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 1,
    "barcode": "7590000000120",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000120.jpg",
    "originalCategory": "Medicamentos Orales"
  },
];
