// Seed products 201-240 (auto-generated split)
export const SEED_PRODUCTS_06 = [
  {
    "name": "Tiocol",
    "genericName": "Tiocolchicósido",
    "laboratorio": "Tiocol",
    "concentracion": "",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 1,
    "barcode": "7590000000201",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000201.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Valsartán + HCT",
    "genericName": "Valsartán + HCT",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Tab x 14",
    "category": "analgesicos",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 1,
    "barcode": "7590000000202",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000202.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Ácido Acetilsalicílico (Drotafarma)",
    "genericName": "Ácido Acetilsalicílico",
    "laboratorio": "Drotafarma",
    "concentracion": "",
    "presentacion": "Blister x 10",
    "category": "analgesicos",
    "priceUsd": 1.5,
    "costUsd": 0.98,
    "stock": 15,
    "barcode": "7590000000203",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000203.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Kwality 81 mg",
    "genericName": "Aspirina",
    "laboratorio": "Kwality",
    "concentracion": "81 mg",
    "presentacion": "Blister x 10",
    "category": "analgesicos",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 5,
    "barcode": "7590000000204",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000204.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Analper Forte",
    "genericName": "Paracetamol + Cafeína",
    "laboratorio": "Analper Forte",
    "concentracion": "",
    "presentacion": "Caja x 10",
    "category": "analgesicos",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 2,
    "barcode": "7590000000205",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000205.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Acetaminofén 500 mg",
    "genericName": "Acetaminofén",
    "laboratorio": "Genérico",
    "concentracion": "500 mg",
    "presentacion": "Blister x 10",
    "category": "analgesicos",
    "priceUsd": 1.5,
    "costUsd": 0.98,
    "stock": 7,
    "barcode": "7590000000206",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000206.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Acetaminofén 650 mg (Calox)",
    "genericName": "Acetaminofén",
    "laboratorio": "Calox",
    "concentracion": "650 mg",
    "presentacion": "Caja x 10",
    "category": "analgesicos",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 2,
    "barcode": "7590000000207",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000207.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Ibuprofeno 200 mg",
    "genericName": "Ibuprofeno",
    "laboratorio": "Genérico",
    "concentracion": "200 mg",
    "presentacion": "Caja x 10",
    "category": "analgesicos",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 1,
    "barcode": "7590000000208",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000208.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Ibutan 600 mg",
    "genericName": "Ibuprofeno",
    "laboratorio": "Ibutan",
    "concentracion": "600 mg",
    "presentacion": "Caja x 10",
    "category": "analgesicos",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 4,
    "barcode": "7590000000209",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000209.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Ibuprofeno 400 mg",
    "genericName": "Ibuprofeno",
    "laboratorio": "Genérico",
    "concentracion": "400 mg",
    "presentacion": "Blister x 10",
    "category": "analgesicos",
    "priceUsd": 1.5,
    "costUsd": 0.98,
    "stock": 8,
    "barcode": "7590000000210",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000210.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Ibuprofeno 600 mg",
    "genericName": "Ibuprofeno",
    "laboratorio": "Genérico",
    "concentracion": "600 mg",
    "presentacion": "Blister x 10",
    "category": "analgesicos",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 7,
    "barcode": "7590000000211",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000211.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Ibuprofeno 800 mg",
    "genericName": "Ibuprofeno",
    "laboratorio": "Genérico",
    "concentracion": "800 mg",
    "presentacion": "Blister x 10",
    "category": "analgesicos",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 5,
    "barcode": "7590000000212",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000212.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Diclofenac Potásico 50 mg",
    "genericName": "Diclofenac Potásico",
    "laboratorio": "Genérico",
    "concentracion": "50 mg",
    "presentacion": "Caja x 10",
    "category": "analgesicos",
    "priceUsd": 1.5,
    "costUsd": 0.98,
    "stock": 2,
    "barcode": "7590000000213",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000213.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Loratadina 10 mg (Caja x 10)",
    "genericName": "Loratadina",
    "laboratorio": "Genérico",
    "concentracion": "10 mg",
    "presentacion": "Caja x 10",
    "category": "antihistaminicos",
    "priceUsd": 1.5,
    "costUsd": 0.98,
    "stock": 7,
    "barcode": "7590000000214",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000214.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Loratadina 10 mg (Blister x 10)",
    "genericName": "Loratadina",
    "laboratorio": "Genérico",
    "concentracion": "10 mg",
    "presentacion": "Blister x 10",
    "category": "antihistaminicos",
    "priceUsd": 1.5,
    "costUsd": 0.98,
    "stock": 11,
    "barcode": "7590000000215",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000215.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Cetirizina (Blister x 10)",
    "genericName": "Cetirizina",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Blister x 10",
    "category": "antihistaminicos",
    "priceUsd": 1.5,
    "costUsd": 0.98,
    "stock": 2,
    "barcode": "7590000000216",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000216.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Cetirizina (Caja x 10)",
    "genericName": "Cetirizina",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Caja x 10",
    "category": "antihistaminicos",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 6,
    "barcode": "7590000000217",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000217.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Cetirivax 10 mg",
    "genericName": "Cetirizina",
    "laboratorio": "Vivax",
    "concentracion": "10 mg",
    "presentacion": "Caja x 10",
    "category": "antihistaminicos",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 3,
    "barcode": "7590000000218",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000218.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Amoxicilina 500 mg",
    "genericName": "Amoxicilina",
    "laboratorio": "Genérico",
    "concentracion": "500 mg",
    "presentacion": "Blister x 10",
    "category": "antibioticos",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 4,
    "barcode": "7590000000219",
    "requiresPrescription": true,
    "isControlled": false,
    "image": "/products/7590000000219.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Aplacálico / Aplacal",
    "genericName": "Calcio",
    "laboratorio": "Aplacálico / Aplacal",
    "concentracion": "",
    "presentacion": "Blister x 4",
    "category": "vitaminas",
    "priceUsd": 3.5,
    "costUsd": 2.27,
    "stock": 3,
    "barcode": "7590000000220",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000220.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Festal (Blister x 4)",
    "genericName": "Enzimas Digestivas",
    "laboratorio": "Festal",
    "concentracion": "",
    "presentacion": "Blister x 4",
    "category": "analgesicos",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 4,
    "barcode": "7590000000221",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000221.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Losartán 50 mg",
    "genericName": "Losartán",
    "laboratorio": "Genérico",
    "concentracion": "50 mg",
    "presentacion": "Blister x 10",
    "category": "cardiovascular",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 8,
    "barcode": "7590000000222",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000222.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Losartán 100 mg",
    "genericName": "Losartán",
    "laboratorio": "Genérico",
    "concentracion": "100 mg",
    "presentacion": "Blister x 10",
    "category": "cardiovascular",
    "priceUsd": 2.5,
    "costUsd": 1.62,
    "stock": 11,
    "barcode": "7590000000223",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000223.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Metoclopramida 10 mg",
    "genericName": "Metoclopramida",
    "laboratorio": "Genérico",
    "concentracion": "10 mg",
    "presentacion": "Blister x 10",
    "category": "gastrointestinal",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 5,
    "barcode": "7590000000224",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000224.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Metronidazol 500 mg",
    "genericName": "Metronidazol",
    "laboratorio": "Genérico",
    "concentracion": "500 mg",
    "presentacion": "Blister x 10",
    "category": "antiparasitarios",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 6,
    "barcode": "7590000000225",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000225.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Multivitaminas",
    "genericName": "Multivitaminas",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Blister x 10",
    "category": "vitaminas",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 7,
    "barcode": "7590000000226",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000226.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Vitamina B",
    "genericName": "Vitamina B",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Blister x 10",
    "category": "vitaminas",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 6,
    "barcode": "7590000000227",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000227.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Sulfato Ferroso 300 mg",
    "genericName": "Sulfato Ferroso",
    "laboratorio": "Genérico",
    "concentracion": "300 mg",
    "presentacion": "Blister x 10",
    "category": "analgesicos",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 5,
    "barcode": "7590000000228",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000228.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Piroxicam 20 mg",
    "genericName": "Piroxicam",
    "laboratorio": "Genérico",
    "concentracion": "20 mg",
    "presentacion": "Blister x 10",
    "category": "analgesicos",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 4,
    "barcode": "7590000000229",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000229.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Digepost 4 g",
    "genericName": "Digepost Antiácido",
    "laboratorio": "Digepost",
    "concentracion": "4 g",
    "presentacion": "Sobre",
    "category": "analgesicos",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 2,
    "barcode": "7590000000230",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000230.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Alka-Seltzer",
    "genericName": "Alka-Seltzer",
    "laboratorio": "Bayer",
    "concentracion": "",
    "presentacion": "Blister x 2",
    "category": "analgesicos",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 6,
    "barcode": "7590000000231",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000231.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Gastro Full",
    "genericName": "Gastro Full Sobre",
    "laboratorio": "Gastro Full",
    "concentracion": "",
    "presentacion": "Sobre",
    "category": "analgesicos",
    "priceUsd": 2.5,
    "costUsd": 1.62,
    "stock": 8,
    "barcode": "7590000000232",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000232.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Omeprazol 20 mg (Caja x 10)",
    "genericName": "Omeprazol",
    "laboratorio": "Genérico",
    "concentracion": "20 mg",
    "presentacion": "Caja x 10",
    "category": "gastrointestinal",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 1,
    "barcode": "7590000000233",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000233.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Omeprazol 20 mg (Blister x 10)",
    "genericName": "Omeprazol",
    "laboratorio": "Genérico",
    "concentracion": "20 mg",
    "presentacion": "Blister x 10",
    "category": "gastrointestinal",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 5,
    "barcode": "7590000000234",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000234.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Angrip",
    "genericName": "Antigripal",
    "laboratorio": "Angrip",
    "concentracion": "",
    "presentacion": "Caja x 4",
    "category": "analgesicos",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 2,
    "barcode": "7590000000235",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000235.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Dynacet Grip Noche",
    "genericName": "Antigripal Noche",
    "laboratorio": "Dynacet Grip Noche",
    "concentracion": "",
    "presentacion": "Sobre",
    "category": "analgesicos",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 5,
    "barcode": "7590000000236",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000236.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Dynacet Grip Día",
    "genericName": "Antigripal Día",
    "laboratorio": "Dynacet Grip Día",
    "concentracion": "",
    "presentacion": "Sobre",
    "category": "analgesicos",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 7,
    "barcode": "7590000000237",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000237.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Anapir",
    "genericName": "Paracetamol",
    "laboratorio": "Anapir",
    "concentracion": "",
    "presentacion": "Blister x 10",
    "category": "analgesicos",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 3,
    "barcode": "7590000000238",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000238.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Dynacet Día",
    "genericName": "Antigripal Día",
    "laboratorio": "Dynacet Día",
    "concentracion": "",
    "presentacion": "Caja x 10",
    "category": "analgesicos",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 4,
    "barcode": "7590000000239",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000239.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Fin-Al-Grip Día",
    "genericName": "Antigripal Día",
    "laboratorio": "Fin-Al-Grip Día",
    "concentracion": "",
    "presentacion": "Caja x 10",
    "category": "analgesicos",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 5,
    "barcode": "7590000000240",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000240.jpg",
    "originalCategory": "Medicamentos Orales"
  },
];
