// Seed products 41-80 (auto-generated split)
export const SEED_PRODUCTS_02 = [
  {
    "name": "La Santé 100 mg",
    "genericName": "Atenolol",
    "laboratorio": "La Santé",
    "concentracion": "100 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 6,
    "barcode": "7590000000041",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000041.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Antifom Vargas 125 mg",
    "genericName": "Simeticona",
    "laboratorio": "Vargas",
    "concentracion": "125 mg",
    "presentacion": "Caja",
    "category": "analgesicos",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 1,
    "barcode": "7590000000042",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000042.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Antifom Vargas 40 mg",
    "genericName": "Simeticona",
    "laboratorio": "Vargas",
    "concentracion": "40 mg",
    "presentacion": "Caja",
    "category": "analgesicos",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 2,
    "barcode": "7590000000043",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000043.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Asaprol 81 mg",
    "genericName": "Ácido Acetilsalicílico",
    "laboratorio": "Asaprol",
    "concentracion": "81 mg",
    "presentacion": "Caja",
    "category": "analgesicos",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 2,
    "barcode": "7590000000044",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000044.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Artrovit",
    "genericName": "Glucosamina + Condroitina",
    "laboratorio": "Artrovit",
    "concentracion": "",
    "presentacion": "Blister",
    "category": "analgesicos",
    "priceUsd": 7.0,
    "costUsd": 4.55,
    "stock": 3,
    "barcode": "7590000000045",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000045.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Atorvastatina 80 mg (Protafarma)",
    "genericName": "Atorvastatina",
    "laboratorio": "Protafarma",
    "concentracion": "80 mg",
    "presentacion": "Blister x 10",
    "category": "cardiovascular",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 5,
    "barcode": "7590000000046",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000046.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Atorvastatina 40 mg (Drotafarma)",
    "genericName": "Atorvastatina",
    "laboratorio": "Drotafarma",
    "concentracion": "40 mg",
    "presentacion": "Blister x 10",
    "category": "cardiovascular",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 4,
    "barcode": "7590000000047",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000047.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Spefar 20 mg",
    "genericName": "Atorvastatina",
    "laboratorio": "Spefar",
    "concentracion": "20 mg",
    "presentacion": "Blister x 10",
    "category": "cardiovascular",
    "priceUsd": 3.5,
    "costUsd": 2.27,
    "stock": 2,
    "barcode": "7590000000048",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000048.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Atorvastatina 20 mg (Genven)",
    "genericName": "Atorvastatina",
    "laboratorio": "Genven",
    "concentracion": "20 mg",
    "presentacion": "Blister x 10",
    "category": "cardiovascular",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 1,
    "barcode": "7590000000049",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000049.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Atorvastatina 20 mg (Protafarma)",
    "genericName": "Atorvastatina",
    "laboratorio": "Protafarma",
    "concentracion": "20 mg",
    "presentacion": "Blister x 10",
    "category": "cardiovascular",
    "priceUsd": 3.5,
    "costUsd": 2.27,
    "stock": 1,
    "barcode": "7590000000050",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000050.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Spefar 10 mg",
    "genericName": "Atorvastatina",
    "laboratorio": "Spefar",
    "concentracion": "10 mg",
    "presentacion": "Blister x 10",
    "category": "cardiovascular",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 1,
    "barcode": "7590000000051",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000051.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Brieta 10 mg",
    "genericName": "Atorvastatina",
    "laboratorio": "Brieta",
    "concentracion": "10 mg",
    "presentacion": "Blister x 10",
    "category": "cardiovascular",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 3,
    "barcode": "7590000000052",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000052.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Candexil 20/5 mg",
    "genericName": "Atorvastatina + Amlodipina",
    "laboratorio": "Candexil",
    "concentracion": "20/5 mg",
    "presentacion": "Caja x 10",
    "category": "cardiovascular",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 1,
    "barcode": "7590000000053",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000053.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Cariban 10 mg",
    "genericName": "Piridoxina + Doxilamina",
    "laboratorio": "Cariban",
    "concentracion": "10 mg",
    "presentacion": "Caja x 10",
    "category": "analgesicos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 2,
    "barcode": "7590000000054",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000054.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Land 16 mg",
    "genericName": "Candesartán",
    "laboratorio": "Land",
    "concentracion": "16 mg",
    "presentacion": "Blister x 10",
    "category": "analgesicos",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 1,
    "barcode": "7590000000055",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000055.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Ciprofloxacina 500 mg (Protafarma)",
    "genericName": "Ciprofloxacina",
    "laboratorio": "Protafarma",
    "concentracion": "500 mg",
    "presentacion": "Blister x 10",
    "category": "antibioticos",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 4,
    "barcode": "7590000000056",
    "requiresPrescription": true,
    "isControlled": false,
    "image": "/products/7590000000056.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Carbamazepina 200 mg (Protafarma)",
    "genericName": "Carbamazepina",
    "laboratorio": "Protafarma",
    "concentracion": "200 mg",
    "presentacion": "Blister x 10",
    "category": "analgesicos",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 1,
    "barcode": "7590000000057",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000057.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Nió 300 mg",
    "genericName": "Carbonato de Litio",
    "laboratorio": "Nió",
    "concentracion": "300 mg",
    "presentacion": "Blister x 10",
    "category": "analgesicos",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 2,
    "barcode": "7590000000058",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000058.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Colchicina 500 mcg",
    "genericName": "Colchicina",
    "laboratorio": "Genérico",
    "concentracion": "500 mcg",
    "presentacion": "Blister x 10",
    "category": "analgesicos",
    "priceUsd": 3.5,
    "costUsd": 2.27,
    "stock": 4,
    "barcode": "7590000000059",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000059.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Cevax 500 mg",
    "genericName": "Cefadroxilo",
    "laboratorio": "Cevax",
    "concentracion": "500 mg",
    "presentacion": "Blister x 10",
    "category": "analgesicos",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 2,
    "barcode": "7590000000060",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000060.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Cefalexina 500 mg (Calox)",
    "genericName": "Cefalexina",
    "laboratorio": "Calox",
    "concentracion": "500 mg",
    "presentacion": "Tab x 8",
    "category": "antibioticos",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 3,
    "barcode": "7590000000061",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000061.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Cetral 10 mg",
    "genericName": "Cetirizina",
    "laboratorio": "Cetral",
    "concentracion": "10 mg",
    "presentacion": "Tab x 10",
    "category": "antihistaminicos",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 6,
    "barcode": "7590000000062",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000062.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Cypral 500 mg",
    "genericName": "Ciprofloxacina",
    "laboratorio": "Cypral",
    "concentracion": "500 mg",
    "presentacion": "Tab x 10",
    "category": "antibioticos",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 4,
    "barcode": "7590000000063",
    "requiresPrescription": true,
    "isControlled": false,
    "image": "/products/7590000000063.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Clorace 4 mg",
    "genericName": "Clorfeniramina",
    "laboratorio": "Clorace",
    "concentracion": "4 mg",
    "presentacion": "Tab x 10",
    "category": "antihistaminicos",
    "priceUsd": 1.5,
    "costUsd": 0.98,
    "stock": 3,
    "barcode": "7590000000064",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000064.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Clonidina 0.150 mg",
    "genericName": "Clonidina",
    "laboratorio": "Genérico",
    "concentracion": "0.150 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 4,
    "barcode": "7590000000065",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000065.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Cuticlin 10 mg",
    "genericName": "Isotretinoína",
    "laboratorio": "Cuticlin",
    "concentracion": "10 mg",
    "presentacion": "Caja x 30",
    "category": "analgesicos",
    "priceUsd": 30.0,
    "costUsd": 19.5,
    "stock": 1,
    "barcode": "7590000000066",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000066.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Clopimany 75 mg",
    "genericName": "Clopidogrel",
    "laboratorio": "Clopimany",
    "concentracion": "75 mg",
    "presentacion": "Tab x 10",
    "category": "cardiovascular",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 2,
    "barcode": "7590000000067",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000067.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Ibudual 200/500 mg",
    "genericName": "Ibuprofeno + Paracetamol",
    "laboratorio": "Ibudual",
    "concentracion": "200/500 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 2,
    "barcode": "7590000000068",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000068.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Eusilen 50/2.5 mg",
    "genericName": "Sulpirida + Diazepam",
    "laboratorio": "Eusilen",
    "concentracion": "50/2.5 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 3,
    "barcode": "7590000000069",
    "requiresPrescription": false,
    "isControlled": true,
    "image": "/products/7590000000069.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Irbesartán 150 mg",
    "genericName": "Irbesartán",
    "laboratorio": "Genérico",
    "concentracion": "150 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 4,
    "barcode": "7590000000070",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000070.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Aitirex 50 mcg",
    "genericName": "Levotiroxina Sódica",
    "laboratorio": "Aitirex",
    "concentracion": "50 mcg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 3.5,
    "costUsd": 2.27,
    "stock": 2,
    "barcode": "7590000000071",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000071.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Sorkinox 500 mg",
    "genericName": "Secnidazol",
    "laboratorio": "Pharma",
    "concentracion": "500 mg",
    "presentacion": "Tab x 4",
    "category": "antiparasitarios",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 3,
    "barcode": "7590000000072",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000072.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Sinemet 250/25 mg",
    "genericName": "Levodopa + Carbidopa",
    "laboratorio": "Sinemet",
    "concentracion": "250/25 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 2,
    "barcode": "7590000000073",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000073.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Loperamida 2 mg",
    "genericName": "Loperamida",
    "laboratorio": "Genérico",
    "concentracion": "2 mg",
    "presentacion": "Tab x 10",
    "category": "gastrointestinal",
    "priceUsd": 1.5,
    "costUsd": 0.98,
    "stock": 8,
    "barcode": "7590000000074",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000074.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Nefrotal 50 mg",
    "genericName": "Losartán Potásico",
    "laboratorio": "Nefrotal",
    "concentracion": "50 mg",
    "presentacion": "Tab x 10",
    "category": "cardiovascular",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 4,
    "barcode": "7590000000075",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000075.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Prednisona 50 mg",
    "genericName": "Prednisona",
    "laboratorio": "Genérico",
    "concentracion": "50 mg",
    "presentacion": "Tab x 10",
    "category": "antiinflamatorios",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 4,
    "barcode": "7590000000076",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000076.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Prednisona 20 mg",
    "genericName": "Prednisona",
    "laboratorio": "Genérico",
    "concentracion": "20 mg",
    "presentacion": "Tab x 10",
    "category": "antiinflamatorios",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 6,
    "barcode": "7590000000077",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000077.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Prednisona 5 mg",
    "genericName": "Prednisona",
    "laboratorio": "Genérico",
    "concentracion": "5 mg",
    "presentacion": "Tab x 10",
    "category": "antiinflamatorios",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 5,
    "barcode": "7590000000078",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000078.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Pregabalina 75 mg",
    "genericName": "Pregabalina",
    "laboratorio": "Genérico",
    "concentracion": "75 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 5,
    "barcode": "7590000000079",
    "requiresPrescription": true,
    "isControlled": false,
    "image": "/products/7590000000079.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Pregabalina 150 mg",
    "genericName": "Pregabalina",
    "laboratorio": "Genérico",
    "concentracion": "150 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 3,
    "barcode": "7590000000080",
    "requiresPrescription": true,
    "isControlled": false,
    "image": "/products/7590000000080.jpg",
    "originalCategory": "Medicamentos Orales"
  },
];
