// Seed products 641-666 (auto-generated split)
export const SEED_PRODUCTS_17 = [
  {
    "name": "Pilas Verdes AA/AAA",
    "genericName": "Pilas Verdes",
    "laboratorio": "Genérico",
    "concentracion": "AA/AAA",
    "presentacion": "Unidad",
    "category": "cuidado-personal",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 2,
    "barcode": "7590000000641",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000641.jpg",
    "originalCategory": "Misceláneos y Cuidado Personal"
  },
  {
    "name": "Limpia Teteros",
    "genericName": "Limpia Teteros",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "cuidado-personal",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 2,
    "barcode": "7590000000642",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000642.jpg",
    "originalCategory": "Misceláneos y Cuidado Personal"
  },
  {
    "name": "Pera Rectal",
    "genericName": "Pera Rectal",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "cuidado-personal",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 3,
    "barcode": "7590000000643",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000643.jpg",
    "originalCategory": "Misceláneos y Cuidado Personal"
  },
  {
    "name": "Pera Nasal Pediátrica",
    "genericName": "Pera Nasal Pediátrica",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "cuidado-personal",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 6,
    "barcode": "7590000000644",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000644.jpg",
    "originalCategory": "Misceláneos y Cuidado Personal"
  },
  {
    "name": "Ducha Vaginal",
    "genericName": "Ducha Vaginal",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "cuidado-personal",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 1,
    "barcode": "7590000000645",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000645.jpg",
    "originalCategory": "Misceláneos y Cuidado Personal"
  },
  {
    "name": "Prestobarba Gillette Negra",
    "genericName": "Prestobarba Negra",
    "laboratorio": "Gillette",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "cuidado-personal",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 24,
    "barcode": "7590000000646",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000646.jpg",
    "originalCategory": "Misceláneos y Cuidado Personal"
  },
  {
    "name": "Prestobarba Gillette Rosada",
    "genericName": "Prestobarba Rosada",
    "laboratorio": "Gillette",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "cuidado-personal",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 2,
    "barcode": "7590000000647",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000647.jpg",
    "originalCategory": "Misceláneos y Cuidado Personal"
  },
  {
    "name": "Prueba de Embarazo Tira/Cassette",
    "genericName": "Prueba de Embarazo",
    "laboratorio": "Genérico",
    "concentracion": "Tira/Cassette",
    "presentacion": "Unidad",
    "category": "cuidado-personal",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 8,
    "barcode": "7590000000648",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000648.jpg",
    "originalCategory": "Misceláneos y Cuidado Personal"
  },
  {
    "name": "Zoológico Intestinal Suspensión",
    "genericName": "Zoológico Intestinal",
    "laboratorio": "Genérico",
    "concentracion": "Suspensión",
    "presentacion": "Frasco",
    "category": "cuidado-personal",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 2,
    "barcode": "7590000000649",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000649.jpg",
    "originalCategory": "Misceláneos y Cuidado Personal"
  },
  {
    "name": "Bicarbonato de Sodio Sobre",
    "genericName": "Bicarbonato de Sodio",
    "laboratorio": "Genérico",
    "concentracion": "Sobre",
    "presentacion": "Sobres",
    "category": "cuidado-personal",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 5,
    "barcode": "7590000000650",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000650.jpg",
    "originalCategory": "Misceláneos y Cuidado Personal"
  },
  {
    "name": "Cloruro de Magnesio Polvo Sobre",
    "genericName": "Cloruro de Magnesio Polvo",
    "laboratorio": "Genérico",
    "concentracion": "Sobre",
    "presentacion": "Sobres",
    "category": "cuidado-personal",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 1,
    "barcode": "7590000000651",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000651.jpg",
    "originalCategory": "Misceláneos y Cuidado Personal"
  },
  {
    "name": "Sal de Higuera (Sulfato Magnesio) Sobre",
    "genericName": "Sal de Higuera (Sulfato Magnesio)",
    "laboratorio": "Genérico",
    "concentracion": "Sobre",
    "presentacion": "Sobres",
    "category": "cuidado-personal",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 2,
    "barcode": "7590000000652",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000652.jpg",
    "originalCategory": "Misceláneos y Cuidado Personal"
  },
  {
    "name": "Alumbre en Polvo Sobre",
    "genericName": "Alumbre en Polvo",
    "laboratorio": "Genérico",
    "concentracion": "Sobre",
    "presentacion": "Sobres",
    "category": "cuidado-personal",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 5,
    "barcode": "7590000000653",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000653.jpg",
    "originalCategory": "Misceláneos y Cuidado Personal"
  },
  {
    "name": "Ácido Bórico Polvo Sobre",
    "genericName": "Ácido Bórico Polvo",
    "laboratorio": "Genérico",
    "concentracion": "Sobre",
    "presentacion": "Sobres",
    "category": "cuidado-personal",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 1,
    "barcode": "7590000000654",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000654.jpg",
    "originalCategory": "Misceláneos y Cuidado Personal"
  },
  {
    "name": "Manta Térmica Bebé",
    "genericName": "Manta Térmica Bebé",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "cuidado-personal",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 6,
    "barcode": "7590000000655",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000655.jpg",
    "originalCategory": "Misceláneos y Cuidado Personal"
  },
  {
    "name": "Ropa de Bebé",
    "genericName": "Ropa de Bebé",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Set",
    "category": "cuidado-personal",
    "priceUsd": 7.0,
    "costUsd": 4.55,
    "stock": 9,
    "barcode": "7590000000656",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000656.jpg",
    "originalCategory": "Misceláneos y Cuidado Personal"
  },
  {
    "name": "Curitas Adhesivas Tira",
    "genericName": "Curitas Adhesivas",
    "laboratorio": "Genérico",
    "concentracion": "Tira",
    "presentacion": "Unidades",
    "category": "cuidado-personal",
    "priceUsd": 0.15,
    "costUsd": 0.1,
    "stock": 94,
    "barcode": "7590000000657",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000657.jpg",
    "originalCategory": "Misceláneos y Cuidado Personal"
  },
  {
    "name": "Tapabocas Quirúrgicos Caja/Pack",
    "genericName": "Tapabocas Quirúrgicos",
    "laboratorio": "Genérico",
    "concentracion": "Caja/Pack",
    "presentacion": "Unidades",
    "category": "cuidado-personal",
    "priceUsd": 0.1,
    "costUsd": 0.07,
    "stock": 500,
    "barcode": "7590000000658",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000658.jpg",
    "originalCategory": "Misceláneos y Cuidado Personal"
  },
  {
    "name": "Tapabocas KN95",
    "genericName": "Tapabocas KN95",
    "laboratorio": "Genérico",
    "concentracion": "KN95",
    "presentacion": "Unidades",
    "category": "cuidado-personal",
    "priceUsd": 1.0,
    "costUsd": 0.65,
    "stock": 17,
    "barcode": "7590000000659",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000659.jpg",
    "originalCategory": "Misceláneos y Cuidado Personal"
  },
  {
    "name": "Vick VapoRub Pote",
    "genericName": "Vick VapoRub",
    "laboratorio": "Procter&Gamble",
    "concentracion": "Pote",
    "presentacion": "Potes",
    "category": "cuidado-personal",
    "priceUsd": 2.5,
    "costUsd": 1.62,
    "stock": 5,
    "barcode": "7590000000660",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000660.jpg",
    "originalCategory": "Misceláneos y Cuidado Personal"
  },
  {
    "name": "Vaselina Labial Tubo",
    "genericName": "Vaselina Labial",
    "laboratorio": "Genérico",
    "concentracion": "10 g",
    "presentacion": "Tubo",
    "category": "cuidado-personal",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 5,
    "barcode": "7590000000661",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000661.jpg",
    "originalCategory": "Misceláneos y Cuidado Personal"
  },
  {
    "name": "Mentol Davis Pote",
    "genericName": "Mentol Davis",
    "laboratorio": "Davis",
    "concentracion": "Pote",
    "presentacion": "Potes",
    "category": "cuidado-personal",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 2,
    "barcode": "7590000000662",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000662.jpg",
    "originalCategory": "Misceláneos y Cuidado Personal"
  },
  {
    "name": "Cortaúñas Pediátrico/Adulto",
    "genericName": "Cortaúñas Pediátrico/Adulto",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "cuidado-personal",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 4,
    "barcode": "7590000000663",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000663.jpg",
    "originalCategory": "Misceláneos y Cuidado Personal"
  },
  {
    "name": "Termómetro de Mercurio Clínico",
    "genericName": "Termómetro de Mercurio Clínico",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "otros",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 6,
    "barcode": "7590000000664",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000664.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Termómetro Digital",
    "genericName": "Termómetro Digital",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "otros",
    "priceUsd": 7.0,
    "costUsd": 4.55,
    "stock": 17,
    "barcode": "7590000000665",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000665.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Vitafer-L Gold Sobre",
    "genericName": "Vitafer-L Gold",
    "laboratorio": "Vitafer",
    "concentracion": "Sobre",
    "presentacion": "Sobres",
    "category": "cuidado-personal",
    "priceUsd": 3.5,
    "costUsd": 2.27,
    "stock": 8,
    "barcode": "7590000000666",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000666.jpg",
    "originalCategory": "Misceláneos y Cuidado Personal"
  }
];
