// Seed products 321-360 (auto-generated split)
export const SEED_PRODUCTS_09 = [
  {
    "name": "Solución Ringer Lactato",
    "genericName": "Solución Ringer Lactato",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Bolsa 500ml",
    "category": "analgesicos",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 9,
    "barcode": "7590000000321",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000321.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Solución Fisiológica 0.9%",
    "genericName": "Solución Fisiológica 0.9%",
    "laboratorio": "Genérico",
    "concentracion": "0.9%",
    "presentacion": "Bolsa 500ml",
    "category": "analgesicos",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 7,
    "barcode": "7590000000322",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000322.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Bargonil 2%",
    "genericName": "Clotrimazol 2%",
    "laboratorio": "Rowe",
    "concentracion": "2%",
    "presentacion": "Tubo",
    "category": "materno-infantil",
    "priceUsd": 25.0,
    "costUsd": 16.25,
    "stock": 1,
    "barcode": "7590000000323",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000323.jpg",
    "originalCategory": "Ginecología y Vaginales"
  },
  {
    "name": "Bargonil Genérico 2%",
    "genericName": "Clotrimazol 2%",
    "laboratorio": "Bargonil Genérico",
    "concentracion": "2%",
    "presentacion": "Tubo",
    "category": "materno-infantil",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 2,
    "barcode": "7590000000324",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000324.jpg",
    "originalCategory": "Ginecología y Vaginales"
  },
  {
    "name": "Anomex Supositorio",
    "genericName": "Antihemorroidal",
    "laboratorio": "Anomex",
    "concentracion": "Supositorio",
    "presentacion": "Unidad",
    "category": "materno-infantil",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 12,
    "barcode": "7590000000325",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000325.jpg",
    "originalCategory": "Ginecología y Vaginales"
  },
  {
    "name": "Aflamax Supositorio",
    "genericName": "Diclofenac Potásico",
    "laboratorio": "Aflamax",
    "concentracion": "Supositorio",
    "presentacion": "Unidad",
    "category": "materno-infantil",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 11,
    "barcode": "7590000000326",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000326.jpg",
    "originalCategory": "Ginecología y Vaginales"
  },
  {
    "name": "Diclofenac 50 mg",
    "genericName": "Diclofenac",
    "laboratorio": "Genérico",
    "concentracion": "50 mg",
    "presentacion": "Supositorio",
    "category": "materno-infantil",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 8,
    "barcode": "7590000000327",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000327.jpg",
    "originalCategory": "Ginecología y Vaginales"
  },
  {
    "name": "Diclofenac 100 mg",
    "genericName": "Diclofenac",
    "laboratorio": "Genérico",
    "concentracion": "100 mg",
    "presentacion": "Supositorio",
    "category": "materno-infantil",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 33,
    "barcode": "7590000000328",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000328.jpg",
    "originalCategory": "Ginecología y Vaginales"
  },
  {
    "name": "Progesterona x 6 óvulos",
    "genericName": "Progesterona",
    "laboratorio": "Genérico",
    "concentracion": "x 6 óvulos",
    "presentacion": "Caja",
    "category": "materno-infantil",
    "priceUsd": 20.0,
    "costUsd": 13.0,
    "stock": 1,
    "barcode": "7590000000329",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000329.jpg",
    "originalCategory": "Ginecología y Vaginales"
  },
  {
    "name": "Progesterona x 5 óvulos",
    "genericName": "Progesterona",
    "laboratorio": "Genérico",
    "concentracion": "x 5 óvulos",
    "presentacion": "Caja",
    "category": "materno-infantil",
    "priceUsd": 20.0,
    "costUsd": 13.0,
    "stock": 6,
    "barcode": "7590000000330",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000330.jpg",
    "originalCategory": "Ginecología y Vaginales"
  },
  {
    "name": "Ilana 1 cap",
    "genericName": "Fluconazol / Itraconazol",
    "laboratorio": "Ilana",
    "concentracion": "1 cap",
    "presentacion": "Caja",
    "category": "materno-infantil",
    "priceUsd": 9.0,
    "costUsd": 5.85,
    "stock": 3,
    "barcode": "7590000000331",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000331.jpg",
    "originalCategory": "Ginecología y Vaginales"
  },
  {
    "name": "Solfem x 5 óvulos",
    "genericName": "Promestrieno",
    "laboratorio": "Solfem",
    "concentracion": "x 5 óvulos",
    "presentacion": "Caja",
    "category": "materno-infantil",
    "priceUsd": 35.0,
    "costUsd": 22.75,
    "stock": 2,
    "barcode": "7590000000332",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000332.jpg",
    "originalCategory": "Ginecología y Vaginales"
  },
  {
    "name": "Gynoderain x 6 óvulos",
    "genericName": "Centella + Neomicina + Polimixina",
    "laboratorio": "Gynoderain",
    "concentracion": "x 6 óvulos",
    "presentacion": "Caja",
    "category": "materno-infantil",
    "priceUsd": 30.0,
    "costUsd": 19.5,
    "stock": 2,
    "barcode": "7590000000333",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000333.jpg",
    "originalCategory": "Ginecología y Vaginales"
  },
  {
    "name": "Metronidazol x 10 tab vaginal",
    "genericName": "Metronidazol",
    "laboratorio": "Genérico",
    "concentracion": "x 10 tab vaginal",
    "presentacion": "Blister",
    "category": "materno-infantil",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 4,
    "barcode": "7590000000334",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000334.jpg",
    "originalCategory": "Ginecología y Vaginales"
  },
  {
    "name": "Candibrix x 6 óvulos",
    "genericName": "Clotrimazol",
    "laboratorio": "Candibrix",
    "concentracion": "x 6 óvulos",
    "presentacion": "Caja",
    "category": "materno-infantil",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 1,
    "barcode": "7590000000335",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000335.jpg",
    "originalCategory": "Ginecología y Vaginales"
  },
  {
    "name": "Gynodac 1%",
    "genericName": "Tioconazol / Miconazol",
    "laboratorio": "Gynodac 1%",
    "concentracion": "1%",
    "presentacion": "Tubo",
    "category": "materno-infantil",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 3,
    "barcode": "7590000000336",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000336.jpg",
    "originalCategory": "Ginecología y Vaginales"
  },
  {
    "name": "Estriol 0.03 mg",
    "genericName": "Estriol",
    "laboratorio": "Genérico",
    "concentracion": "0.03 mg",
    "presentacion": "x 6 óvulos",
    "category": "materno-infantil",
    "priceUsd": 20.0,
    "costUsd": 13.0,
    "stock": 1,
    "barcode": "7590000000337",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000337.jpg",
    "originalCategory": "Ginecología y Vaginales"
  },
  {
    "name": "Nistatina x 1 óvulo",
    "genericName": "Nistatina",
    "laboratorio": "Genérico",
    "concentracion": "x 1 óvulo",
    "presentacion": "Unidad",
    "category": "materno-infantil",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 8,
    "barcode": "7590000000338",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000338.jpg",
    "originalCategory": "Ginecología y Vaginales"
  },
  {
    "name": "Clindamicina x 1 óvulo",
    "genericName": "Clindamicina",
    "laboratorio": "Genérico",
    "concentracion": "x 1 óvulo",
    "presentacion": "Unidad",
    "category": "materno-infantil",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 9,
    "barcode": "7590000000339",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000339.jpg",
    "originalCategory": "Ginecología y Vaginales"
  },
  {
    "name": "Clindamicina x 5 óvulos",
    "genericName": "Clindamicina",
    "laboratorio": "Genérico",
    "concentracion": "x 5 óvulos",
    "presentacion": "Caja",
    "category": "materno-infantil",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 1,
    "barcode": "7590000000340",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000340.jpg",
    "originalCategory": "Ginecología y Vaginales"
  },
  {
    "name": "Clindamicina x 7 óvulos",
    "genericName": "Clindamicina",
    "laboratorio": "Genérico",
    "concentracion": "x 7 óvulos",
    "presentacion": "Caja",
    "category": "materno-infantil",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 2,
    "barcode": "7590000000341",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000341.jpg",
    "originalCategory": "Ginecología y Vaginales"
  },
  {
    "name": "Estriol Gel",
    "genericName": "Estriol Gel",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Tubo",
    "category": "materno-infantil",
    "priceUsd": 20.0,
    "costUsd": 13.0,
    "stock": 1,
    "barcode": "7590000000342",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000342.jpg",
    "originalCategory": "Ginecología y Vaginales"
  },
  {
    "name": "Clikel Duo x 5 óvulos",
    "genericName": "Clindamicina + Ketoconazol",
    "laboratorio": "Clikel Duo",
    "concentracion": "x 5 óvulos",
    "presentacion": "Caja",
    "category": "materno-infantil",
    "priceUsd": 17.0,
    "costUsd": 11.05,
    "stock": 2,
    "barcode": "7590000000343",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000343.jpg",
    "originalCategory": "Ginecología y Vaginales"
  },
  {
    "name": "Clinfast x 3 óvulos",
    "genericName": "Clindamicina + Ketoconazol",
    "laboratorio": "Clinfast",
    "concentracion": "x 3 óvulos",
    "presentacion": "Caja",
    "category": "materno-infantil",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 2,
    "barcode": "7590000000344",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000344.jpg",
    "originalCategory": "Ginecología y Vaginales"
  },
  {
    "name": "Clotrimazol 500 mg",
    "genericName": "Clotrimazol",
    "laboratorio": "Genérico",
    "concentracion": "500 mg",
    "presentacion": "x 2 tab",
    "category": "materno-infantil",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 2,
    "barcode": "7590000000345",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000345.jpg",
    "originalCategory": "Ginecología y Vaginales"
  },
  {
    "name": "Metronidazol x 10 óvulos",
    "genericName": "Metronidazol",
    "laboratorio": "Genérico",
    "concentracion": "x 10 óvulos",
    "presentacion": "Blister",
    "category": "materno-infantil",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 7,
    "barcode": "7590000000346",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000346.jpg",
    "originalCategory": "Ginecología y Vaginales"
  },
  {
    "name": "Ovumix x 6 óvulos",
    "genericName": "Metronidazol + Miconazol + Polimixina",
    "laboratorio": "Ovumix",
    "concentracion": "x 6 óvulos",
    "presentacion": "Caja",
    "category": "materno-infantil",
    "priceUsd": 30.0,
    "costUsd": 19.5,
    "stock": 1,
    "barcode": "7590000000347",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000347.jpg",
    "originalCategory": "Ginecología y Vaginales"
  },
  {
    "name": "Trimix Forte x 7 óvulos",
    "genericName": "Neomicina + Polimixina + Nistatina",
    "laboratorio": "Trimix Forte",
    "concentracion": "x 7 óvulos",
    "presentacion": "Caja",
    "category": "materno-infantil",
    "priceUsd": 25.0,
    "costUsd": 16.25,
    "stock": 1,
    "barcode": "7590000000348",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000348.jpg",
    "originalCategory": "Ginecología y Vaginales"
  },
  {
    "name": "Metronidazol + Miconazol x 7 óvulos",
    "genericName": "Metronidazol + Miconazol",
    "laboratorio": "Genérico",
    "concentracion": "x 7 óvulos",
    "presentacion": "Caja",
    "category": "materno-infantil",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 2,
    "barcode": "7590000000349",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000349.jpg",
    "originalCategory": "Ginecología y Vaginales"
  },
  {
    "name": "Aless x 10 óvulos",
    "genericName": "Metronidazol",
    "laboratorio": "Aless",
    "concentracion": "x 10 óvulos",
    "presentacion": "Caja",
    "category": "materno-infantil",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 1,
    "barcode": "7590000000350",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000350.jpg",
    "originalCategory": "Ginecología y Vaginales"
  },
  {
    "name": "Clotrimazol x 1 óvulo",
    "genericName": "Clotrimazol",
    "laboratorio": "Genérico",
    "concentracion": "x 1 óvulo",
    "presentacion": "Caja",
    "category": "materno-infantil",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 2,
    "barcode": "7590000000351",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000351.jpg",
    "originalCategory": "Ginecología y Vaginales"
  },
  {
    "name": "Clotrimazol x 3 óvulos",
    "genericName": "Clotrimazol",
    "laboratorio": "Genérico",
    "concentracion": "x 3 óvulos",
    "presentacion": "Caja",
    "category": "materno-infantil",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 1,
    "barcode": "7590000000352",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000352.jpg",
    "originalCategory": "Ginecología y Vaginales"
  },
  {
    "name": "Cortix x 3 óvulos",
    "genericName": "Clotrimazol",
    "laboratorio": "Cortix",
    "concentracion": "x 3 óvulos",
    "presentacion": "Caja",
    "category": "materno-infantil",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 3,
    "barcode": "7590000000353",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000353.jpg",
    "originalCategory": "Ginecología y Vaginales"
  },
  {
    "name": "Imazol 500 mg (Cap x 1)",
    "genericName": "Clotrimazol",
    "laboratorio": "Imazol",
    "concentracion": "500 mg",
    "presentacion": "Cap x 1",
    "category": "materno-infantil",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 1,
    "barcode": "7590000000354",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000354.jpg",
    "originalCategory": "Ginecología y Vaginales"
  },
  {
    "name": "Imazol 500 mg (Tubo)",
    "genericName": "Clotrimazol Crema",
    "laboratorio": "Imazol",
    "concentracion": "500 mg",
    "presentacion": "Tubo",
    "category": "materno-infantil",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 2,
    "barcode": "7590000000355",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000355.jpg",
    "originalCategory": "Ginecología y Vaginales"
  },
  {
    "name": "Gynotran x 7 óvulos",
    "genericName": "Metronidazol + Nitrato de Miconazol",
    "laboratorio": "Gynotran",
    "concentracion": "x 7 óvulos",
    "presentacion": "Caja",
    "category": "materno-infantil",
    "priceUsd": 30.0,
    "costUsd": 19.5,
    "stock": 1,
    "barcode": "7590000000356",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000356.jpg",
    "originalCategory": "Ginecología y Vaginales"
  },
  {
    "name": "Gynotran Crema",
    "genericName": "Metronidazol + Nitrato de Miconazol",
    "laboratorio": "Gynotran Crema",
    "concentracion": "",
    "presentacion": "Tubo",
    "category": "materno-infantil",
    "priceUsd": 25.0,
    "costUsd": 16.25,
    "stock": 2,
    "barcode": "7590000000357",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000357.jpg",
    "originalCategory": "Ginecología y Vaginales"
  },
  {
    "name": "Clotrimazol Crema Vaginal",
    "genericName": "Clotrimazol Crema Vaginal",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Tubo",
    "category": "materno-infantil",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 3,
    "barcode": "7590000000358",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000358.jpg",
    "originalCategory": "Ginecología y Vaginales"
  },
  {
    "name": "Gyno-Canderm x 7 óvulos",
    "genericName": "Clotrimazol",
    "laboratorio": "Gyno-Canderm",
    "concentracion": "x 7 óvulos",
    "presentacion": "Caja",
    "category": "materno-infantil",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 3,
    "barcode": "7590000000359",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000359.jpg",
    "originalCategory": "Ginecología y Vaginales"
  },
  {
    "name": "Redu-Gras x 30 tab",
    "genericName": "Redu-Gras",
    "laboratorio": "Redu-Gras",
    "concentracion": "x 30 tab",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 16.0,
    "costUsd": 10.4,
    "stock": 1,
    "barcode": "7590000000360",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000360.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
];
