// Seed products 281-320 (auto-generated split)
export const SEED_PRODUCTS_08 = [
  {
    "name": "Diclofenac Sódico 75 mg",
    "genericName": "Diclofenac Sódico",
    "laboratorio": "Genérico",
    "concentracion": "75 mg",
    "presentacion": "Ampolla",
    "category": "analgesicos",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 16,
    "barcode": "7590000000281",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000281.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Digoxina 0.25 mg/ml",
    "genericName": "Digoxina",
    "laboratorio": "Genérico",
    "concentracion": "0.25 mg/ml",
    "presentacion": "Ampolla 2ml",
    "category": "analgesicos",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 2,
    "barcode": "7590000000282",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000282.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Dopamina 200 mg",
    "genericName": "Dopamina",
    "laboratorio": "Genérico",
    "concentracion": "200 mg",
    "presentacion": "Ampolla",
    "category": "analgesicos",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 4,
    "barcode": "7590000000283",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000283.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Duvadilan 10 mg",
    "genericName": "Isoxsuprina",
    "laboratorio": "Duvadilan",
    "concentracion": "10 mg",
    "presentacion": "Ampolla",
    "category": "analgesicos",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 7,
    "barcode": "7590000000284",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000284.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Isoxsuprina 10 mg",
    "genericName": "Isoxsuprina",
    "laboratorio": "Genérico",
    "concentracion": "10 mg",
    "presentacion": "Ampolla",
    "category": "analgesicos",
    "priceUsd": 9.0,
    "costUsd": 5.85,
    "stock": 5,
    "barcode": "7590000000285",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000285.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Cifarcaína 1%",
    "genericName": "Lidocaína Clorhidrato",
    "laboratorio": "Laferca",
    "concentracion": "1%",
    "presentacion": "Fco 100ml",
    "category": "analgesicos",
    "priceUsd": 20.0,
    "costUsd": 13.0,
    "stock": 2,
    "barcode": "7590000000286",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000286.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Ciprofloxacina IV 200 mg/100 ml (Drotafarma)",
    "genericName": "Ciprofloxacina IV",
    "laboratorio": "Drotafarma",
    "concentracion": "200 mg/100 ml",
    "presentacion": "Frasco IV",
    "category": "analgesicos",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 7,
    "barcode": "7590000000287",
    "requiresPrescription": true,
    "isControlled": false,
    "image": "/products/7590000000287.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Distrilab 200 mg/100 ml",
    "genericName": "Ciprofloxacina IV",
    "laboratorio": "Distrilab",
    "concentracion": "200 mg/100 ml",
    "presentacion": "Frasco IV",
    "category": "analgesicos",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 4,
    "barcode": "7590000000288",
    "requiresPrescription": true,
    "isControlled": false,
    "image": "/products/7590000000288.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Bumelex 2 ml",
    "genericName": "Bumetanida",
    "laboratorio": "Bumelex",
    "concentracion": "2 ml",
    "presentacion": "Ampolla",
    "category": "analgesicos",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 2,
    "barcode": "7590000000289",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000289.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Betagen 12 mg/3 ml",
    "genericName": "Betametasona",
    "laboratorio": "Betagen",
    "concentracion": "12 mg/3 ml",
    "presentacion": "Ampolla",
    "category": "analgesicos",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 1,
    "barcode": "7590000000290",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000290.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Atropina Sulfato 1 mg/1 ml",
    "genericName": "Atropina Sulfato",
    "laboratorio": "Genérico",
    "concentracion": "1 mg/1 ml",
    "presentacion": "Ampolla",
    "category": "analgesicos",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 28,
    "barcode": "7590000000291",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000291.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Nitroprusiato de Sodio 50 mg",
    "genericName": "Nitroprusiato de Sodio",
    "laboratorio": "Genérico",
    "concentracion": "50 mg",
    "presentacion": "Caja x 1",
    "category": "analgesicos",
    "priceUsd": 120.0,
    "costUsd": 78.0,
    "stock": 2,
    "barcode": "7590000000292",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000292.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Nimodipina 10 mg/50 ml",
    "genericName": "Nimodipina",
    "laboratorio": "Genérico",
    "concentracion": "10 mg/50 ml",
    "presentacion": "Caja x 1",
    "category": "analgesicos",
    "priceUsd": 35.0,
    "costUsd": 22.75,
    "stock": 2,
    "barcode": "7590000000293",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000293.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Norepinefrina 4 mg/4 ml",
    "genericName": "Norepinefrina",
    "laboratorio": "Genérico",
    "concentracion": "4 mg/4 ml",
    "presentacion": "Ampolla",
    "category": "analgesicos",
    "priceUsd": 20.0,
    "costUsd": 13.0,
    "stock": 3,
    "barcode": "7590000000294",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000294.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Metotrexato 50 mg/2 ml",
    "genericName": "Metotrexato",
    "laboratorio": "Genérico",
    "concentracion": "50 mg/2 ml",
    "presentacion": "Ampolla",
    "category": "analgesicos",
    "priceUsd": 20.0,
    "costUsd": 13.0,
    "stock": 1,
    "barcode": "7590000000295",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000295.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Milrinona 10 mg/10 ml",
    "genericName": "Milrinona",
    "laboratorio": "Genérico",
    "concentracion": "10 mg/10 ml",
    "presentacion": "Ampolla",
    "category": "analgesicos",
    "priceUsd": 180.0,
    "costUsd": 117.0,
    "stock": 1,
    "barcode": "7590000000296",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000296.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Clexane 80 mg",
    "genericName": "Enoxaparina Sódica",
    "laboratorio": "Sanofi",
    "concentracion": "80 mg",
    "presentacion": "Jeringa",
    "category": "analgesicos",
    "priceUsd": 35.0,
    "costUsd": 22.75,
    "stock": 1,
    "barcode": "7590000000297",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000297.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Clexane 60 mg",
    "genericName": "Enoxaparina Sódica",
    "laboratorio": "Sanofi",
    "concentracion": "60 mg",
    "presentacion": "Jeringa",
    "category": "analgesicos",
    "priceUsd": 35.0,
    "costUsd": 22.75,
    "stock": 2,
    "barcode": "7590000000298",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000298.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Clexane 40 mg",
    "genericName": "Enoxaparina Sódica",
    "laboratorio": "Sanofi",
    "concentracion": "40 mg",
    "presentacion": "Jeringa",
    "category": "analgesicos",
    "priceUsd": 35.0,
    "costUsd": 22.75,
    "stock": 3,
    "barcode": "7590000000299",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000299.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Lantus 100 U/ml",
    "genericName": "Insulina Glargina",
    "laboratorio": "Sanofi",
    "concentracion": "100 U/ml",
    "presentacion": "Vial",
    "category": "analgesicos",
    "priceUsd": 45.0,
    "costUsd": 29.25,
    "stock": 2,
    "barcode": "7590000000300",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000300.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "NovoRapid 3 ml",
    "genericName": "Insulina Aspártica",
    "laboratorio": "Novo Nordisk",
    "concentracion": "3 ml",
    "presentacion": "Pluma",
    "category": "analgesicos",
    "priceUsd": 40.0,
    "costUsd": 26.0,
    "stock": 3,
    "barcode": "7590000000301",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000301.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Ultravist 300 mg I/ml",
    "genericName": "Iopromida",
    "laboratorio": "Bayer",
    "concentracion": "300 mg I/ml",
    "presentacion": "Frasco",
    "category": "analgesicos",
    "priceUsd": 120.0,
    "costUsd": 78.0,
    "stock": 1,
    "barcode": "7590000000302",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000302.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Suprahyal 25 mg/2.5 ml",
    "genericName": "Hialuronato Sódico",
    "laboratorio": "Suprahyal",
    "concentracion": "25 mg/2.5 ml",
    "presentacion": "Jeringa",
    "category": "analgesicos",
    "priceUsd": 80.0,
    "costUsd": 52.0,
    "stock": 1,
    "barcode": "7590000000303",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000303.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Colestime 150 mg",
    "genericName": "Colistimetato Sódico",
    "laboratorio": "Colestime",
    "concentracion": "150 mg",
    "presentacion": "Vial",
    "category": "analgesicos",
    "priceUsd": 65.0,
    "costUsd": 42.25,
    "stock": 2,
    "barcode": "7590000000304",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000304.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Antig Vial",
    "genericName": "Inmunoglobulina Liofilizada",
    "laboratorio": "Antig",
    "concentracion": "Vial",
    "presentacion": "Vial",
    "category": "analgesicos",
    "priceUsd": 70.0,
    "costUsd": 45.5,
    "stock": 1,
    "barcode": "7590000000305",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000305.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Betadine 1 L",
    "genericName": "Betadine",
    "laboratorio": "Betadine",
    "concentracion": "1 L",
    "presentacion": "Galón/Frasco",
    "category": "analgesicos",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 1,
    "barcode": "7590000000306",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000306.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Agua Destilada 1 L",
    "genericName": "Agua Destilada",
    "laboratorio": "Genérico",
    "concentracion": "1 L",
    "presentacion": "Frasco",
    "category": "analgesicos",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 5,
    "barcode": "7590000000307",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000307.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Agua Oxigenada 1 L",
    "genericName": "Agua Oxigenada",
    "laboratorio": "Genérico",
    "concentracion": "1 L",
    "presentacion": "Frasco",
    "category": "analgesicos",
    "priceUsd": 9.0,
    "costUsd": 5.85,
    "stock": 1,
    "barcode": "7590000000308",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000308.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Alcohol Absoluto/Isopropílico 1 L",
    "genericName": "Alcohol Absoluto/Isopropílico",
    "laboratorio": "Genérico",
    "concentracion": "1 L",
    "presentacion": "Frasco",
    "category": "analgesicos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 1,
    "barcode": "7590000000309",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000309.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Cal Sodada",
    "genericName": "Cal Sodada",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Envase",
    "category": "analgesicos",
    "priceUsd": 25.0,
    "costUsd": 16.25,
    "stock": 1,
    "barcode": "7590000000310",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000310.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Solución Salina 0.45%",
    "genericName": "Solución Salina 0.45%",
    "laboratorio": "Genérico",
    "concentracion": "0.45%",
    "presentacion": "Bolsa 500ml",
    "category": "analgesicos",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 3,
    "barcode": "7590000000311",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000311.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Dextro-Sal 5% - 0.30%",
    "genericName": "Dextro-Sal 5% - 0.30%",
    "laboratorio": "Genérico",
    "concentracion": "5% - 0.30%",
    "presentacion": "Bolsa 500ml",
    "category": "analgesicos",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 2,
    "barcode": "7590000000312",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000312.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Dextrosa 5% - Solución 0.9% 5% - 0.9%",
    "genericName": "Dextrosa 5% - Solución 0.9%",
    "laboratorio": "Genérico",
    "concentracion": "5% - 0.9%",
    "presentacion": "Bolsa 500ml",
    "category": "analgesicos",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 6,
    "barcode": "7590000000313",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000313.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Dextro-Sal 5% - 0.45%",
    "genericName": "Dextro-Sal 5% - 0.45%",
    "laboratorio": "Genérico",
    "concentracion": "5% - 0.45%",
    "presentacion": "Bolsa 500ml",
    "category": "analgesicos",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 2,
    "barcode": "7590000000314",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000314.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Glucosa al 10%",
    "genericName": "Glucosa al 10%",
    "laboratorio": "Genérico",
    "concentracion": "10%",
    "presentacion": "Bolsa 500ml",
    "category": "analgesicos",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 7,
    "barcode": "7590000000315",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000315.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Dextrosal 5%",
    "genericName": "Dextrosal 5%",
    "laboratorio": "Genérico",
    "concentracion": "5%",
    "presentacion": "Bolsa 500ml",
    "category": "analgesicos",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 7,
    "barcode": "7590000000316",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000316.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Dextrosal 10%",
    "genericName": "Dextrosal 10%",
    "laboratorio": "Genérico",
    "concentracion": "10%",
    "presentacion": "Bolsa 500ml",
    "category": "analgesicos",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 6,
    "barcode": "7590000000317",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000317.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Aminoácidos al 8.5%",
    "genericName": "Aminoácidos al 8.5%",
    "laboratorio": "Genérico",
    "concentracion": "8.5%",
    "presentacion": "Bolsa 500ml",
    "category": "analgesicos",
    "priceUsd": 75.0,
    "costUsd": 48.75,
    "stock": 1,
    "barcode": "7590000000318",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000318.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Dextrosa al 30%",
    "genericName": "Dextrosa al 30%",
    "laboratorio": "Genérico",
    "concentracion": "30%",
    "presentacion": "Bolsa 500ml",
    "category": "analgesicos",
    "priceUsd": 30.0,
    "costUsd": 19.5,
    "stock": 1,
    "barcode": "7590000000319",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000319.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Manitol al 18%",
    "genericName": "Manitol al 18%",
    "laboratorio": "Genérico",
    "concentracion": "18%",
    "presentacion": "Bolsa 500ml",
    "category": "analgesicos",
    "priceUsd": 25.0,
    "costUsd": 16.25,
    "stock": 1,
    "barcode": "7590000000320",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000320.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
];
