// Lote 2: insumos, dudosos y resto del inventario físico C&Y 2025 (15/08/2026).
// Generado automáticamente desde la transcripción del inventario manuscrito.
// Incluye: 169 insumos/otros no cubiertos en el lote 1 + 102 filas dudosas.
// Precios en Bs convertidos a USD (tasa ~850). Filas sin precio legible quedan en $0.
export const SEED_PRODUCTS_INV03 = [
  {
    "name": "manguera Hudson RCI",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 200.0,
    "costUsd": 130.0,
    "stock": 1,
    "barcode": "7590000001587",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Aguja Espinal #16-22-23",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 3.5,
    "costUsd": 2.27,
    "stock": 0,
    "barcode": "7590000001588",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Aguja Trukunt #14",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 65.0,
    "costUsd": 42.25,
    "stock": 1,
    "barcode": "7590000001589",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Aguja Trukunt #16",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 65.0,
    "costUsd": 42.25,
    "stock": 1,
    "barcode": "7590000001590",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Aguja Trukunt #18",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 65.0,
    "costUsd": 42.25,
    "stock": 1,
    "barcode": "7590000001591",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Agujas Odontologicas",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 8,
    "barcode": "7590000001592",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Alcohol 1L",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 1,
    "barcode": "7590000001593",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Alcohol 70% 240ml",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 12,
    "barcode": "7590000001594",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Alcohol 70% 500ml",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 3,
    "barcode": "7590000001595",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Alcohol 70% 950ml",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 4,
    "barcode": "7590000001596",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Alcohol 96% 240ml",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 5,
    "barcode": "7590000001597",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Alcohol 96% 500ml",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 1,
    "barcode": "7590000001598",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Algodon 25gr",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 2.5,
    "costUsd": 1.62,
    "stock": 5,
    "barcode": "7590000001599",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Algodon 50gr",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 3.5,
    "costUsd": 2.27,
    "stock": 2,
    "barcode": "7590000001600",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Algodon Alve 50gr",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 1,
    "barcode": "7590000001601",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Algodón 50gr",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 1,
    "barcode": "7590000001602",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Aplacal blister x4",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 3.5,
    "costUsd": 2.27,
    "stock": 3,
    "barcode": "7590000001603",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Aposito de Alginato de plata 10x20cm Dynamed",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 1,
    "barcode": "7590000001604",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Bata cirujano",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 20,
    "barcode": "7590000001605",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Bata de Paciente",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 2,
    "barcode": "7590000001606",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Bolsa Recolectora Orina 2000 litros",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 2.5,
    "costUsd": 1.62,
    "stock": 22,
    "barcode": "7590000001607",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Bolsa de Nutrición Entera",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 50.0,
    "costUsd": 32.5,
    "stock": 1,
    "barcode": "7590000001608",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Bolsa de Nutrición de 3000ml",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 50.0,
    "costUsd": 32.5,
    "stock": 1,
    "barcode": "7590000001609",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Bolsa de Orina Cystoflo-Med 2000ml",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 4,
    "barcode": "7590000001610",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Bolsa de Sangre cuadruple CPDA-1 450ml",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 25.0,
    "costUsd": 16.25,
    "stock": 1,
    "barcode": "7590000001611",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Bolsa de Sangre triple CPDA-1 Para recolección 450ml",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 25.0,
    "costUsd": 16.25,
    "stock": 1,
    "barcode": "7590000001612",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Bolsa de colostomia 4Base",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 2,
    "barcode": "7590000001613",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Bolsa sola de colostomia",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 6,
    "barcode": "7590000001614",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Bolsas Negras grandes",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 1.5,
    "costUsd": 0.98,
    "stock": 0,
    "barcode": "7590000001615",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Budesonida",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 0,
    "barcode": "7590000001616",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Campo Cerrado Esteril 40g",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 2.5,
    "costUsd": 1.62,
    "stock": 5,
    "barcode": "7590000001617",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Campo abierto Esteril oftalmologico",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 2.5,
    "costUsd": 1.62,
    "stock": 4,
    "barcode": "7590000001618",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Canula Basal Bigote",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 1,
    "barcode": "7590000001619",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Canula Yankauer 01 3.6 metros",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 0,
    "barcode": "7590000001620",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Canula de Mayo 90mm",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 5,
    "barcode": "7590000001621",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Canula de Mayo Naranja",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 4,
    "barcode": "7590000001622",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Canula de Mayo N°1",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 3,
    "barcode": "7590000001623",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Canula de Pipillo 3.0mm",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 40.0,
    "costUsd": 26.0,
    "stock": 1,
    "barcode": "7590000001624",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Cateter Umbilical 3.5",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 17,
    "barcode": "7590000001625",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Cateter Umbilical 5.0",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 16,
    "barcode": "7590000001626",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Cateter de Alimentación #5",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 0,
    "barcode": "7590000001627",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Cateter de Alimentación #8",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 9,
    "barcode": "7590000001628",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Cateter de Anestesia Epidural (Kit 16.G x 80mm)",
    "genericName": "",
    "laboratorio": "Kit 16.G x 80mm",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 20.0,
    "costUsd": 13.0,
    "stock": 1,
    "barcode": "7590000001629",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Cera Dental",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 2,
    "barcode": "7590000001630",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Cera Dental (Para Breques)",
    "genericName": "",
    "laboratorio": "Para Breques",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 7.0,
    "costUsd": 4.55,
    "stock": 2,
    "barcode": "7590000001631",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Cera de hueso (01 unidades) Cura wax",
    "genericName": "",
    "laboratorio": "01 unidades",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 1,
    "barcode": "7590000001632",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Cera de hueso (02 unidad) Bone wa",
    "genericName": "",
    "laboratorio": "02 unidad",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 2,
    "barcode": "7590000001633",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Cera de hueso (02 unidad) Trumax",
    "genericName": "",
    "laboratorio": "02 unidad",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 2,
    "barcode": "7590000001634",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Foley #16 silicón 2 vías",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 2,
    "barcode": "7590000001635",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Foley #16 silicón 3 vías",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 2,
    "barcode": "7590000001636",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Foley #20 silicón 2 vías",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 3,
    "barcode": "7590000001637",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Foley #20 silicón 3 vías",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 4,
    "barcode": "7590000001638",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Foley 2 vias silicon #12",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 3,
    "barcode": "7590000001639",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Foley 2 vias silicon #14",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 2,
    "barcode": "7590000001640",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Foley latex #10 2 vías",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 3,
    "barcode": "7590000001641",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Foley latex #12",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 5,
    "barcode": "7590000001642",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Foley latex #14",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 7,
    "barcode": "7590000001643",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Foley latex #16",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 10,
    "barcode": "7590000001644",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Foley latex #18",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 8,
    "barcode": "7590000001645",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Foley latex #20",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 5,
    "barcode": "7590000001646",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Foley latex #24",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 7,
    "barcode": "7590000001647",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Foley silicon #18",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 10,
    "barcode": "7590000001648",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Foley silicon #22 (2 vias)",
    "genericName": "",
    "laboratorio": "2 vias",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 3,
    "barcode": "7590000001649",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Foley silicon #24 2 vias",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 3,
    "barcode": "7590000001650",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Foley silicon #24 3 vias",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 5,
    "barcode": "7590000001651",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Foley silicon #6",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 3,
    "barcode": "7590000001652",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Foley silicon 3 vías #22",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 4,
    "barcode": "7590000001653",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Foley silicón #10 2 vías",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 4,
    "barcode": "7590000001654",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Foley silicón #18 2 vías",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 4,
    "barcode": "7590000001655",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Foley silicón #18 3 vías",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 2,
    "barcode": "7590000001656",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Gasa Oraologica",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Paquete",
    "category": "insumos",
    "priceUsd": 9.0,
    "costUsd": 5.85,
    "stock": 1,
    "barcode": "7590000001657",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Gasa Parafinada Esteril 10x10cm",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 0,
    "barcode": "7590000001658",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Gasa Parafinada con Acetato de clorhexidin 10x10cm",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 4,
    "barcode": "7590000001659",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Gasa Parafinada con Neomicina 10x10cm",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 9,
    "barcode": "7590000001660",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Gasa de Parafina para Quemaduras 10x10cm",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 0,
    "barcode": "7590000001661",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Gasa por Rollo (yarda)",
    "genericName": "",
    "laboratorio": "yarda",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 35.0,
    "costUsd": 22.75,
    "stock": 1,
    "barcode": "7590000001662",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Gasas",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 0.5,
    "costUsd": 0.33,
    "stock": 0,
    "barcode": "7590000001663",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Guantes Esteriles (7)(6.5)(8)",
    "genericName": "",
    "laboratorio": "7",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 1.5,
    "costUsd": 0.98,
    "stock": 0,
    "barcode": "7590000001664",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Hojilla de Bisturi en acero al carbono",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 0.5,
    "costUsd": 0.33,
    "stock": 10,
    "barcode": "7590000001665",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Hojillas de Bisturi #11",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 0.5,
    "costUsd": 0.33,
    "stock": 6,
    "barcode": "7590000001666",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Hojillas de Bisturi #20",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 0.5,
    "costUsd": 0.33,
    "stock": 15,
    "barcode": "7590000001667",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Ioban Tm2 350cm x 35cm",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 50.0,
    "costUsd": 32.5,
    "stock": 1,
    "barcode": "7590000001668",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Ioban Tm2 60cm x 45cm",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 55.0,
    "costUsd": 35.75,
    "stock": 1,
    "barcode": "7590000001669",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Jelco #14",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 2.5,
    "costUsd": 1.62,
    "stock": 8,
    "barcode": "7590000001670",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Jelco #16",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 3.5,
    "costUsd": 2.27,
    "stock": 9,
    "barcode": "7590000001671",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Jelco #18",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 2.5,
    "costUsd": 1.62,
    "stock": 29,
    "barcode": "7590000001672",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Jelco #20",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 2.5,
    "costUsd": 1.62,
    "stock": 9,
    "barcode": "7590000001673",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Jelco #22",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 2.5,
    "costUsd": 1.62,
    "stock": 15,
    "barcode": "7590000001674",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Jelco #24",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 2.5,
    "costUsd": 1.62,
    "stock": 14,
    "barcode": "7590000001675",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Jeringa 1cc",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 200.0,
    "costUsd": 130.0,
    "stock": 0,
    "barcode": "7590000001676",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Jeringa 20cc",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 0.53,
    "costUsd": 0.34,
    "stock": 0,
    "barcode": "7590000001677",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Jeringa 3cc, 5cc, 10cc",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 0.35,
    "costUsd": 0.23,
    "stock": 0,
    "barcode": "7590000001678",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Jeringa de irrigación Bulbo asepto 60ml",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 1,
    "barcode": "7590000001679",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Jeringa tomy 60cc",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 0,
    "barcode": "7590000001680",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Kit cateter vía venoso central Triple Lumen - Fr5 x 8cm",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 60.0,
    "costUsd": 39.0,
    "stock": 0,
    "barcode": "7590000001681",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Kit cateter vía venoso central Triple Lumen Fr7 x 20 cm",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 60.0,
    "costUsd": 39.0,
    "stock": 1,
    "barcode": "7590000001682",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Kit de sutura",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 60.0,
    "costUsd": 39.0,
    "stock": 1,
    "barcode": "7590000001683",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Lanceran 30ml (Gotas)",
    "genericName": "",
    "laboratorio": "Gotas",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 5,
    "barcode": "7590000001684",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Levin cateter #10",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 2.5,
    "costUsd": 1.62,
    "stock": 2,
    "barcode": "7590000001685",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Levin cateter #12",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 2.5,
    "costUsd": 1.62,
    "stock": 8,
    "barcode": "7590000001686",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Levin cateter #14",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 2.5,
    "costUsd": 1.62,
    "stock": 1,
    "barcode": "7590000001687",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Levin cateter #18",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 2.5,
    "costUsd": 1.62,
    "stock": 4,
    "barcode": "7590000001688",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Levin cateter #8",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 2.5,
    "costUsd": 1.62,
    "stock": 3,
    "barcode": "7590000001689",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Malla Quirurgica",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 50.0,
    "costUsd": 32.5,
    "stock": 1,
    "barcode": "7590000001690",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Malla quirurgica de monofilamento de polipropileno 10 x 10",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 25.0,
    "costUsd": 16.25,
    "stock": 1,
    "barcode": "7590000001691",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Mascarilla (Oxigeno adulto)",
    "genericName": "",
    "laboratorio": "Oxigeno adulto",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 0,
    "barcode": "7590000001692",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Mascarilla (Oxigeno pediatrico)",
    "genericName": "",
    "laboratorio": "Oxigeno pediatrico",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 8,
    "barcode": "7590000001693",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Mascarilla Adulto Nebulizar",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 0,
    "barcode": "7590000001694",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Mascarilla de O2 Venturi",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 5,
    "barcode": "7590000001695",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Mascarilla de Reservorio",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 0,
    "barcode": "7590000001696",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Mascarilla de Traqueostomia con Correa elastica",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 2,
    "barcode": "7590000001697",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Nelatón #10",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 6,
    "barcode": "7590000001698",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Nelatón #12",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 15,
    "barcode": "7590000001699",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Nelatón #14",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 7,
    "barcode": "7590000001700",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Nelatón #16",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 14,
    "barcode": "7590000001701",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Nelatón #18",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 5,
    "barcode": "7590000001702",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Nelatón #20",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 7,
    "barcode": "7590000001703",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Nelatón #8",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 12,
    "barcode": "7590000001704",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Placa de electrocauterio monopolar Pediatrico Dynamics",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 0,
    "barcode": "7590000001705",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Placa de electrocauterio monopolar adulto Dynamics",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 0,
    "barcode": "7590000001706",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Placa para electrocauterio",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 1,
    "barcode": "7590000001707",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Scalp #25",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 0.5,
    "costUsd": 0.33,
    "stock": 51,
    "barcode": "7590000001708",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Seda c/aguja",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 0,
    "barcode": "7590000001709",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Sistema Drenaje de Heridas - Tipo Blake",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 55.0,
    "costUsd": 35.75,
    "stock": 2,
    "barcode": "7590000001710",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Sonda de Succión #05",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 3,
    "barcode": "7590000001711",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Sonda de Succión #08",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 19,
    "barcode": "7590000001712",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Sonda de Succión #10",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 2,
    "barcode": "7590000001713",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Sonda de Succión #12",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 4,
    "barcode": "7590000001714",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Sonda de Succión #14",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 0,
    "barcode": "7590000001715",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Sonda de Succión #16",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 4,
    "barcode": "7590000001716",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Sonda de Succión #18",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 2,
    "barcode": "7590000001717",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Sonda de Succión #20",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 3,
    "barcode": "7590000001718",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Sonda de alimentación (8)",
    "genericName": "",
    "laboratorio": "8",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 0,
    "barcode": "7590000001719",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Sutura Acrobib",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 50.0,
    "costUsd": 32.5,
    "stock": 1,
    "barcode": "7590000001720",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Tijeras saca grapas",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 2,
    "barcode": "7590000001721",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Traqueotomo #3.5 mm",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 1,
    "barcode": "7590000001722",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Traqueotomo #3.5 mm",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 1,
    "barcode": "7590000001723",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Traqueotomo #4.0mm",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 1,
    "barcode": "7590000001724",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Traqueotomo #5.5mm",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 2,
    "barcode": "7590000001725",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Traqueotomo #6.0 mm",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 1,
    "barcode": "7590000001726",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Traqueotomo #7.5mm",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 1,
    "barcode": "7590000001727",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Traqueotomo #8.0 mm",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 1,
    "barcode": "7590000001728",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Traqueotomo #8.5 mm",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 1,
    "barcode": "7590000001729",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Trocal 24fg 8M (cateter)",
    "genericName": "",
    "laboratorio": "cateter",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 25.0,
    "costUsd": 16.25,
    "stock": 1,
    "barcode": "7590000001730",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Tubo Endotraqueal #3.0mm",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 8,
    "barcode": "7590000001731",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Tubo Endotraqueal #3.5mm",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 9,
    "barcode": "7590000001732",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Tubo Endotraqueal #4.0",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 10,
    "barcode": "7590000001733",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Tubo Endotraqueal #5.5mm",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 2,
    "barcode": "7590000001734",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Tubo Endotraqueal #6.0",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 4,
    "barcode": "7590000001735",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Tubo Endotraqueal #7.0",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 3,
    "barcode": "7590000001736",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Tubo Endotraqueal #7.5",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 3,
    "barcode": "7590000001737",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Tubo Endotraqueal #8.0",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 1,
    "barcode": "7590000001738",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Tubo Endotraqueal #8.5",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 1,
    "barcode": "7590000001739",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Tubo Penrose 1/2",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 3,
    "barcode": "7590000001740",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Tubo Penrose 1/4",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 4,
    "barcode": "7590000001741",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Tubo de extensión K-50",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 9,
    "barcode": "7590000001742",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Tubos azules",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 0.59,
    "costUsd": 0.38,
    "stock": 59,
    "barcode": "7590000001743",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Tubos morados",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 0.59,
    "costUsd": 0.38,
    "stock": 60,
    "barcode": "7590000001744",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Tubos rojos",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 0.59,
    "costUsd": 0.38,
    "stock": 83,
    "barcode": "7590000001745",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Venda Elastica ajustable max 20cmx4m",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 6,
    "barcode": "7590000001746",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Venda Especial 4.0 20cm/4mts",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 5,
    "barcode": "7590000001747",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Venda Especial 40 15cm 4metros",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 9,
    "barcode": "7590000001748",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Venda de Gasa para heridas / Quemadas",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 9,
    "barcode": "7590000001749",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Venda especial 4 90cm",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 5,
    "barcode": "7590000001750",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Vendas Coban med 10 x4cm",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 12,
    "barcode": "7590000001751",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Vendas Coban med 2.5x4cm",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 5,
    "barcode": "7590000001752",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Vendas Coban med 5cmx4cm",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 10,
    "barcode": "7590000001753",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Vendas Coban med 7.5cm x4cm",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 3,
    "barcode": "7590000001754",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "YanKawer o Canulas 3 metros",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 0,
    "barcode": "7590000001755",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "CanbanPindoxingdoxilamina 10mg",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Caja",
    "category": "medicamentos",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 2,
    "barcode": "7590000001756",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Celecoxib 200mg (KidsGomitas)",
    "genericName": "",
    "laboratorio": "KidsGomitas",
    "concentracion": "",
    "presentacion": "Blister",
    "category": "medicamentos",
    "priceUsd": 7.0,
    "costUsd": 4.55,
    "stock": 4,
    "barcode": "7590000001757",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Fulgram amoxicilina + acido clavulanico 875mg 125mg",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Caja",
    "category": "medicamentos",
    "priceUsd": 25.0,
    "costUsd": 16.25,
    "stock": 1,
    "barcode": "7590000001758",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Nefrotal 100mg (losartan)",
    "genericName": "",
    "laboratorio": "losartan",
    "concentracion": "",
    "presentacion": "Blister",
    "category": "medicamentos",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 2,
    "barcode": "7590000001759",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Itucolal 600mg",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Caja",
    "category": "medicamentos",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 4,
    "barcode": "7590000001760",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Eusilen Dual (Ibuprofeno 600mg)",
    "genericName": "",
    "laboratorio": "Ibuprofeno 600mg",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 0,
    "barcode": "7590000001761",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Ulcon 1g (Sucralfato)",
    "genericName": "",
    "laboratorio": "Sucralfato",
    "concentracion": "",
    "presentacion": "Caja",
    "category": "medicamentos",
    "priceUsd": 20.0,
    "costUsd": 13.0,
    "stock": 1,
    "barcode": "7590000001762",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Botiquin Primeros auxilios",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "cuidado_personal",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 0,
    "barcode": "7590000001763",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Algodon 10gr",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 2,
    "barcode": "7590000001764",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Desodorante Speed Stick 30g",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "cuidado_personal",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 1,
    "barcode": "7590000001765",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Toallas humeda grandes OKY x42",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "cuidado_personal",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 2,
    "barcode": "7590000001766",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Vasopresina",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 1,
    "barcode": "7590000001767",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Efadro bisturi",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 0,
    "barcode": "7590000001768",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Cromico (0)(1)(2.0)(3.0)",
    "genericName": "",
    "laboratorio": "0",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 0,
    "barcode": "7590000001769",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Nylon (2-0)(3-0)",
    "genericName": "",
    "laboratorio": "2-0",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 0,
    "barcode": "7590000001770",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Lamina Porta objeto",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 1.0,
    "costUsd": 0.65,
    "stock": 22,
    "barcode": "7590000001771",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Baja lenguas (caja + 10 unidades)",
    "genericName": "",
    "laboratorio": "caja + 10 unidades",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 1.0,
    "costUsd": 0.65,
    "stock": 0,
    "barcode": "7590000001772",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Aguja hipodermica 25/50 octavo",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 1.0,
    "costUsd": 0.65,
    "stock": 0,
    "barcode": "7590000001773",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Aguja hipodermica 18G",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 1.0,
    "costUsd": 0.65,
    "stock": 0,
    "barcode": "7590000001774",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Hojilla de Bisturi #15",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 10,
    "barcode": "7590000001775",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Amptrypan",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 30.0,
    "costUsd": 19.5,
    "stock": 1,
    "barcode": "7590000001776",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Foley latex #22",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 35.0,
    "costUsd": 22.75,
    "stock": 8,
    "barcode": "7590000001777",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Electrodos 3x 1$",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 1.0,
    "costUsd": 0.65,
    "stock": 12,
    "barcode": "7590000001778",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Prolastat (5 tabletas) 0.5mg (4 x 30 b)",
    "genericName": "",
    "laboratorio": "5 tabletas",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 0,
    "barcode": "7590000001779",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Traceval 500mg x 5 tabletas (4 Blister)",
    "genericName": "",
    "laboratorio": "4 Blister",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 0,
    "barcode": "7590000001780",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Clonatrin clonazepam 2mg x 10 tableta",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Blister",
    "category": "medicamentos",
    "priceUsd": 25.0,
    "costUsd": 16.25,
    "stock": 2,
    "barcode": "7590000001781",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Canula de Mayo 9cm",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 5,
    "barcode": "7590000001782",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Tubo Endotraqueal #6.5",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 2,
    "barcode": "7590000001783",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Circuito Respiratorio Pediatrico",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 70.0,
    "costUsd": 45.5,
    "stock": 1,
    "barcode": "7590000001784",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Hudson RC7 40\"(101cm) Adulto",
    "genericName": "",
    "laboratorio": "101cm",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 2,
    "barcode": "7590000001785",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Guedel para via aerea PVC suave 50mm",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 4,
    "barcode": "7590000001786",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Deca Lentermina (3 ampollas)",
    "genericName": "",
    "laboratorio": "3 ampollas",
    "concentracion": "",
    "presentacion": "Caja",
    "category": "medicamentos",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 2,
    "barcode": "7590000001787",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Puntos de adhesivo",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 0,
    "barcode": "7590000001788",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Supositorio Glicerina",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 9,
    "barcode": "7590000001789",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Bata de Paciente",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 7,
    "barcode": "7590000001790",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Cateter via Central 5fr-80mm",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 50.0,
    "costUsd": 32.5,
    "stock": 1,
    "barcode": "7590000001791",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Cateter venoso Central triple Lumen 5fr 3 Lumen 5 pulgadas",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 60.0,
    "costUsd": 39.0,
    "stock": 18,
    "barcode": "7590000001792",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Alambre Kischner 8.1",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 22.0,
    "costUsd": 14.3,
    "stock": 4,
    "barcode": "7590000001793",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Bacteval",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Blister",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 3,
    "barcode": "7590000001794",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Benzoato de Bencilo 120ml Jarabe",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 13,
    "barcode": "7590000001795",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Cateter vía Central Trilumen 7Fr-20",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 60.0,
    "costUsd": 39.0,
    "stock": 0,
    "barcode": "7590000001796",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Montelukast - Desloratadina Grenfarma x10 tab (2)",
    "genericName": "",
    "laboratorio": "2",
    "concentracion": "",
    "presentacion": "Caja",
    "category": "medicamentos",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 3,
    "barcode": "7590000001797",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Metoprolol 50mg x10 tableta",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Blister",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 4,
    "barcode": "7590000001798",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Nifedipina 10mg x10 tabl",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 0,
    "barcode": "7590000001799",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Clindamicina x1 ovulo",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 9.0,
    "costUsd": 5.85,
    "stock": 9,
    "barcode": "7590000001800",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Corta uña de bebé",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 3.5,
    "costUsd": 2.27,
    "stock": 0,
    "barcode": "7590000001801",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Cardimar x 90 tableta",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 1.0,
    "costUsd": 0.65,
    "stock": 1,
    "barcode": "7590000001802",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Graberry & vitamina C x 30",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 20.0,
    "costUsd": 13.0,
    "stock": 1,
    "barcode": "7590000001803",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Opaflan (Diclofenac) 2mg/ml Vencido",
    "genericName": "",
    "laboratorio": "Diclofenac",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 0,
    "barcode": "7590000001804",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Fulgram 600mg - 42,9mg/5ml 60ml",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 22.0,
    "costUsd": 14.3,
    "stock": 0,
    "barcode": "7590000001805",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Clavumed (Amoxicilina + Acido Clavulanico) 250mg+125mg 60ml",
    "genericName": "",
    "laboratorio": "Amoxicilina + Acido Clavulanico",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 3,
    "barcode": "7590000001806",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Clavumed (Amoxicilina + Acido Clavulanico) 600mg/42,9mg 60ml",
    "genericName": "",
    "laboratorio": "Amoxicilina + Acido Clavulanico",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 3,
    "barcode": "7590000001807",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Neutrox (antiacido) vencido",
    "genericName": "",
    "laboratorio": "antiacido",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 0,
    "barcode": "7590000001808",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Curitas",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 100.0,
    "costUsd": 65.0,
    "stock": 94,
    "barcode": "7590000001809",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Tapa bocas",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "insumos",
    "priceUsd": 0.59,
    "costUsd": 0.38,
    "stock": 0,
    "barcode": "7590000001810",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Corta uñas",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 4,
    "barcode": "7590000001811",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Calzinc D vencido",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 0,
    "barcode": "7590000001812",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Pilas 3A energizer",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 5,
    "barcode": "7590000001813",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Dextro-Sal 5%-0,30%",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 2,
    "barcode": "7590000001814",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Cetirizina Blister x10",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 2,
    "barcode": "7590000001815",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Cromico 0",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 27,
    "barcode": "7590000001816",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Cromico 1",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 5,
    "barcode": "7590000001817",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Cromico 2-0 + 12 unidades en STOP",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 15,
    "barcode": "7590000001818",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Cromico 3-0",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 21,
    "barcode": "7590000001819",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Cromico 4-0",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 3,
    "barcode": "7590000001820",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Simple 0",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 9,
    "barcode": "7590000001821",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Simple 1",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 4,
    "barcode": "7590000001822",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Simple 2-0",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 4,
    "barcode": "7590000001823",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Simple 3-0",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 6,
    "barcode": "7590000001824",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Nylon 2-0 AR",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 34,
    "barcode": "7590000001825",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Nylon 2-0 AC",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 12,
    "barcode": "7590000001826",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Nylon 3-0 AR",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 9,
    "barcode": "7590000001827",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Nylon 3-0 AC",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 12,
    "barcode": "7590000001828",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Nylon 4-0",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 6,
    "barcode": "7590000001829",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Nylon 5-0",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 3,
    "barcode": "7590000001830",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Nylon 6-0",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 10,
    "barcode": "7590000001831",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Nylon 10-0",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 3,
    "barcode": "7590000001832",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Nylon 4-0 Demetech",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 7,
    "barcode": "7590000001833",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Seda 1",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 21,
    "barcode": "7590000001834",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Seda 2-0",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 10,
    "barcode": "7590000001835",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Seda 3-0",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 9,
    "barcode": "7590000001836",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Seda 0",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 4,
    "barcode": "7590000001837",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Seda trenzada 2-0",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 4,
    "barcode": "7590000001838",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Seda Trenzada 0",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 8,
    "barcode": "7590000001839",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Seda 4-0 13mm",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 8,
    "barcode": "7590000001840",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Sutupack 1",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 3,
    "barcode": "7590000001841",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Sutupack 0",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 12,
    "barcode": "7590000001842",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Vicryl 0",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 24,
    "barcode": "7590000001843",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Vicryl 1",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 2,
    "barcode": "7590000001844",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Vicryl 2-0",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 35,
    "barcode": "7590000001845",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Vicryl 3-0",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 14,
    "barcode": "7590000001846",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Vicryl 4-0",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 15,
    "barcode": "7590000001847",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Prolene 0",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 25,
    "barcode": "7590000001848",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Prolene 1",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 20,
    "barcode": "7590000001849",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Prolene 2-0",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 38,
    "barcode": "7590000001850",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Prolene 3-0 AC",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 20,
    "barcode": "7590000001851",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Prolene 3-0 AR",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 12,
    "barcode": "7590000001852",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Prolene 5-0",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 12,
    "barcode": "7590000001853",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Prolene 6-0",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 6,
    "barcode": "7590000001854",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Prolene 4-0",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 8,
    "barcode": "7590000001855",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Monofyl 3-0",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 3,
    "barcode": "7590000001856",
    "requiresPrescription": false,
    "isControlled": false,
  },
  {
    "name": "Polidioxanona 5-0",
    "genericName": "",
    "laboratorio": "",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "medicamentos",
    "priceUsd": 0.0,
    "costUsd": 0.0,
    "stock": 12,
    "barcode": "7590000001857",
    "requiresPrescription": false,
    "isControlled": false,
  },
];