// Seed products 361-400 (auto-generated split)
export const SEED_PRODUCTS_10 = [
  {
    "name": "Sábila + Linaza x 60 tab",
    "genericName": "Sábila + Linaza",
    "laboratorio": "Genérico",
    "concentracion": "x 60 tab",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 1,
    "barcode": "7590000000361",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000361.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
  {
    "name": "Cardo Lechoso / Silimarina x 60 tab",
    "genericName": "Cardo Lechoso / Silimarina",
    "laboratorio": "Genérico",
    "concentracion": "x 60 tab",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 1,
    "barcode": "7590000000362",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000362.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
  {
    "name": "Carbón Activado x 60 tab",
    "genericName": "Carbón Activado",
    "laboratorio": "Genérico",
    "concentracion": "x 60 tab",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 30.0,
    "costUsd": 19.5,
    "stock": 2,
    "barcode": "7590000000363",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000363.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
  {
    "name": "Saw Palmetto x 60 tab",
    "genericName": "Saw Palmetto",
    "laboratorio": "Genérico",
    "concentracion": "x 60 tab",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 1,
    "barcode": "7590000000364",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000364.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
  {
    "name": "Vitaminas Prenatal x 60 tab",
    "genericName": "Vitaminas Prenatal",
    "laboratorio": "Genérico",
    "concentracion": "x 60 tab",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 20.0,
    "costUsd": 13.0,
    "stock": 1,
    "barcode": "7590000000365",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000365.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
  {
    "name": "Zinc 25 mg x 30 tab",
    "genericName": "Zinc",
    "laboratorio": "Genérico",
    "concentracion": "25 mg x 30 tab",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 1,
    "barcode": "7590000000366",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000366.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
  {
    "name": "Vitamina C Gomitas x 60 gomas",
    "genericName": "Vitamina C Gomitas",
    "laboratorio": "Genérico",
    "concentracion": "x 60 gomas",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 14.0,
    "costUsd": 9.1,
    "stock": 1,
    "barcode": "7590000000367",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000367.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
  {
    "name": "Letisan 1000 mg x 30 tab",
    "genericName": "Vitamina C",
    "laboratorio": "Letisan",
    "concentracion": "1000 mg x 30 tab",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 1,
    "barcode": "7590000000368",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000368.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
  {
    "name": "Vitamina + Zinc x 30 tab",
    "genericName": "Vitamina + Zinc",
    "laboratorio": "Genérico",
    "concentracion": "x 30 tab",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 1,
    "barcode": "7590000000369",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000369.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
  {
    "name": "Castaño de Indias x 60 tab",
    "genericName": "Castaño de Indias",
    "laboratorio": "Genérico",
    "concentracion": "x 60 tab",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 3,
    "barcode": "7590000000370",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000370.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
  {
    "name": "L-Arginina x 100 tab",
    "genericName": "L-Arginina",
    "laboratorio": "Genérico",
    "concentracion": "x 100 tab",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 30.0,
    "costUsd": 19.5,
    "stock": 1,
    "barcode": "7590000000371",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000371.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
  {
    "name": "L-Carnitina x 30 tab",
    "genericName": "L-Carnitina",
    "laboratorio": "Genérico",
    "concentracion": "x 30 tab",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 1,
    "barcode": "7590000000372",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000372.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
  {
    "name": "Melatonina 3 mg x 60 tab",
    "genericName": "Melatonina",
    "laboratorio": "Genérico",
    "concentracion": "3 mg x 60 tab",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 20.0,
    "costUsd": 13.0,
    "stock": 1,
    "barcode": "7590000000373",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000373.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
  {
    "name": "Met VB6 5 mg x 30 tab",
    "genericName": "Vitamina B6",
    "laboratorio": "Met VB6",
    "concentracion": "5 mg x 30 tab",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 2,
    "barcode": "7590000000374",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000374.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
  {
    "name": "Melatonina Plus x 60 tab",
    "genericName": "Melatonina Plus",
    "laboratorio": "Genérico",
    "concentracion": "x 60 tab",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 1,
    "barcode": "7590000000375",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000375.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
  {
    "name": "Varisan 300 mg x 60 tab",
    "genericName": "Varisan",
    "laboratorio": "Varisan",
    "concentracion": "300 mg x 60 tab",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 1,
    "barcode": "7590000000376",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000376.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
  {
    "name": "Omega 3 x 60 tab",
    "genericName": "Omega 3",
    "laboratorio": "Genérico",
    "concentracion": "x 60 tab",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 20.0,
    "costUsd": 13.0,
    "stock": 1,
    "barcode": "7590000000377",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000377.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
  {
    "name": "Glucosamina 2865 mg x 90 tab",
    "genericName": "Glucosamina",
    "laboratorio": "Genérico",
    "concentracion": "2865 mg x 90 tab",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 20.0,
    "costUsd": 13.0,
    "stock": 1,
    "barcode": "7590000000378",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000378.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
  {
    "name": "Inositol x 60 tab",
    "genericName": "Inositol",
    "laboratorio": "Genérico",
    "concentracion": "x 60 tab",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 28.0,
    "costUsd": 18.2,
    "stock": 1,
    "barcode": "7590000000379",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000379.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
  {
    "name": "Levadura de Cerveza x 60 tab",
    "genericName": "Levadura de Cerveza",
    "laboratorio": "Genérico",
    "concentracion": "x 60 tab",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 1,
    "barcode": "7590000000380",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000380.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
  {
    "name": "Ñame Salvaje (Wild Yam) 365 mg x 60 tab",
    "genericName": "Ñame Salvaje (Wild Yam)",
    "laboratorio": "Genérico",
    "concentracion": "365 mg x 60 tab",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 1,
    "barcode": "7590000000381",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000381.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
  {
    "name": "Ñame Salvaje (Wild Yam) 500 mg x 60 tab",
    "genericName": "Ñame Salvaje (Wild Yam)",
    "laboratorio": "Genérico",
    "concentracion": "500 mg x 60 tab",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 2,
    "barcode": "7590000000382",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000382.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
  {
    "name": "Cardimar x 90 tab",
    "genericName": "Cardimar (Silimarina)",
    "laboratorio": "Cardimar",
    "concentracion": "x 90 tab",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 1,
    "barcode": "7590000000383",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000383.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
  {
    "name": "Citrato de Magnesio x 60 tab",
    "genericName": "Citrato de Magnesio",
    "laboratorio": "Genérico",
    "concentracion": "x 60 tab",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 20.0,
    "costUsd": 13.0,
    "stock": 1,
    "barcode": "7590000000384",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000384.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
  {
    "name": "Magnevit x 30 tab",
    "genericName": "Magnevit",
    "laboratorio": "Magnevit",
    "concentracion": "x 30 tab",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 1,
    "barcode": "7590000000385",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000385.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
  {
    "name": "Stonex Plus x 30 tab",
    "genericName": "Citrato de Potasio",
    "laboratorio": "Stonex Plus",
    "concentracion": "x 30 tab",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 30.0,
    "costUsd": 19.5,
    "stock": 1,
    "barcode": "7590000000386",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000386.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
  {
    "name": "Cranberry + Vitamina C x 30 tab",
    "genericName": "Cranberry + Vitamina C",
    "laboratorio": "Genérico",
    "concentracion": "x 30 tab",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 20.0,
    "costUsd": 13.0,
    "stock": 1,
    "barcode": "7590000000387",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000387.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
  {
    "name": "Cranberry x 60 tab",
    "genericName": "Cranberry",
    "laboratorio": "Genérico",
    "concentracion": "x 60 tab",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 1,
    "barcode": "7590000000388",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000388.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
  {
    "name": "Centrunex x 60 tab",
    "genericName": "Centrunex",
    "laboratorio": "Centrunex",
    "concentracion": "x 60 tab",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 1,
    "barcode": "7590000000389",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000389.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
  {
    "name": "Centella Asiática x 30 cap",
    "genericName": "Centella Asiática",
    "laboratorio": "Genérico",
    "concentracion": "x 30 cap",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 3,
    "barcode": "7590000000390",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000390.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
  {
    "name": "Centella Asiática x 10 tab",
    "genericName": "Centella Asiática",
    "laboratorio": "Genérico",
    "concentracion": "x 10 tab",
    "presentacion": "Blister",
    "category": "vitaminas",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 2,
    "barcode": "7590000000391",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000391.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
  {
    "name": "Colágeno Hidrolizado x 30 cap",
    "genericName": "Colágeno Hidrolizado",
    "laboratorio": "Genérico",
    "concentracion": "x 30 cap",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 2,
    "barcode": "7590000000392",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000392.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
  {
    "name": "Ginkgo Biloba x 60 cap",
    "genericName": "Ginkgo Biloba",
    "laboratorio": "Genérico",
    "concentracion": "x 60 cap",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 1,
    "barcode": "7590000000393",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000393.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
  {
    "name": "Chancapiedra x 70 cap",
    "genericName": "Chancapiedra",
    "laboratorio": "Genérico",
    "concentracion": "x 70 cap",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 1,
    "barcode": "7590000000394",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000394.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
  {
    "name": "Calcibon Natal x 30 cap",
    "genericName": "Calcio Citrato + Vitamina D3",
    "laboratorio": "Calcibon Natal",
    "concentracion": "x 30 cap",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 25.0,
    "costUsd": 16.25,
    "stock": 2,
    "barcode": "7590000000395",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000395.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
  {
    "name": "Calcibon D x 30 cap",
    "genericName": "Calcio Citrato + Vitamina D3",
    "laboratorio": "Calcibon D",
    "concentracion": "x 30 cap",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 25.0,
    "costUsd": 16.25,
    "stock": 1,
    "barcode": "7590000000396",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000396.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
  {
    "name": "Calostro Bovino x 60 cap",
    "genericName": "Calostro Bovino",
    "laboratorio": "Genérico",
    "concentracion": "x 60 cap",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 35.0,
    "costUsd": 22.75,
    "stock": 2,
    "barcode": "7590000000397",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000397.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
  {
    "name": "Calcifor x 30 cap",
    "genericName": "Calcifor",
    "laboratorio": "Calcifor",
    "concentracion": "x 30 cap",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 1,
    "barcode": "7590000000398",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000398.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
  {
    "name": "Citrato de Calcio x 18 cap",
    "genericName": "Citrato de Calcio",
    "laboratorio": "Genérico",
    "concentracion": "x 18 cap",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 1,
    "barcode": "7590000000399",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000399.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
  {
    "name": "Sanafito x 60 cap",
    "genericName": "Biotina",
    "laboratorio": "Sanafito",
    "concentracion": "x 60 cap",
    "presentacion": "Frasco",
    "category": "vitaminas",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 1,
    "barcode": "7590000000400",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000400.jpg",
    "originalCategory": "Naturistas y Suplementos"
  },
];
