// Seed products 241-280 (auto-generated split)
export const SEED_PRODUCTS_07 = [
  {
    "name": "Fin-Al-Grip Noche",
    "genericName": "Antigripal Noche",
    "laboratorio": "Fin-Al-Grip Noche",
    "concentracion": "",
    "presentacion": "Caja x 10",
    "category": "analgesicos",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 2,
    "barcode": "7590000000241",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000241.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Alivet Noche",
    "genericName": "Antigripal Noche",
    "laboratorio": "Alivet Noche",
    "concentracion": "",
    "presentacion": "Sobre",
    "category": "analgesicos",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 5,
    "barcode": "7590000000242",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000242.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Alivet Día",
    "genericName": "Antigripal Día",
    "laboratorio": "Alivet Día",
    "concentracion": "",
    "presentacion": "Sobre",
    "category": "analgesicos",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 6,
    "barcode": "7590000000243",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000243.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Alivet",
    "genericName": "Antigripal",
    "laboratorio": "Alivet",
    "concentracion": "",
    "presentacion": "Caja x 4",
    "category": "analgesicos",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 2,
    "barcode": "7590000000244",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000244.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Teragrip",
    "genericName": "Antigripal",
    "laboratorio": "Teragrip",
    "concentracion": "",
    "presentacion": "Caja x 14",
    "category": "analgesicos",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 1,
    "barcode": "7590000000245",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000245.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Teragrip Noche",
    "genericName": "Antigripal Noche",
    "laboratorio": "Teragrip Noche",
    "concentracion": "",
    "presentacion": "Sobre",
    "category": "analgesicos",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 2,
    "barcode": "7590000000246",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000246.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Teragrip Día",
    "genericName": "Antigripal Día",
    "laboratorio": "Teragrip Día",
    "concentracion": "",
    "presentacion": "Sobre",
    "category": "analgesicos",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 4,
    "barcode": "7590000000247",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000247.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Clonatril 1 mg",
    "genericName": "Clonazepam",
    "laboratorio": "Clonatril",
    "concentracion": "1 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 6,
    "barcode": "7590000000248",
    "requiresPrescription": true,
    "isControlled": true,
    "image": "/products/7590000000248.jpg",
    "originalCategory": "Psicotrópicos y Controlados"
  },
  {
    "name": "Clonatril 2 mg",
    "genericName": "Clonazepam",
    "laboratorio": "Clonatril",
    "concentracion": "2 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 2,
    "barcode": "7590000000249",
    "requiresPrescription": true,
    "isControlled": true,
    "image": "/products/7590000000249.jpg",
    "originalCategory": "Psicotrópicos y Controlados"
  },
  {
    "name": "Clonzep 2 mg",
    "genericName": "Clonazepam",
    "laboratorio": "Clonzep",
    "concentracion": "2 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 1,
    "barcode": "7590000000250",
    "requiresPrescription": true,
    "isControlled": true,
    "image": "/products/7590000000250.jpg",
    "originalCategory": "Psicotrópicos y Controlados"
  },
  {
    "name": "Ansilan 2 mg",
    "genericName": "Alprazolam",
    "laboratorio": "Ansilan",
    "concentracion": "2 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 1,
    "barcode": "7590000000251",
    "requiresPrescription": true,
    "isControlled": true,
    "image": "/products/7590000000251.jpg",
    "originalCategory": "Psicotrópicos y Controlados"
  },
  {
    "name": "Alpram 1 mg",
    "genericName": "Alprazolam",
    "laboratorio": "Alpram",
    "concentracion": "1 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 1,
    "barcode": "7590000000252",
    "requiresPrescription": true,
    "isControlled": true,
    "image": "/products/7590000000252.jpg",
    "originalCategory": "Psicotrópicos y Controlados"
  },
  {
    "name": "Alpram 2 mg",
    "genericName": "Alprazolam",
    "laboratorio": "Alpram",
    "concentracion": "2 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 4,
    "barcode": "7590000000253",
    "requiresPrescription": true,
    "isControlled": true,
    "image": "/products/7590000000253.jpg",
    "originalCategory": "Psicotrópicos y Controlados"
  },
  {
    "name": "Alpram 0.5 mg",
    "genericName": "Alprazolam",
    "laboratorio": "Alpram",
    "concentracion": "0.5 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 5,
    "barcode": "7590000000254",
    "requiresPrescription": true,
    "isControlled": true,
    "image": "/products/7590000000254.jpg",
    "originalCategory": "Psicotrópicos y Controlados"
  },
  {
    "name": "Zolpidex 10 mg",
    "genericName": "Zolpidem",
    "laboratorio": "Zolpidex",
    "concentracion": "10 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 2,
    "barcode": "7590000000255",
    "requiresPrescription": true,
    "isControlled": true,
    "image": "/products/7590000000255.jpg",
    "originalCategory": "Psicotrópicos y Controlados"
  },
  {
    "name": "Gardenal",
    "genericName": "Fenobarbital",
    "laboratorio": "Gardenal",
    "concentracion": "",
    "presentacion": "Ampolla",
    "category": "analgesicos",
    "priceUsd": 45.0,
    "costUsd": 29.25,
    "stock": 2,
    "barcode": "7590000000256",
    "requiresPrescription": true,
    "isControlled": true,
    "image": "/products/7590000000256.jpg",
    "originalCategory": "Psicotrópicos y Controlados"
  },
  {
    "name": "Gardenal 100 mg",
    "genericName": "Fenobarbital",
    "laboratorio": "Gardenal",
    "concentracion": "100 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 2,
    "barcode": "7590000000257",
    "requiresPrescription": true,
    "isControlled": true,
    "image": "/products/7590000000257.jpg",
    "originalCategory": "Psicotrópicos y Controlados"
  },
  {
    "name": "Tramal 50 mg",
    "genericName": "Tramadol",
    "laboratorio": "Tramal",
    "concentracion": "50 mg",
    "presentacion": "Ampolla",
    "category": "analgesicos",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 4,
    "barcode": "7590000000258",
    "requiresPrescription": true,
    "isControlled": true,
    "image": "/products/7590000000258.jpg",
    "originalCategory": "Psicotrópicos y Controlados"
  },
  {
    "name": "Tramal 100 mg",
    "genericName": "Tramadol",
    "laboratorio": "Tramal",
    "concentracion": "100 mg",
    "presentacion": "Ampolla",
    "category": "analgesicos",
    "priceUsd": 20.0,
    "costUsd": 13.0,
    "stock": 7,
    "barcode": "7590000000259",
    "requiresPrescription": true,
    "isControlled": true,
    "image": "/products/7590000000259.jpg",
    "originalCategory": "Psicotrópicos y Controlados"
  },
  {
    "name": "Fentanilo",
    "genericName": "Fentanilo",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Ampolla",
    "category": "analgesicos",
    "priceUsd": 28.0,
    "costUsd": 18.2,
    "stock": 2,
    "barcode": "7590000000260",
    "requiresPrescription": true,
    "isControlled": true,
    "image": "/products/7590000000260.jpg",
    "originalCategory": "Psicotrópicos y Controlados"
  },
  {
    "name": "Morfina",
    "genericName": "Morfina",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Ampolla",
    "category": "analgesicos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 2,
    "barcode": "7590000000261",
    "requiresPrescription": true,
    "isControlled": true,
    "image": "/products/7590000000261.jpg",
    "originalCategory": "Psicotrópicos y Controlados"
  },
  {
    "name": "Diazepam",
    "genericName": "Diazepam",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Ampolla",
    "category": "analgesicos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 4,
    "barcode": "7590000000262",
    "requiresPrescription": true,
    "isControlled": true,
    "image": "/products/7590000000262.jpg",
    "originalCategory": "Psicotrópicos y Controlados"
  },
  {
    "name": "Midazolam",
    "genericName": "Midazolam",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Ampolla",
    "category": "analgesicos",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 2,
    "barcode": "7590000000263",
    "requiresPrescription": true,
    "isControlled": true,
    "image": "/products/7590000000263.jpg",
    "originalCategory": "Psicotrópicos y Controlados"
  },
  {
    "name": "Prolastat 0.5 mg",
    "genericName": "Cabergolina",
    "laboratorio": "Prolastat",
    "concentracion": "0.5 mg",
    "presentacion": "Tab x 5",
    "category": "analgesicos",
    "priceUsd": 30.0,
    "costUsd": 19.5,
    "stock": 4,
    "barcode": "7590000000264",
    "requiresPrescription": true,
    "isControlled": true,
    "image": "/products/7590000000264.jpg",
    "originalCategory": "Psicotrópicos y Controlados"
  },
  {
    "name": "Cytotec 200 mcg",
    "genericName": "Misoprostol",
    "laboratorio": "Cytotec",
    "concentracion": "200 mcg",
    "presentacion": "Tabletas",
    "category": "analgesicos",
    "priceUsd": 25.0,
    "costUsd": 16.25,
    "stock": 7,
    "barcode": "7590000000265",
    "requiresPrescription": true,
    "isControlled": true,
    "image": "/products/7590000000265.jpg",
    "originalCategory": "Psicotrópicos y Controlados"
  },
  {
    "name": "Betametasona Dipropionato 0.05%",
    "genericName": "Betametasona Dipropionato",
    "laboratorio": "Genérico",
    "concentracion": "0.05%",
    "presentacion": "Tubo 30g",
    "category": "dermatologicos",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 3,
    "barcode": "7590000000266",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000266.jpg",
    "originalCategory": "Cremas y Tópicos"
  },
  {
    "name": "Poentobral 5 g",
    "genericName": "Tobramicina Ungüento",
    "laboratorio": "Poen",
    "concentracion": "5 g",
    "presentacion": "Tubo",
    "category": "dermatologicos",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 2,
    "barcode": "7590000000267",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000267.jpg",
    "originalCategory": "Cremas y Tópicos"
  },
  {
    "name": "Derain 15%",
    "genericName": "Cicatrizante / Extracto",
    "laboratorio": "Derain",
    "concentracion": "15%",
    "presentacion": "Tubo 15g",
    "category": "dermatologicos",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 2,
    "barcode": "7590000000268",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000268.jpg",
    "originalCategory": "Cremas y Tópicos"
  },
  {
    "name": "Duroval 50 mg",
    "genericName": "Sildenafilo",
    "laboratorio": "Duroval",
    "concentracion": "50 mg",
    "presentacion": "Cap x 8",
    "category": "analgesicos",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 8,
    "barcode": "7590000000269",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000269.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Triderm Tubo 20g",
    "genericName": "Clotrimazol + Neomicina + Betametasona",
    "laboratorio": "Triderm",
    "concentracion": "20 g",
    "presentacion": "Tubo 20g",
    "category": "dermatologicos",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 1,
    "barcode": "7590000000270",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000270.jpg",
    "originalCategory": "Cremas y Tópicos"
  },
  {
    "name": "Silvederma 1%",
    "genericName": "Sulfadiazina de Plata",
    "laboratorio": "Silvederma",
    "concentracion": "1%",
    "presentacion": "Pote 400g",
    "category": "dermatologicos",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 2,
    "barcode": "7590000000271",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000271.jpg",
    "originalCategory": "Cremas y Tópicos"
  },
  {
    "name": "Dexametasona 4 mg/1 ml",
    "genericName": "Dexametasona",
    "laboratorio": "Genérico",
    "concentracion": "4 mg/1 ml",
    "presentacion": "Ampolla",
    "category": "analgesicos",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 4,
    "barcode": "7590000000272",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000272.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Diclofenac Potásico 75 mg/3 ml",
    "genericName": "Diclofenac Potásico",
    "laboratorio": "Genérico",
    "concentracion": "75 mg/3 ml",
    "presentacion": "Ampolla",
    "category": "analgesicos",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 12,
    "barcode": "7590000000273",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000273.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Dexametasona 8 mg/2 ml",
    "genericName": "Dexametasona",
    "laboratorio": "Genérico",
    "concentracion": "8 mg/2 ml",
    "presentacion": "Ampolla",
    "category": "analgesicos",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 12,
    "barcode": "7590000000274",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000274.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Dipirona 1 g/2 ml",
    "genericName": "Dipirona",
    "laboratorio": "Genérico",
    "concentracion": "1 g/2 ml",
    "presentacion": "Ampolla",
    "category": "analgesicos",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 7,
    "barcode": "7590000000275",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000275.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Clorfeniramina 10 mg/1 ml",
    "genericName": "Clorfeniramina",
    "laboratorio": "Genérico",
    "concentracion": "10 mg/1 ml",
    "presentacion": "Ampolla",
    "category": "analgesicos",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 4,
    "barcode": "7590000000276",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000276.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Ceftazidima 1 g",
    "genericName": "Ceftazidima",
    "laboratorio": "Genérico",
    "concentracion": "1 g",
    "presentacion": "Vial",
    "category": "analgesicos",
    "priceUsd": 13.0,
    "costUsd": 8.45,
    "stock": 4,
    "barcode": "7590000000277",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000277.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Cefazolina 1 g",
    "genericName": "Cefazolina",
    "laboratorio": "Genérico",
    "concentracion": "1 g",
    "presentacion": "Vial",
    "category": "analgesicos",
    "priceUsd": 3.5,
    "costUsd": 2.27,
    "stock": 5,
    "barcode": "7590000000278",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000278.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Cifarcaína 2%",
    "genericName": "Lidocaína",
    "laboratorio": "Laferca",
    "concentracion": "2%",
    "presentacion": "Ampolla",
    "category": "analgesicos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 6,
    "barcode": "7590000000279",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000279.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
  {
    "name": "Dobutamina 250 mg",
    "genericName": "Dobutamina",
    "laboratorio": "Genérico",
    "concentracion": "250 mg",
    "presentacion": "Ampolla",
    "category": "analgesicos",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 0,
    "barcode": "7590000000280",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000280.jpg",
    "originalCategory": "Inyectables y Soluciones"
  },
];
