// Seed products 1-40 (auto-generated split)
export const SEED_PRODUCTS_01 = [
  {
    "name": "Ácido Fólico 5 mg (PlusAndex)",
    "genericName": "Ácido Fólico",
    "laboratorio": "PlusAndex",
    "concentracion": "5 mg",
    "presentacion": "Blister x 10",
    "category": "vitaminas",
    "priceUsd": 1.5,
    "costUsd": 0.98,
    "stock": 12,
    "barcode": "7590000000001",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000001.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Ácido Fólico 10 mg (Calox)",
    "genericName": "Ácido Fólico",
    "laboratorio": "Calox",
    "concentracion": "10 mg",
    "presentacion": "Blister x 10",
    "category": "vitaminas",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 14,
    "barcode": "7590000000002",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000002.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Amaremfem 150 mg",
    "genericName": "Ácido Ibandrónico",
    "laboratorio": "Amaremfem",
    "concentracion": "150 mg",
    "presentacion": "Caja x 1",
    "category": "analgesicos",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 2,
    "barcode": "7590000000003",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000003.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Litomen 300 mg",
    "genericName": "Ácido Ursodesoxicólico",
    "laboratorio": "Litomen",
    "concentracion": "300 mg",
    "presentacion": "Caja",
    "category": "analgesicos",
    "priceUsd": 45.0,
    "costUsd": 29.25,
    "stock": 1,
    "barcode": "7590000000004",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000004.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Ácido Mefenámico 500 mg",
    "genericName": "Ácido Mefenámico",
    "laboratorio": "Genérico",
    "concentracion": "500 mg",
    "presentacion": "Caja x 10",
    "category": "analgesicos",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 3,
    "barcode": "7590000000005",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000005.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Aciclovir 200 mg (Kattun Medic)",
    "genericName": "Aciclovir",
    "laboratorio": "Kattun Medic",
    "concentracion": "200 mg",
    "presentacion": "Caja x 10",
    "category": "analgesicos",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 3,
    "barcode": "7590000000006",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000006.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Aciclovir 400 mg",
    "genericName": "Aciclovir",
    "laboratorio": "Genérico",
    "concentracion": "400 mg",
    "presentacion": "Caja x 10",
    "category": "analgesicos",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 3,
    "barcode": "7590000000007",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000007.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Xanextra 500 mg",
    "genericName": "Ácido Tranexámico",
    "laboratorio": "Xanextra",
    "concentracion": "500 mg",
    "presentacion": "Cap x 7",
    "category": "analgesicos",
    "priceUsd": 7.0,
    "costUsd": 4.55,
    "stock": 3,
    "barcode": "7590000000008",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000008.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Ácido Tranexámico 500 mg",
    "genericName": "Ácido Tranexámico",
    "laboratorio": "Genérico",
    "concentracion": "500 mg",
    "presentacion": "Cap x 10",
    "category": "analgesicos",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 0,
    "barcode": "7590000000009",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000009.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "ValPron 500 mg",
    "genericName": "Ácido Valproico",
    "laboratorio": "ValPron",
    "concentracion": "500 mg",
    "presentacion": "Blister",
    "category": "analgesicos",
    "priceUsd": 1.5,
    "costUsd": 0.98,
    "stock": 2,
    "barcode": "7590000000010",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000010.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Ácido Valproico 250 mg",
    "genericName": "Ácido Valproico",
    "laboratorio": "Genérico",
    "concentracion": "250 mg",
    "presentacion": "Blister",
    "category": "analgesicos",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 2,
    "barcode": "7590000000011",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000011.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Ácido Valproico 500 mg (Zifluvis)",
    "genericName": "Ácido Valproico",
    "laboratorio": "Zifluvis",
    "concentracion": "500 mg",
    "presentacion": "-",
    "category": "analgesicos",
    "priceUsd": 9.0,
    "costUsd": 5.85,
    "stock": 0,
    "barcode": "7590000000012",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000012.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Acetilcisteína 600 mg",
    "genericName": "Acetilcisteína",
    "laboratorio": "Genérico",
    "concentracion": "600 mg",
    "presentacion": "Sobres",
    "category": "analgesicos",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 4,
    "barcode": "7590000000013",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000013.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Fluimexina 200 mg",
    "genericName": "Acetilcisteína",
    "laboratorio": "Fluimexina",
    "concentracion": "200 mg",
    "presentacion": "Sobres",
    "category": "analgesicos",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 7,
    "barcode": "7590000000014",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000014.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Mucochem 200 mg",
    "genericName": "N-Acetilcisteína",
    "laboratorio": "Mucochem",
    "concentracion": "200 mg",
    "presentacion": "Sobres",
    "category": "analgesicos",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 7,
    "barcode": "7590000000015",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000015.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Albendazol 200 mg (Calox)",
    "genericName": "Albendazol",
    "laboratorio": "Calox",
    "concentracion": "200 mg",
    "presentacion": "Tab x 2",
    "category": "antiparasitarios",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 1,
    "barcode": "7590000000016",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000016.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Albicar 200 mg",
    "genericName": "Albendazol",
    "laboratorio": "Albicar",
    "concentracion": "200 mg",
    "presentacion": "Tab x 2",
    "category": "antiparasitarios",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 8,
    "barcode": "7590000000017",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000017.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Albendazol 400 mg",
    "genericName": "Albendazol",
    "laboratorio": "Genérico",
    "concentracion": "400 mg",
    "presentacion": "Tab x 10",
    "category": "antiparasitarios",
    "priceUsd": 3.5,
    "costUsd": 2.27,
    "stock": 1,
    "barcode": "7590000000018",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000018.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Albendazol 400 mg (Protafarma)",
    "genericName": "Albendazol",
    "laboratorio": "Protafarma",
    "concentracion": "400 mg",
    "presentacion": "Tab x 2",
    "category": "antiparasitarios",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 2,
    "barcode": "7590000000019",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000019.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Aflamax 50 mg (Tab x 20)",
    "genericName": "Diclofenac Potásico",
    "laboratorio": "Aflamax",
    "concentracion": "50 mg",
    "presentacion": "Tab x 20",
    "category": "analgesicos",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 4,
    "barcode": "7590000000020",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000020.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Aflamax 50 mg (Tab x 10)",
    "genericName": "Diclofenac Potásico",
    "laboratorio": "Aflamax",
    "concentracion": "50 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 6,
    "barcode": "7590000000021",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000021.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Algoren 10 mg",
    "genericName": "Propranolol Clorhidrato",
    "laboratorio": "Algoren",
    "concentracion": "10 mg",
    "presentacion": "Tab x 20",
    "category": "analgesicos",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 1,
    "barcode": "7590000000022",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000022.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Alopurinol 300 mg (Protafarma)",
    "genericName": "Alopurinol",
    "laboratorio": "Protafarma",
    "concentracion": "300 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 2,
    "barcode": "7590000000023",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000023.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Aluron 100 mg",
    "genericName": "Alopurinol",
    "laboratorio": "Aluron",
    "concentracion": "100 mg",
    "presentacion": "Caja",
    "category": "analgesicos",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 2,
    "barcode": "7590000000024",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000024.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Amlodipina 5 mg (Protafarma)",
    "genericName": "Amlodipina",
    "laboratorio": "Protafarma",
    "concentracion": "5 mg",
    "presentacion": "Tab x 10",
    "category": "cardiovascular",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 6,
    "barcode": "7590000000025",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000025.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Amlodipina 5 mg (Genven)",
    "genericName": "Amlodipina",
    "laboratorio": "Genven",
    "concentracion": "5 mg",
    "presentacion": "Tab x 10",
    "category": "cardiovascular",
    "priceUsd": 2.5,
    "costUsd": 1.62,
    "stock": 1,
    "barcode": "7590000000026",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000026.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Kimiceg 5 mg",
    "genericName": "Amlodipina",
    "laboratorio": "Kimiceg",
    "concentracion": "5 mg",
    "presentacion": "Tab x 10",
    "category": "cardiovascular",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 4,
    "barcode": "7590000000027",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000027.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Amlodipina 10 mg (Protafarma)",
    "genericName": "Amlodipina",
    "laboratorio": "Protafarma",
    "concentracion": "10 mg",
    "presentacion": "Tab x 10",
    "category": "cardiovascular",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 2,
    "barcode": "7590000000028",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000028.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Amlodipina 10 mg (Genven)",
    "genericName": "Amlodipina",
    "laboratorio": "Genven",
    "concentracion": "10 mg",
    "presentacion": "Tab x 10",
    "category": "cardiovascular",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 2,
    "barcode": "7590000000029",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000029.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "La Santé 10 mg",
    "genericName": "Amlodipina",
    "laboratorio": "La Santé",
    "concentracion": "10 mg",
    "presentacion": "Tab x 10",
    "category": "cardiovascular",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 2,
    "barcode": "7590000000030",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000030.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Amiodarona Clorhidrato 200 mg",
    "genericName": "Amiodarona Clorhidrato",
    "laboratorio": "Genérico",
    "concentracion": "200 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 7.5,
    "costUsd": 4.88,
    "stock": 3,
    "barcode": "7590000000031",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000031.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Diarona Vincenti 200 mg",
    "genericName": "Amiodarona Clorhidrato",
    "laboratorio": "Vincenti",
    "concentracion": "200 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 2,
    "barcode": "7590000000032",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000032.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Doxiclav 875/125 mg",
    "genericName": "Amoxicilina + Ácido Clavulánico",
    "laboratorio": "Doxiclav",
    "concentracion": "875/125 mg",
    "presentacion": "Caja",
    "category": "antibioticos",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 1,
    "barcode": "7590000000033",
    "requiresPrescription": true,
    "isControlled": false,
    "image": "/products/7590000000033.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Amoxicilina + Ácido Clavulánico 875/125 mg (Protafarma)",
    "genericName": "Amoxicilina + Ácido Clavulánico",
    "laboratorio": "Protafarma",
    "concentracion": "875/125 mg",
    "presentacion": "Caja",
    "category": "antibioticos",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 2,
    "barcode": "7590000000034",
    "requiresPrescription": true,
    "isControlled": false,
    "image": "/products/7590000000034.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Sanfer 500/125 mg",
    "genericName": "Amoxicilina + Ácido Clavulánico",
    "laboratorio": "Sanfer",
    "concentracion": "500/125 mg",
    "presentacion": "Caja",
    "category": "antibioticos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 2,
    "barcode": "7590000000035",
    "requiresPrescription": true,
    "isControlled": false,
    "image": "/products/7590000000035.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Amoxicilina + Ácido Clavulánico 500/125 mg (Protafarma)",
    "genericName": "Amoxicilina + Ácido Clavulánico",
    "laboratorio": "Protafarma",
    "concentracion": "500/125 mg",
    "presentacion": "Caja",
    "category": "antibioticos",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 1,
    "barcode": "7590000000036",
    "requiresPrescription": true,
    "isControlled": false,
    "image": "/products/7590000000036.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Fulgram 875/125 mg",
    "genericName": "Amoxicilina + Ácido Clavulánico",
    "laboratorio": "Fulgram",
    "concentracion": "875/125 mg",
    "presentacion": "Caja",
    "category": "antibioticos",
    "priceUsd": 25.0,
    "costUsd": 16.25,
    "stock": 1,
    "barcode": "7590000000037",
    "requiresPrescription": true,
    "isControlled": false,
    "image": "/products/7590000000037.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Amitriptilina 25 mg",
    "genericName": "Amitriptilina",
    "laboratorio": "Genérico",
    "concentracion": "25 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 9,
    "barcode": "7590000000038",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000038.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Ampicilina 500 mg (Protafarma)",
    "genericName": "Ampicilina",
    "laboratorio": "Protafarma",
    "concentracion": "500 mg",
    "presentacion": "Tab x 10",
    "category": "antibioticos",
    "priceUsd": 3.5,
    "costUsd": 2.27,
    "stock": 4,
    "barcode": "7590000000039",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000039.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Atamel Forte Calox 650 mg",
    "genericName": "Paracetamol + Cafeína",
    "laboratorio": "Calox",
    "concentracion": "650 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 3,
    "barcode": "7590000000040",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000040.jpg",
    "originalCategory": "Medicamentos Orales"
  },
];
