// Seed products 521-560 (auto-generated split)
export const SEED_PRODUCTS_14 = [
  {
    "name": "Pepto-Bismol 525 mg/30 ml",
    "genericName": "Subsalicilato de Bismuto",
    "laboratorio": "Pepto-Bismol",
    "concentracion": "525 mg/30 ml",
    "presentacion": "Fco 118ml",
    "category": "respiratorio",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 1,
    "barcode": "7590000000521",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000521.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Pepsa-Del",
    "genericName": "Antiácido",
    "laboratorio": "Pepsa-Del",
    "concentracion": "",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 1,
    "barcode": "7590000000522",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000522.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Sinax 185/200/25 mg/5 ml",
    "genericName": "Antiácido",
    "laboratorio": "Sinax",
    "concentracion": "185/200/25 mg/5 ml",
    "presentacion": "Fco 200ml",
    "category": "respiratorio",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 1,
    "barcode": "7590000000523",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000523.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Leche Magnesia 8.5%",
    "genericName": "Hidróxido de Magnesio",
    "laboratorio": "Leche Magnesia",
    "concentracion": "8.5%",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 2,
    "barcode": "7590000000524",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000524.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Neutrox",
    "genericName": "Antiácido",
    "laboratorio": "Neutrox",
    "concentracion": "",
    "presentacion": "Fco",
    "category": "respiratorio",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 1,
    "barcode": "7590000000525",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000525.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Antiácido 150 ml",
    "genericName": "Antiácido",
    "laboratorio": "Genérico",
    "concentracion": "150 ml",
    "presentacion": "Fco 150ml",
    "category": "respiratorio",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 1,
    "barcode": "7590000000526",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000526.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Dicigel",
    "genericName": "Magaldrato + Simeticona",
    "laboratorio": "Dicigel",
    "concentracion": "",
    "presentacion": "Fco 240ml",
    "category": "respiratorio",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 1,
    "barcode": "7590000000527",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000527.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Senolax",
    "genericName": "Laxante",
    "laboratorio": "Senolax",
    "concentracion": "",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 2,
    "barcode": "7590000000528",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000528.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Limolax",
    "genericName": "Laxante",
    "laboratorio": "Limolax",
    "concentracion": "",
    "presentacion": "Fco 250ml",
    "category": "respiratorio",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 2,
    "barcode": "7590000000529",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000529.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Cloruro de Magnesio Líquido 500 ml",
    "genericName": "Cloruro de Magnesio Líquido",
    "laboratorio": "Genérico",
    "concentracion": "500 ml",
    "presentacion": "Fco 500ml",
    "category": "respiratorio",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 1,
    "barcode": "7590000000530",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000530.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Citrato de Potasio Líquido 500 ml",
    "genericName": "Citrato de Potasio Líquido",
    "laboratorio": "Genérico",
    "concentracion": "500 ml",
    "presentacion": "Fco 500ml",
    "category": "respiratorio",
    "priceUsd": 9.0,
    "costUsd": 5.85,
    "stock": 1,
    "barcode": "7590000000531",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000531.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Vitisival B1-B12",
    "genericName": "Vitaminas B Complejo",
    "laboratorio": "Vitisival",
    "concentracion": "B1-B12",
    "presentacion": "Fco",
    "category": "respiratorio",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 1,
    "barcode": "7590000000532",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000532.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Vitalit B B3, B6, B12",
    "genericName": "Vitaminas B",
    "laboratorio": "Vitalit B",
    "concentracion": "B3, B6, B12",
    "presentacion": "Fco",
    "category": "respiratorio",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 2,
    "barcode": "7590000000533",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000533.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Apetinín",
    "genericName": "Estimulante Apetito",
    "laboratorio": "Apetinín",
    "concentracion": "",
    "presentacion": "Fco 240ml",
    "category": "respiratorio",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 2,
    "barcode": "7590000000534",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000534.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Calzinc D",
    "genericName": "Calcio + Zinc + D",
    "laboratorio": "Calzinc D",
    "concentracion": "",
    "presentacion": "Fco",
    "category": "respiratorio",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 1,
    "barcode": "7590000000535",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000535.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Multihierro",
    "genericName": "Multihierro",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Fco",
    "category": "respiratorio",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 1,
    "barcode": "7590000000536",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000536.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Miovit (Fco 90ml)",
    "genericName": "Vitaminas B",
    "laboratorio": "Miovit",
    "concentracion": "",
    "presentacion": "Fco 90ml",
    "category": "respiratorio",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 4,
    "barcode": "7590000000537",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000537.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Letisan 100 mg/ml",
    "genericName": "Vitamina C Gotas",
    "laboratorio": "Letisan",
    "concentracion": "100 mg/ml",
    "presentacion": "Gotero",
    "category": "respiratorio",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 2,
    "barcode": "7590000000538",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000538.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Acticar 1 g/10 ml",
    "genericName": "L-Carnitina",
    "laboratorio": "Acticar",
    "concentracion": "1 g/10 ml",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 1,
    "barcode": "7590000000539",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000539.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Carnisin 1 g/10 ml",
    "genericName": "Levocarnitina",
    "laboratorio": "Carnisin",
    "concentracion": "1 g/10 ml",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 1,
    "barcode": "7590000000540",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000540.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Rocarnin 10%",
    "genericName": "L-Carnitina",
    "laboratorio": "Rocarnin",
    "concentracion": "10%",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 2,
    "barcode": "7590000000541",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000541.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Nista-Fur",
    "genericName": "Nistatina Gotas",
    "laboratorio": "Nista-Fur",
    "concentracion": "",
    "presentacion": "Gotero 30ml",
    "category": "respiratorio",
    "priceUsd": 9.0,
    "costUsd": 5.85,
    "stock": 4,
    "barcode": "7590000000542",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000542.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Clodoxin 5/50 mg",
    "genericName": "Metoclopramida + Vit B6",
    "laboratorio": "Clodoxin",
    "concentracion": "5/50 mg",
    "presentacion": "Fco",
    "category": "respiratorio",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 1,
    "barcode": "7590000000543",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000543.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Clop 5 mg/5 ml",
    "genericName": "Metoclopramida",
    "laboratorio": "Clop",
    "concentracion": "5 mg/5 ml",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 1,
    "barcode": "7590000000544",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000544.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Metoclopramida 5 mg/5 ml (Drotafarma)",
    "genericName": "Metoclopramida",
    "laboratorio": "Drotafarma",
    "concentracion": "5 mg/5 ml",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 7.0,
    "costUsd": 4.55,
    "stock": 1,
    "barcode": "7590000000545",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000545.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Jarabe de Berro",
    "genericName": "Jarabe de Berro",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 2,
    "barcode": "7590000000546",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000546.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Jarabe Jen-Miel",
    "genericName": "Jarabe Jen-Miel",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Fco 180ml",
    "category": "respiratorio",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 1,
    "barcode": "7590000000547",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000547.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Jarabe Sabe Miel",
    "genericName": "Jarabe Sabe Miel",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Fco 180ml",
    "category": "respiratorio",
    "priceUsd": 9.0,
    "costUsd": 5.85,
    "stock": 2,
    "barcode": "7590000000548",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000548.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Torlem",
    "genericName": "Expectorante",
    "laboratorio": "Torlem",
    "concentracion": "",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 1,
    "barcode": "7590000000549",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000549.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Tilodrin 30 mg/15 ml",
    "genericName": "Dextrometorfano",
    "laboratorio": "Tilodrin",
    "concentracion": "30 mg/15 ml",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 1,
    "barcode": "7590000000550",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000550.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Hedraliv 0.07%",
    "genericName": "Hedera Helix",
    "laboratorio": "Hedraliv",
    "concentracion": "0.07%",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 14.0,
    "costUsd": 9.1,
    "stock": 1,
    "barcode": "7590000000551",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000551.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Lamedor Adulto",
    "genericName": "Lamedor Adulto",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 9.0,
    "costUsd": 5.85,
    "stock": 1,
    "barcode": "7590000000552",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000552.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Lamedor Pediátrico",
    "genericName": "Lamedor Pediátrico",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 9.0,
    "costUsd": 5.85,
    "stock": 1,
    "barcode": "7590000000553",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000553.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Jengibre con Berro",
    "genericName": "Jengibre con Berro",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 1,
    "barcode": "7590000000554",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000554.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Loganil 100 mg/5 ml",
    "genericName": "Carbocisteína",
    "laboratorio": "Loganil",
    "concentracion": "100 mg/5 ml",
    "presentacion": "Fco",
    "category": "respiratorio",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 1,
    "barcode": "7590000000555",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000555.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Farmagenik",
    "genericName": "Jarabe Lamedor",
    "laboratorio": "Farmagenik",
    "concentracion": "",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 9.0,
    "costUsd": 5.85,
    "stock": 2,
    "barcode": "7590000000556",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000556.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Fluvirin 35 mg/5 ml",
    "genericName": "Fluvirin",
    "laboratorio": "Fluvirin",
    "concentracion": "35 mg/5 ml",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 14.0,
    "costUsd": 9.1,
    "stock": 1,
    "barcode": "7590000000557",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000557.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Prospan 7 mg/ml",
    "genericName": "Hedera Helix",
    "laboratorio": "Prospan",
    "concentracion": "7 mg/ml",
    "presentacion": "Fco 100ml",
    "category": "respiratorio",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 1,
    "barcode": "7590000000558",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000558.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Yonal 15 mg/5 ml",
    "genericName": "Ambroxol",
    "laboratorio": "Yonal",
    "concentracion": "15 mg/5 ml",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 9.0,
    "costUsd": 5.85,
    "stock": 3,
    "barcode": "7590000000559",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000559.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Yonalab 15/3 mg/5 ml",
    "genericName": "Ambroxol + Clenbuterol",
    "laboratorio": "Yonalab",
    "concentracion": "15/3 mg/5 ml",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 9.0,
    "costUsd": 5.85,
    "stock": 1,
    "barcode": "7590000000560",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000560.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
];
