// Seed products 481-520 (auto-generated split)
export const SEED_PRODUCTS_13 = [
  {
    "name": "Otaflan 2 mg/ml",
    "genericName": "Diclofenac",
    "laboratorio": "Otaflan",
    "concentracion": "2 mg/ml",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 1,
    "barcode": "7590000000481",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000481.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "SyG 250 mg/5 ml",
    "genericName": "Amoxicilina",
    "laboratorio": "SyG",
    "concentracion": "250 mg/5 ml",
    "presentacion": "Polvo 60ml",
    "category": "respiratorio",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 2,
    "barcode": "7590000000482",
    "requiresPrescription": true,
    "isControlled": false,
    "image": "/products/7590000000482.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Amoxival 750 mg/5 ml",
    "genericName": "Amoxicilina",
    "laboratorio": "Amoxival",
    "concentracion": "750 mg/5 ml",
    "presentacion": "Polvo",
    "category": "respiratorio",
    "priceUsd": 20.0,
    "costUsd": 13.0,
    "stock": 2,
    "barcode": "7590000000483",
    "requiresPrescription": true,
    "isControlled": false,
    "image": "/products/7590000000483.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Fulgram 600/42.9 mg/5 ml",
    "genericName": "Amoxicilina + Ácido Clavulánico",
    "laboratorio": "Fulgram",
    "concentracion": "600/42.9 mg/5 ml",
    "presentacion": "Fco 60ml",
    "category": "respiratorio",
    "priceUsd": 22.0,
    "costUsd": 14.3,
    "stock": 1,
    "barcode": "7590000000484",
    "requiresPrescription": true,
    "isControlled": false,
    "image": "/products/7590000000484.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Clavumed 250/62.5 mg/5 ml",
    "genericName": "Amoxicilina + Ácido Clavulánico",
    "laboratorio": "Clavumed",
    "concentracion": "250/62.5 mg/5 ml",
    "presentacion": "Fco 60ml",
    "category": "respiratorio",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 3,
    "barcode": "7590000000485",
    "requiresPrescription": true,
    "isControlled": false,
    "image": "/products/7590000000485.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Clavumed 600/42.9 mg/5 ml",
    "genericName": "Amoxicilina + Ácido Clavulánico",
    "laboratorio": "Clavumed",
    "concentracion": "600/42.9 mg/5 ml",
    "presentacion": "Fco 60ml",
    "category": "respiratorio",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 3,
    "barcode": "7590000000486",
    "requiresPrescription": true,
    "isControlled": false,
    "image": "/products/7590000000486.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Amoxicilina + Ácido Clavulánico 250/62.5 mg/5 ml",
    "genericName": "Amoxicilina + Ácido Clavulánico",
    "laboratorio": "Genérico",
    "concentracion": "250/62.5 mg/5 ml",
    "presentacion": "Fco 60ml",
    "category": "respiratorio",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 1,
    "barcode": "7590000000487",
    "requiresPrescription": true,
    "isControlled": false,
    "image": "/products/7590000000487.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Amoklavin-Bid 400/57 mg/5 ml",
    "genericName": "Amoxicilina + Ácido Clavulánico",
    "laboratorio": "Amoklavin-Bid",
    "concentracion": "400/57 mg/5 ml",
    "presentacion": "Fco Forte",
    "category": "respiratorio",
    "priceUsd": 20.0,
    "costUsd": 13.0,
    "stock": 1,
    "barcode": "7590000000488",
    "requiresPrescription": true,
    "isControlled": false,
    "image": "/products/7590000000488.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Fahd 200 mg/5 ml",
    "genericName": "Azitromicina",
    "laboratorio": "Fahd",
    "concentracion": "200 mg/5 ml",
    "presentacion": "Fco 15ml",
    "category": "respiratorio",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 2,
    "barcode": "7590000000489",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000489.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Arzomidol 200 mg/5 ml",
    "genericName": "Azitromicina",
    "laboratorio": "Arzomidol",
    "concentracion": "200 mg/5 ml",
    "presentacion": "Fco 15ml",
    "category": "respiratorio",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 1,
    "barcode": "7590000000490",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000490.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Pharmetique 250 mg/5 ml",
    "genericName": "Ampicilina",
    "laboratorio": "Pharmetique",
    "concentracion": "250 mg/5 ml",
    "presentacion": "Fco 60ml",
    "category": "respiratorio",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 1,
    "barcode": "7590000000491",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000491.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Cefadroxilo 250 mg/5 ml",
    "genericName": "Cefadroxilo",
    "laboratorio": "Genérico",
    "concentracion": "250 mg/5 ml",
    "presentacion": "Fco 60ml",
    "category": "respiratorio",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 1,
    "barcode": "7590000000492",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000492.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Cleo 100 mg/5 ml",
    "genericName": "Cefixima",
    "laboratorio": "Cleo",
    "concentracion": "100 mg/5 ml",
    "presentacion": "Fco 60ml",
    "category": "respiratorio",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 1,
    "barcode": "7590000000493",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000493.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Dacss 100 mg/5 ml",
    "genericName": "Cefixima",
    "laboratorio": "Dacss",
    "concentracion": "100 mg/5 ml",
    "presentacion": "Fco 60ml",
    "category": "respiratorio",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 1,
    "barcode": "7590000000494",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000494.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Cefalexina 125 mg/5 ml",
    "genericName": "Cefalexina",
    "laboratorio": "Genérico",
    "concentracion": "125 mg/5 ml",
    "presentacion": "Fco",
    "category": "respiratorio",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 3,
    "barcode": "7590000000495",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000495.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Claritromicina 250 mg/5 ml",
    "genericName": "Claritromicina",
    "laboratorio": "Genérico",
    "concentracion": "250 mg/5 ml",
    "presentacion": "Fco 50ml",
    "category": "respiratorio",
    "priceUsd": 20.0,
    "costUsd": 13.0,
    "stock": 1,
    "barcode": "7590000000496",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000496.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Ciprofloxacina 250 mg/5 ml",
    "genericName": "Ciprofloxacina",
    "laboratorio": "Genérico",
    "concentracion": "250 mg/5 ml",
    "presentacion": "Fco 60ml",
    "category": "respiratorio",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 1,
    "barcode": "7590000000497",
    "requiresPrescription": true,
    "isControlled": false,
    "image": "/products/7590000000497.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Talerc 1 mg/ml",
    "genericName": "Cetirizina",
    "laboratorio": "Talerc",
    "concentracion": "1 mg/ml",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 9.0,
    "costUsd": 5.85,
    "stock": 2,
    "barcode": "7590000000498",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000498.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Cetral 5 mg/5 ml",
    "genericName": "Cetirizina",
    "laboratorio": "Cetral",
    "concentracion": "5 mg/5 ml",
    "presentacion": "Fco 60ml",
    "category": "respiratorio",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 2,
    "barcode": "7590000000499",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000499.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Cetral D 5/60 mg",
    "genericName": "Cetirizina + Pseudoefedrina",
    "laboratorio": "Cetral D",
    "concentracion": "5/60 mg",
    "presentacion": "Fco 60ml",
    "category": "respiratorio",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 1,
    "barcode": "7590000000500",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000500.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Brixmedic 5 mg/5 ml",
    "genericName": "Cetirizina",
    "laboratorio": "Brixmedic",
    "concentracion": "5 mg/5 ml",
    "presentacion": "Fco 60ml",
    "category": "respiratorio",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 3,
    "barcode": "7590000000501",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000501.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Kwality 5 mg/5 ml",
    "genericName": "Loratadina",
    "laboratorio": "Kwality",
    "concentracion": "5 mg/5 ml",
    "presentacion": "Fco 60ml",
    "category": "respiratorio",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 1,
    "barcode": "7590000000502",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000502.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Buka 5 mg/5 ml",
    "genericName": "Loratadina",
    "laboratorio": "Buka",
    "concentracion": "5 mg/5 ml",
    "presentacion": "Fco 60ml",
    "category": "respiratorio",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 1,
    "barcode": "7590000000503",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000503.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Lorecort 1/0.05 mg",
    "genericName": "Loratadina + Betametasona",
    "laboratorio": "Lorecort",
    "concentracion": "1/0.05 mg",
    "presentacion": "Fco",
    "category": "respiratorio",
    "priceUsd": 25.0,
    "costUsd": 16.25,
    "stock": 1,
    "barcode": "7590000000504",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000504.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Deslorat 0.5 mg/ml",
    "genericName": "Desloratadina",
    "laboratorio": "Deslorat",
    "concentracion": "0.5 mg/ml",
    "presentacion": "Fco 60ml",
    "category": "respiratorio",
    "priceUsd": 9.0,
    "costUsd": 5.85,
    "stock": 1,
    "barcode": "7590000000505",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000505.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Predix 3 mg/ml",
    "genericName": "Prednisolona",
    "laboratorio": "Drotafarma",
    "concentracion": "3 mg/ml",
    "presentacion": "Fco",
    "category": "respiratorio",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 3,
    "barcode": "7590000000506",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000506.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Cortibrix 3 mg/ml",
    "genericName": "Prednisolona",
    "laboratorio": "Brixmedic",
    "concentracion": "3 mg/ml",
    "presentacion": "Fco",
    "category": "respiratorio",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 3,
    "barcode": "7590000000507",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000507.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "PediaCort 3 mg/ml",
    "genericName": "Prednisolona",
    "laboratorio": "PediaCort",
    "concentracion": "3 mg/ml",
    "presentacion": "Fco 60ml",
    "category": "respiratorio",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 1,
    "barcode": "7590000000508",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000508.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Aciclovir 200 mg/5 ml",
    "genericName": "Aciclovir",
    "laboratorio": "Genérico",
    "concentracion": "200 mg/5 ml",
    "presentacion": "Fco 100ml",
    "category": "respiratorio",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 1,
    "barcode": "7590000000509",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000509.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "IQI",
    "genericName": "Piperazina",
    "laboratorio": "IQI",
    "concentracion": "",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 1,
    "barcode": "7590000000510",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000510.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Metronidazol 250 mg/5 ml",
    "genericName": "Metronidazol",
    "laboratorio": "Genérico",
    "concentracion": "250 mg/5 ml",
    "presentacion": "Fco 100ml",
    "category": "respiratorio",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 3,
    "barcode": "7590000000511",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000511.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Xonidax 100 mg/5 ml",
    "genericName": "Nitazoxanida",
    "laboratorio": "Xonidax",
    "concentracion": "100 mg/5 ml",
    "presentacion": "Fco 60ml",
    "category": "respiratorio",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 2,
    "barcode": "7590000000512",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000512.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "HYM 100 mg/5 ml",
    "genericName": "Nitazoxanida",
    "laboratorio": "HYM",
    "concentracion": "100 mg/5 ml",
    "presentacion": "Fco 60ml",
    "category": "respiratorio",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 1,
    "barcode": "7590000000513",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000513.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Piperazina 500 mg/5 ml (Drotafarma)",
    "genericName": "Piperazina",
    "laboratorio": "Drotafarma",
    "concentracion": "500 mg/5 ml",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 1,
    "barcode": "7590000000514",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000514.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Bioquímica 500 mg/5 ml",
    "genericName": "Piperazina",
    "laboratorio": "Bioquímica",
    "concentracion": "500 mg/5 ml",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 1,
    "barcode": "7590000000515",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000515.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Vizerul 150 mg/10 ml",
    "genericName": "Ranitidina",
    "laboratorio": "Vizerul",
    "concentracion": "150 mg/10 ml",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 1,
    "barcode": "7590000000516",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000516.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Ulcon 1 g/5 ml",
    "genericName": "Sucralfato",
    "laboratorio": "Ulcon",
    "concentracion": "1 g/5 ml",
    "presentacion": "Fco 80ml",
    "category": "respiratorio",
    "priceUsd": 30.0,
    "costUsd": 19.5,
    "stock": 1,
    "barcode": "7590000000517",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000517.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Co-Trimoxazol 240 mg/5 ml",
    "genericName": "Trimetoprima + Sulfametoxazol",
    "laboratorio": "Co-Trimoxazol",
    "concentracion": "240 mg/5 ml",
    "presentacion": "Fco 100ml",
    "category": "respiratorio",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 1,
    "barcode": "7590000000518",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000518.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Moderan 10.1 g/15 ml",
    "genericName": "Lactulosa",
    "laboratorio": "Moderan",
    "concentracion": "10.1 g/15 ml",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 20.0,
    "costUsd": 13.0,
    "stock": 1,
    "barcode": "7590000000519",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000519.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Bactron 40/200 mg/5 ml",
    "genericName": "Trimetoprima + Sulfametoxazol",
    "laboratorio": "Bactron",
    "concentracion": "40/200 mg/5 ml",
    "presentacion": "Fco 100ml",
    "category": "respiratorio",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 1,
    "barcode": "7590000000520",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000520.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
];
