// Seed products 441-480 (auto-generated split)
export const SEED_PRODUCTS_12 = [
  {
    "name": "Muñequera con Férula",
    "genericName": "Muñequera con Férula",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "otros",
    "priceUsd": 40.0,
    "costUsd": 26.0,
    "stock": 2,
    "barcode": "7590000000441",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000441.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Rodillera Elástica",
    "genericName": "Rodillera Elástica",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "otros",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 7,
    "barcode": "7590000000442",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000442.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Fajero Inguinal",
    "genericName": "Fajero Inguinal",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "otros",
    "priceUsd": 25.0,
    "costUsd": 16.25,
    "stock": 3,
    "barcode": "7590000000443",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000443.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Codera Elástica",
    "genericName": "Codera Elástica",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "otros",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 4,
    "barcode": "7590000000444",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000444.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Tobillera Elástica",
    "genericName": "Tobillera Elástica",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "otros",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 2,
    "barcode": "7590000000445",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000445.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Inmovilizador de Clavícula",
    "genericName": "Inmovilizador de Clavícula",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "otros",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 2,
    "barcode": "7590000000446",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000446.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Suspensorio Testicular",
    "genericName": "Suspensorio Testicular",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "otros",
    "priceUsd": 25.0,
    "costUsd": 16.25,
    "stock": 3,
    "barcode": "7590000000447",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000447.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Faja con Corrector Postura",
    "genericName": "Faja con Corrector Postura",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "otros",
    "priceUsd": 25.0,
    "costUsd": 16.25,
    "stock": 3,
    "barcode": "7590000000448",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000448.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Venda Elástica con Velcro 10cm",
    "genericName": "Venda Elástica con Velcro 10cm",
    "laboratorio": "Genérico",
    "concentracion": "10 cm",
    "presentacion": "Rollo",
    "category": "otros",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 2,
    "barcode": "7590000000449",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000449.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Venda Elástica con Velcro 15cm",
    "genericName": "Venda Elástica con Velcro 15cm",
    "laboratorio": "Genérico",
    "concentracion": "15 cm",
    "presentacion": "Rollo",
    "category": "otros",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 2,
    "barcode": "7590000000450",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000450.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "CPAP",
    "genericName": "CPAP",
    "laboratorio": "CPAP",
    "concentracion": "",
    "presentacion": "Equipo",
    "category": "otros",
    "priceUsd": 210.0,
    "costUsd": 136.5,
    "stock": 1,
    "barcode": "7590000000451",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000451.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Silla de Ruedas",
    "genericName": "Silla de Ruedas",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Equipo",
    "category": "otros",
    "priceUsd": 160.0,
    "costUsd": 104.0,
    "stock": 1,
    "barcode": "7590000000452",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000452.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Colchón Antiescaras",
    "genericName": "Colchón Antiescaras",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Equipo",
    "category": "otros",
    "priceUsd": 80.0,
    "costUsd": 52.0,
    "stock": 1,
    "barcode": "7590000000453",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000453.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Andadera",
    "genericName": "Andadera",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Equipo",
    "category": "otros",
    "priceUsd": 70.0,
    "costUsd": 45.5,
    "stock": 1,
    "barcode": "7590000000454",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000454.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Muletas",
    "genericName": "Muletas",
    "laboratorio": "Genérico",
    "concentracion": "Par",
    "presentacion": "Par",
    "category": "otros",
    "priceUsd": 50.0,
    "costUsd": 32.5,
    "stock": 1,
    "barcode": "7590000000455",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000455.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Brace de Rodilla Articulado",
    "genericName": "Brace de Rodilla Articulado",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "otros",
    "priceUsd": 150.0,
    "costUsd": 97.5,
    "stock": 1,
    "barcode": "7590000000456",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000456.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Aguja de Biopsia Tru-Cut # 14",
    "genericName": "Aguja de Biopsia Tru-Cut # 14",
    "laboratorio": "Tru-Cut",
    "concentracion": "14G",
    "presentacion": "Unidad",
    "category": "otros",
    "priceUsd": 65.0,
    "costUsd": 42.25,
    "stock": 1,
    "barcode": "7590000000457",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000457.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Aguja de Biopsia Tru-Cut # 16",
    "genericName": "Aguja de Biopsia Tru-Cut # 16",
    "laboratorio": "Tru-Cut",
    "concentracion": "16G",
    "presentacion": "Unidad",
    "category": "otros",
    "priceUsd": 65.0,
    "costUsd": 42.25,
    "stock": 1,
    "barcode": "7590000000458",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000458.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Aguja de Biopsia Tru-Cut # 18",
    "genericName": "Aguja de Biopsia Tru-Cut # 18",
    "laboratorio": "Tru-Cut",
    "concentracion": "18G",
    "presentacion": "Unidad",
    "category": "otros",
    "priceUsd": 65.0,
    "costUsd": 42.25,
    "stock": 1,
    "barcode": "7590000000459",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000459.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Catéter Bilumen Hemodiálisis",
    "genericName": "Catéter Bilumen Hemodiálisis",
    "laboratorio": "Genérico",
    "concentracion": "12Fr x 20cm",
    "presentacion": "Unidad",
    "category": "otros",
    "priceUsd": 75.0,
    "costUsd": 48.75,
    "stock": 1,
    "barcode": "7590000000460",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000460.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Catéter Vía Venosa Central",
    "genericName": "Catéter Vía Venosa Central",
    "laboratorio": "Triple Lumen",
    "concentracion": "7Fr x 20cm",
    "presentacion": "Kit",
    "category": "otros",
    "priceUsd": 60.0,
    "costUsd": 39.0,
    "stock": 1,
    "barcode": "7590000000461",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000461.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Catéter Doble J",
    "genericName": "Catéter Doble J",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Unidad",
    "category": "otros",
    "priceUsd": 40.0,
    "costUsd": 26.0,
    "stock": 1,
    "barcode": "7590000000462",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000462.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Malla Polipropileno 30x30cm",
    "genericName": "Malla Polipropileno 30x30cm",
    "laboratorio": "Genérico",
    "concentracion": "30x30 cm",
    "presentacion": "Unidad",
    "category": "otros",
    "priceUsd": 50.0,
    "costUsd": 32.5,
    "stock": 1,
    "barcode": "7590000000463",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000463.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Malla Polipropileno 10x10cm",
    "genericName": "Malla Polipropileno 10x10cm",
    "laboratorio": "Genérico",
    "concentracion": "10x10 cm",
    "presentacion": "Unidad",
    "category": "otros",
    "priceUsd": 25.0,
    "costUsd": 16.25,
    "stock": 1,
    "barcode": "7590000000464",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000464.jpg",
    "originalCategory": "Casa Médica y Equipos"
  },
  {
    "name": "Apiret 180 mg/5 ml (Fco 60ml)",
    "genericName": "Paracetamol",
    "laboratorio": "Apiret",
    "concentracion": "180 mg/5 ml",
    "presentacion": "Fco 60ml",
    "category": "respiratorio",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 3,
    "barcode": "7590000000465",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000465.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Apiret 180 mg/5 ml (Fco 120ml)",
    "genericName": "Paracetamol",
    "laboratorio": "Apiret",
    "concentracion": "180 mg/5 ml",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 9.0,
    "costUsd": 5.85,
    "stock": 2,
    "barcode": "7590000000466",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000466.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Febrilix 120 mg/5 ml",
    "genericName": "Paracetamol",
    "laboratorio": "Febrilix",
    "concentracion": "120 mg/5 ml",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 3,
    "barcode": "7590000000467",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000467.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Febrip 180 mg/5 ml",
    "genericName": "Paracetamol",
    "laboratorio": "Febrip",
    "concentracion": "180 mg/5 ml",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 4,
    "barcode": "7590000000468",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000468.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Dynacet 120 mg/5 ml",
    "genericName": "Paracetamol",
    "laboratorio": "Dynacet",
    "concentracion": "120 mg/5 ml",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 5,
    "barcode": "7590000000469",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000469.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Anydol Forte 180 mg/5 ml",
    "genericName": "Paracetamol",
    "laboratorio": "Anydol Forte",
    "concentracion": "180 mg/5 ml",
    "presentacion": "Fco 60ml",
    "category": "respiratorio",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 4,
    "barcode": "7590000000470",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000470.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Paracetamol 120 mg/5 ml (Drotafarma)",
    "genericName": "Paracetamol",
    "laboratorio": "Drotafarma",
    "concentracion": "120 mg/5 ml",
    "presentacion": "Fco 60ml",
    "category": "respiratorio",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 3,
    "barcode": "7590000000471",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000471.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Medigen 120 mg/5 ml",
    "genericName": "Paracetamol",
    "laboratorio": "Medigen",
    "concentracion": "120 mg/5 ml",
    "presentacion": "Fco 60ml",
    "category": "respiratorio",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 3,
    "barcode": "7590000000472",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000472.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Tachipirin Forte 160 mg/5 ml",
    "genericName": "Paracetamol",
    "laboratorio": "Tachipirin Forte",
    "concentracion": "160 mg/5 ml",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 3,
    "barcode": "7590000000473",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000473.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Ananty Forte 160 mg/5 ml",
    "genericName": "Paracetamol",
    "laboratorio": "Ananty Forte",
    "concentracion": "160 mg/5 ml",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 1,
    "barcode": "7590000000474",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000474.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Atamel 120 mg/5 ml",
    "genericName": "Paracetamol",
    "laboratorio": "Atamel",
    "concentracion": "120 mg/5 ml",
    "presentacion": "Fco 60ml",
    "category": "respiratorio",
    "priceUsd": 7.0,
    "costUsd": 4.55,
    "stock": 3,
    "barcode": "7590000000475",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000475.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Ibuprofeno 100 mg/5 ml",
    "genericName": "Ibuprofeno",
    "laboratorio": "Genérico",
    "concentracion": "100 mg/5 ml",
    "presentacion": "Fco 60ml",
    "category": "respiratorio",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 3,
    "barcode": "7590000000476",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000476.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Brixmedic 120 mg/5 ml",
    "genericName": "Paracetamol",
    "laboratorio": "Brixmedic",
    "concentracion": "120 mg/5 ml",
    "presentacion": "Fco 100ml",
    "category": "respiratorio",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 1,
    "barcode": "7590000000477",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000477.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Portugal 120 mg/5 ml",
    "genericName": "Paracetamol",
    "laboratorio": "Portugal",
    "concentracion": "120 mg/5 ml",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 8.5,
    "costUsd": 5.53,
    "stock": 1,
    "barcode": "7590000000478",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000478.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Brugesic Forte 200 mg/5 ml",
    "genericName": "Ibuprofeno",
    "laboratorio": "Brugesic Forte",
    "concentracion": "200 mg/5 ml",
    "presentacion": "Fco 60ml",
    "category": "respiratorio",
    "priceUsd": 7.0,
    "costUsd": 4.55,
    "stock": 1,
    "barcode": "7590000000479",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000479.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Diagesic 1.8 mg/ml",
    "genericName": "Diclofenac",
    "laboratorio": "Diagesic",
    "concentracion": "1.8 mg/ml",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 3,
    "barcode": "7590000000480",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000480.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
];
