// Seed products 561-600 (auto-generated split)
export const SEED_PRODUCTS_15 = [
  {
    "name": "Levoferin 30 mg/5 ml",
    "genericName": "Levodropropizina",
    "laboratorio": "Levoferin",
    "concentracion": "30 mg/5 ml",
    "presentacion": "Fco 90ml",
    "category": "respiratorio",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 2,
    "barcode": "7590000000561",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000561.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Dynalab 4 mg/5 ml",
    "genericName": "Bromhexina",
    "laboratorio": "Dynalab",
    "concentracion": "4 mg/5 ml",
    "presentacion": "Fco 100ml",
    "category": "respiratorio",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 2,
    "barcode": "7590000000562",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000562.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Dynalab 8 mg/5 ml",
    "genericName": "Bromhexina",
    "laboratorio": "Dynalab",
    "concentracion": "8 mg/5 ml",
    "presentacion": "Fco 100ml",
    "category": "respiratorio",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 2,
    "barcode": "7590000000563",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000563.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Perebrón 50 mg/5 ml",
    "genericName": "Oxolamina",
    "laboratorio": "Perebrón",
    "concentracion": "50 mg/5 ml",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 1,
    "barcode": "7590000000564",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000564.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Gencer 28 mg/5 ml",
    "genericName": "Oxolamina",
    "laboratorio": "Gencer",
    "concentracion": "28 mg/5 ml",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 2,
    "barcode": "7590000000565",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000565.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Kwality 28 mg/5 ml",
    "genericName": "Oxolamina",
    "laboratorio": "Kwality",
    "concentracion": "28 mg/5 ml",
    "presentacion": "Fco 100ml",
    "category": "respiratorio",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 2,
    "barcode": "7590000000566",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000566.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Kwality 50 mg/5 ml",
    "genericName": "Oxolamina",
    "laboratorio": "Kwality",
    "concentracion": "50 mg/5 ml",
    "presentacion": "Fco 100ml",
    "category": "respiratorio",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 1,
    "barcode": "7590000000567",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000567.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Antux 6 mg/ml",
    "genericName": "Levodropropizina",
    "laboratorio": "Antux",
    "concentracion": "6 mg/ml",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 3,
    "barcode": "7590000000568",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000568.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Acebrofilina 10 mg/ml",
    "genericName": "Acebrofilina",
    "laboratorio": "Genérico",
    "concentracion": "10 mg/ml",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 2,
    "barcode": "7590000000569",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000569.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Klas 100 mg/10 ml",
    "genericName": "Acebrofilina",
    "laboratorio": "Klas",
    "concentracion": "100 mg/10 ml",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 1,
    "barcode": "7590000000570",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000570.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Mucofar 100 mg/5 ml",
    "genericName": "Carbocisteína Pediátrico",
    "laboratorio": "Mucofar",
    "concentracion": "100 mg/5 ml",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 9.0,
    "costUsd": 5.85,
    "stock": 3,
    "barcode": "7590000000571",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000571.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Mucofar 250 mg/5 ml",
    "genericName": "Carbocisteína Adulto",
    "laboratorio": "Mucofar",
    "concentracion": "250 mg/5 ml",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 9.0,
    "costUsd": 5.85,
    "stock": 3,
    "barcode": "7590000000572",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000572.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Gulaper 100 mg/5 ml",
    "genericName": "Carbocisteína Pediátrico",
    "laboratorio": "Gulaper",
    "concentracion": "100 mg/5 ml",
    "presentacion": "Fco 60ml",
    "category": "respiratorio",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 2,
    "barcode": "7590000000573",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000573.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Gulaper 250 mg/5 ml",
    "genericName": "Carbocisteína Adulto",
    "laboratorio": "Gulaper",
    "concentracion": "250 mg/5 ml",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 2,
    "barcode": "7590000000574",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000574.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Quim-far 8 mg/5 ml",
    "genericName": "Bromhexina",
    "laboratorio": "Quim-far",
    "concentracion": "8 mg/5 ml",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 2,
    "barcode": "7590000000575",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000575.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Kwality 8 mg/5 ml",
    "genericName": "Bromhexina",
    "laboratorio": "Kwality",
    "concentracion": "8 mg/5 ml",
    "presentacion": "Fco 100ml",
    "category": "respiratorio",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 1,
    "barcode": "7590000000576",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000576.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Clenbunal 0.010 mg/5 ml",
    "genericName": "Clenbuterol",
    "laboratorio": "Clenbunal",
    "concentracion": "0.010 mg/5 ml",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 1,
    "barcode": "7590000000577",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000577.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Bromhexina Genérico 4 mg/5 ml",
    "genericName": "Bromhexina Genérico",
    "laboratorio": "Genérico",
    "concentracion": "4 mg/5 ml",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 1,
    "barcode": "7590000000578",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000578.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Muclar 30/5 mg",
    "genericName": "Ambroxol + Loratadina",
    "laboratorio": "Muclar",
    "concentracion": "30/5 mg",
    "presentacion": "Fco 60ml",
    "category": "respiratorio",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 2,
    "barcode": "7590000000579",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000579.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Ampluex 15 mg/5 ml",
    "genericName": "Ambroxol",
    "laboratorio": "Ampluex",
    "concentracion": "15 mg/5 ml",
    "presentacion": "Fco",
    "category": "respiratorio",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 2,
    "barcode": "7590000000580",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000580.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Arbixil 7.5 mg/5 mcg",
    "genericName": "Ambroxol + Clenbuterol",
    "laboratorio": "Arbixil",
    "concentracion": "7.5 mg/5 mcg",
    "presentacion": "Fco",
    "category": "respiratorio",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 2,
    "barcode": "7590000000581",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000581.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Ambroxol 30 mg/5 ml",
    "genericName": "Ambroxol",
    "laboratorio": "Genérico",
    "concentracion": "30 mg/5 ml",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 1,
    "barcode": "7590000000582",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000582.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Misulvan 15/0.01 mg/5 ml",
    "genericName": "Ambroxol + Clenbuterol",
    "laboratorio": "Misulvan",
    "concentracion": "15/0.01 mg/5 ml",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 1,
    "barcode": "7590000000583",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000583.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Ambroxol + Loratadina 30/5 mg/5 ml",
    "genericName": "Ambroxol + Loratadina",
    "laboratorio": "Genérico",
    "concentracion": "30/5 mg/5 ml",
    "presentacion": "Fco",
    "category": "respiratorio",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 1,
    "barcode": "7590000000584",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000584.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Levetiracetam 100 mg/ml",
    "genericName": "Levetiracetam",
    "laboratorio": "Genérico",
    "concentracion": "100 mg/ml",
    "presentacion": "Fco 100ml",
    "category": "respiratorio",
    "priceUsd": 25.0,
    "costUsd": 16.25,
    "stock": 1,
    "barcode": "7590000000585",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000585.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Ácido Valproico 250 mg/5 ml",
    "genericName": "Ácido Valproico",
    "laboratorio": "Genérico",
    "concentracion": "250 mg/5 ml",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 3,
    "barcode": "7590000000586",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000586.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Valpron 200 mg/ml",
    "genericName": "Ácido Valproico",
    "laboratorio": "Valpron",
    "concentracion": "200 mg/ml",
    "presentacion": "Gotero 30ml",
    "category": "respiratorio",
    "priceUsd": 20.0,
    "costUsd": 13.0,
    "stock": 1,
    "barcode": "7590000000587",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000587.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Ácido Fólico Jarabe 2.5 mg",
    "genericName": "Ácido Fólico Jarabe",
    "laboratorio": "Genérico",
    "concentracion": "2.5 mg",
    "presentacion": "Fco 100ml",
    "category": "respiratorio",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 5,
    "barcode": "7590000000588",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000588.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Hepafol",
    "genericName": "Hepafol",
    "laboratorio": "Hepafol",
    "concentracion": "",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 2,
    "barcode": "7590000000589",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000589.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Ferganic",
    "genericName": "Ferganic Folic Jarabe",
    "laboratorio": "Ferganic",
    "concentracion": "",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 1,
    "barcode": "7590000000590",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000590.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Wampole",
    "genericName": "Tónico Multivitamínico",
    "laboratorio": "Wampole",
    "concentracion": "",
    "presentacion": "Fco 120ml",
    "category": "respiratorio",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 4,
    "barcode": "7590000000591",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000591.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Sultamicilina 250 mg/5 ml",
    "genericName": "Sultamicilina",
    "laboratorio": "Genérico",
    "concentracion": "250 mg/5 ml",
    "presentacion": "Fco 60ml",
    "category": "respiratorio",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 2,
    "barcode": "7590000000592",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000592.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Tu-Miel Expectorante",
    "genericName": "Tu-Miel Expectorante",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Fco",
    "category": "respiratorio",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 2,
    "barcode": "7590000000593",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000593.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Regenerador Pulmonar Plus",
    "genericName": "Regenerador Pulmonar Plus",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Fco",
    "category": "respiratorio",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 4,
    "barcode": "7590000000594",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000594.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Asmi-Plus Jarabe",
    "genericName": "Asmi-Plus Jarabe",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Fco",
    "category": "respiratorio",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 1,
    "barcode": "7590000000595",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000595.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Jarabe Berro Adulto",
    "genericName": "Jarabe Berro Adulto",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Fco",
    "category": "respiratorio",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 2,
    "barcode": "7590000000596",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000596.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Jarabe Berro Pediátrico",
    "genericName": "Jarabe Berro Pediátrico",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Fco",
    "category": "respiratorio",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 1,
    "barcode": "7590000000597",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000597.jpg",
    "originalCategory": "Jarabes y Suspensiones"
  },
  {
    "name": "Sutura Catgut Crómico 0",
    "genericName": "Sutura Catgut Crómico 0",
    "laboratorio": "Crómico",
    "concentracion": "0",
    "presentacion": "Sobre/Hebra",
    "category": "primeros-auxilios",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 27,
    "barcode": "7590000000598",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000598.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
  {
    "name": "Sutura Catgut Crómico 1",
    "genericName": "Sutura Catgut Crómico 1",
    "laboratorio": "Crómico",
    "concentracion": "1",
    "presentacion": "Sobre/Hebra",
    "category": "primeros-auxilios",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 5,
    "barcode": "7590000000599",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000599.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
  {
    "name": "Sutura Catgut Crómico 2-0",
    "genericName": "Sutura Catgut Crómico 2-0",
    "laboratorio": "Crómico",
    "concentracion": "2-0",
    "presentacion": "Sobre/Hebra",
    "category": "primeros-auxilios",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 27,
    "barcode": "7590000000600",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000600.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
];
