// Seed products 601-640 (auto-generated split)
export const SEED_PRODUCTS_16 = [
  {
    "name": "Sutura Catgut Crómico 3-0",
    "genericName": "Sutura Catgut Crómico 3-0",
    "laboratorio": "Crómico",
    "concentracion": "3-0",
    "presentacion": "Sobre/Hebra",
    "category": "primeros-auxilios",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 21,
    "barcode": "7590000000601",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000601.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
  {
    "name": "Sutura Catgut Crómico 4-0",
    "genericName": "Sutura Catgut Crómico 4-0",
    "laboratorio": "Crómico",
    "concentracion": "4-0",
    "presentacion": "Sobre/Hebra",
    "category": "primeros-auxilios",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 3,
    "barcode": "7590000000602",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000602.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
  {
    "name": "Sutura Catgut Simple 0",
    "genericName": "Sutura Catgut Simple 0",
    "laboratorio": "Simple",
    "concentracion": "0",
    "presentacion": "Sobre/Hebra",
    "category": "primeros-auxilios",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 9,
    "barcode": "7590000000603",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000603.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
  {
    "name": "Sutura Catgut Simple 1",
    "genericName": "Sutura Catgut Simple 1",
    "laboratorio": "Simple",
    "concentracion": "1",
    "presentacion": "Sobre/Hebra",
    "category": "primeros-auxilios",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 4,
    "barcode": "7590000000604",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000604.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
  {
    "name": "Sutura Catgut Simple 2-0",
    "genericName": "Sutura Catgut Simple 2-0",
    "laboratorio": "Simple",
    "concentracion": "2-0",
    "presentacion": "Sobre/Hebra",
    "category": "primeros-auxilios",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 4,
    "barcode": "7590000000605",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000605.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
  {
    "name": "Sutura Catgut Simple 3-0",
    "genericName": "Sutura Catgut Simple 3-0",
    "laboratorio": "Simple",
    "concentracion": "3-0",
    "presentacion": "Sobre/Hebra",
    "category": "primeros-auxilios",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 6,
    "barcode": "7590000000606",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000606.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
  {
    "name": "Sutura Nylon 2-0 AR 2-0 Aguja Redonda",
    "genericName": "Sutura Nylon 2-0 AR",
    "laboratorio": "Nylon",
    "concentracion": "2-0 Aguja Redonda",
    "presentacion": "Sobre/Hebra",
    "category": "primeros-auxilios",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 34,
    "barcode": "7590000000607",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000607.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
  {
    "name": "Sutura Nylon 2-0 AC 2-0 Aguja Cortante",
    "genericName": "Sutura Nylon 2-0 AC",
    "laboratorio": "Nylon",
    "concentracion": "2-0 Aguja Cortante",
    "presentacion": "Sobre/Hebra",
    "category": "primeros-auxilios",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 12,
    "barcode": "7590000000608",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000608.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
  {
    "name": "Sutura Nylon 3-0 AR 3-0 Aguja Redonda",
    "genericName": "Sutura Nylon 3-0 AR",
    "laboratorio": "Nylon",
    "concentracion": "3-0 Aguja Redonda",
    "presentacion": "Sobre/Hebra",
    "category": "primeros-auxilios",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 9,
    "barcode": "7590000000609",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000609.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
  {
    "name": "Sutura Nylon 3-0 AC 3-0 Aguja Cortante",
    "genericName": "Sutura Nylon 3-0 AC",
    "laboratorio": "Nylon",
    "concentracion": "3-0 Aguja Cortante",
    "presentacion": "Sobre/Hebra",
    "category": "primeros-auxilios",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 12,
    "barcode": "7590000000610",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000610.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
  {
    "name": "Sutura Nylon 4-0",
    "genericName": "Sutura Nylon 4-0",
    "laboratorio": "Nylon",
    "concentracion": "4-0",
    "presentacion": "Sobre/Hebra",
    "category": "primeros-auxilios",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 6,
    "barcode": "7590000000611",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000611.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
  {
    "name": "Sutura Nylon 5-0",
    "genericName": "Sutura Nylon 5-0",
    "laboratorio": "Nylon",
    "concentracion": "5-0",
    "presentacion": "Sobre/Hebra",
    "category": "primeros-auxilios",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 3,
    "barcode": "7590000000612",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000612.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
  {
    "name": "Sutura Nylon 6-0",
    "genericName": "Sutura Nylon 6-0",
    "laboratorio": "Nylon",
    "concentracion": "6-0",
    "presentacion": "Sobre/Hebra",
    "category": "primeros-auxilios",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 10,
    "barcode": "7590000000613",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000613.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
  {
    "name": "Sutura Nylon 10-0 10-0 Oftálmico",
    "genericName": "Sutura Nylon 10-0",
    "laboratorio": "Nylon",
    "concentracion": "10-0 Oftálmico",
    "presentacion": "Sobre/Hebra",
    "category": "primeros-auxilios",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 3,
    "barcode": "7590000000614",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000614.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
  {
    "name": "Sutura Nylon 4-0 Demetech",
    "genericName": "Sutura Nylon 4-0 Demetech",
    "laboratorio": "Demetech",
    "concentracion": "4-0",
    "presentacion": "Sobre/Hebra",
    "category": "primeros-auxilios",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 7,
    "barcode": "7590000000615",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000615.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
  {
    "name": "Sutura Seda Negra 1",
    "genericName": "Sutura Seda Negra 1",
    "laboratorio": "Seda",
    "concentracion": "1",
    "presentacion": "Sobre/Hebra",
    "category": "primeros-auxilios",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 21,
    "barcode": "7590000000616",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000616.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
  {
    "name": "Sutura Seda Negra 2-0",
    "genericName": "Sutura Seda Negra 2-0",
    "laboratorio": "Seda",
    "concentracion": "2-0",
    "presentacion": "Sobre/Hebra",
    "category": "primeros-auxilios",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 10,
    "barcode": "7590000000617",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000617.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
  {
    "name": "Sutura Seda Negra 3-0",
    "genericName": "Sutura Seda Negra 3-0",
    "laboratorio": "Seda",
    "concentracion": "3-0",
    "presentacion": "Sobre/Hebra",
    "category": "primeros-auxilios",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 9,
    "barcode": "7590000000618",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000618.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
  {
    "name": "Sutura Seda Negra 0",
    "genericName": "Sutura Seda Negra 0",
    "laboratorio": "Seda",
    "concentracion": "0",
    "presentacion": "Sobre/Hebra",
    "category": "primeros-auxilios",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 4,
    "barcode": "7590000000619",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000619.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
  {
    "name": "Sutura Seda Trenzada 2-0",
    "genericName": "Sutura Seda Trenzada 2-0",
    "laboratorio": "Seda",
    "concentracion": "2-0",
    "presentacion": "Sobre/Hebra",
    "category": "primeros-auxilios",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 4,
    "barcode": "7590000000620",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000620.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
  {
    "name": "Sutura Seda Trenzada 0",
    "genericName": "Sutura Seda Trenzada 0",
    "laboratorio": "Seda",
    "concentracion": "0",
    "presentacion": "Sobre/Hebra",
    "category": "primeros-auxilios",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 8,
    "barcode": "7590000000621",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000621.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
  {
    "name": "Sutura Seda 4-0 13mm",
    "genericName": "Sutura Seda 4-0 13mm",
    "laboratorio": "Seda",
    "concentracion": "4-0 13mm",
    "presentacion": "Sobre/Hebra",
    "category": "primeros-auxilios",
    "priceUsd": 3.5,
    "costUsd": 2.27,
    "stock": 8,
    "barcode": "7590000000622",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000622.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
  {
    "name": "Sutura Sutupack 1",
    "genericName": "Sutura Sutupack 1",
    "laboratorio": "Sutupack",
    "concentracion": "1",
    "presentacion": "Carrete/Pack",
    "category": "primeros-auxilios",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 3,
    "barcode": "7590000000623",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000623.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
  {
    "name": "Sutura Sutupack 0",
    "genericName": "Sutura Sutupack 0",
    "laboratorio": "Sutupack",
    "concentracion": "0",
    "presentacion": "Carrete/Pack",
    "category": "primeros-auxilios",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 12,
    "barcode": "7590000000624",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000624.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
  {
    "name": "Sutura Vicryl 0",
    "genericName": "Sutura Vicryl 0",
    "laboratorio": "Ethicon",
    "concentracion": "0",
    "presentacion": "Sobre/Hebra",
    "category": "primeros-auxilios",
    "priceUsd": 4.5,
    "costUsd": 2.93,
    "stock": 24,
    "barcode": "7590000000625",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000625.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
  {
    "name": "Sutura Vicryl 1",
    "genericName": "Sutura Vicryl 1",
    "laboratorio": "Ethicon",
    "concentracion": "1",
    "presentacion": "Sobre/Hebra",
    "category": "primeros-auxilios",
    "priceUsd": 4.5,
    "costUsd": 2.93,
    "stock": 2,
    "barcode": "7590000000626",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000626.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
  {
    "name": "Sutura Vicryl 2-0",
    "genericName": "Sutura Vicryl 2-0",
    "laboratorio": "Ethicon",
    "concentracion": "2-0",
    "presentacion": "Sobre/Hebra",
    "category": "primeros-auxilios",
    "priceUsd": 4.5,
    "costUsd": 2.93,
    "stock": 35,
    "barcode": "7590000000627",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000627.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
  {
    "name": "Sutura Vicryl 3-0",
    "genericName": "Sutura Vicryl 3-0",
    "laboratorio": "Ethicon",
    "concentracion": "3-0",
    "presentacion": "Sobre/Hebra",
    "category": "primeros-auxilios",
    "priceUsd": 4.5,
    "costUsd": 2.93,
    "stock": 14,
    "barcode": "7590000000628",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000628.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
  {
    "name": "Sutura Vicryl 4-0",
    "genericName": "Sutura Vicryl 4-0",
    "laboratorio": "Ethicon",
    "concentracion": "4-0",
    "presentacion": "Sobre/Hebra",
    "category": "primeros-auxilios",
    "priceUsd": 4.5,
    "costUsd": 2.93,
    "stock": 15,
    "barcode": "7590000000629",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000629.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
  {
    "name": "Sutura Prolene 0",
    "genericName": "Sutura Prolene 0",
    "laboratorio": "Ethicon",
    "concentracion": "0",
    "presentacion": "Sobre/Hebra",
    "category": "primeros-auxilios",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 25,
    "barcode": "7590000000630",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000630.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
  {
    "name": "Sutura Prolene 1",
    "genericName": "Sutura Prolene 1",
    "laboratorio": "Ethicon",
    "concentracion": "1",
    "presentacion": "Sobre/Hebra",
    "category": "primeros-auxilios",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 20,
    "barcode": "7590000000631",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000631.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
  {
    "name": "Sutura Prolene 2-0",
    "genericName": "Sutura Prolene 2-0",
    "laboratorio": "Ethicon",
    "concentracion": "2-0",
    "presentacion": "Sobre/Hebra",
    "category": "primeros-auxilios",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 38,
    "barcode": "7590000000632",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000632.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
  {
    "name": "Sutura Prolene 3-0 AC 3-0 Aguja Cortante",
    "genericName": "Sutura Prolene 3-0 AC",
    "laboratorio": "Ethicon",
    "concentracion": "3-0 Aguja Cortante",
    "presentacion": "Sobre/Hebra",
    "category": "primeros-auxilios",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 20,
    "barcode": "7590000000633",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000633.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
  {
    "name": "Sutura Prolene 3-0 AR 3-0 Aguja Redonda",
    "genericName": "Sutura Prolene 3-0 AR",
    "laboratorio": "Ethicon",
    "concentracion": "3-0 Aguja Redonda",
    "presentacion": "Sobre/Hebra",
    "category": "primeros-auxilios",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 12,
    "barcode": "7590000000634",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000634.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
  {
    "name": "Sutura Prolene 5-0",
    "genericName": "Sutura Prolene 5-0",
    "laboratorio": "Ethicon",
    "concentracion": "5-0",
    "presentacion": "Sobre/Hebra",
    "category": "primeros-auxilios",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 12,
    "barcode": "7590000000635",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000635.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
  {
    "name": "Sutura Prolene 6-0",
    "genericName": "Sutura Prolene 6-0",
    "laboratorio": "Ethicon",
    "concentracion": "6-0",
    "presentacion": "Sobre/Hebra",
    "category": "primeros-auxilios",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 6,
    "barcode": "7590000000636",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000636.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
  {
    "name": "Sutura Prolene 4-0",
    "genericName": "Sutura Prolene 4-0",
    "laboratorio": "Ethicon",
    "concentracion": "4-0",
    "presentacion": "Sobre/Hebra",
    "category": "primeros-auxilios",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 8,
    "barcode": "7590000000637",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000637.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
  {
    "name": "Sutura Monofyl 3-0",
    "genericName": "Sutura Monofyl 3-0",
    "laboratorio": "Monofyl",
    "concentracion": "3-0",
    "presentacion": "Sobre/Hebra",
    "category": "primeros-auxilios",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 3,
    "barcode": "7590000000638",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000638.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
  {
    "name": "Sutura Polidioxanona 5-0",
    "genericName": "Sutura Polidioxanona 5-0",
    "laboratorio": "PDS / Polidioxanona",
    "concentracion": "5-0",
    "presentacion": "Sobre/Hebra",
    "category": "primeros-auxilios",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 12,
    "barcode": "7590000000639",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000639.jpg",
    "originalCategory": "Suturas Quirúrgicas"
  },
  {
    "name": "Pilas Energizer AAA",
    "genericName": "Pilas Energizer AAA",
    "laboratorio": "Energizer",
    "concentracion": "AAA",
    "presentacion": "Par/Unidad",
    "category": "cuidado-personal",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 5,
    "barcode": "7590000000640",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000640.jpg",
    "originalCategory": "Misceláneos y Cuidado Personal"
  },
];
