// Seed products 161-200 (auto-generated split)
export const SEED_PRODUCTS_05 = [
  {
    "name": "Olmesartán 20 mg",
    "genericName": "Olmesartán",
    "laboratorio": "Genérico",
    "concentracion": "20 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 2,
    "barcode": "7590000000161",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000161.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Olanzapina 5 mg",
    "genericName": "Olanzapina",
    "laboratorio": "Genérico",
    "concentracion": "5 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 2,
    "barcode": "7590000000162",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000162.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Olanzapina 10 mg",
    "genericName": "Olanzapina",
    "laboratorio": "Genérico",
    "concentracion": "10 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 6,
    "barcode": "7590000000163",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000163.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Ovayol Cap x 15",
    "genericName": "Inofolic / Suplemento",
    "laboratorio": "Ovayol",
    "concentracion": "Cap x 15",
    "presentacion": "Blister",
    "category": "analgesicos",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 2,
    "barcode": "7590000000164",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000164.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Omega 3,6,7,9 Cap x 10",
    "genericName": "Omega 3,6,7,9",
    "laboratorio": "Genérico",
    "concentracion": "Cap x 10",
    "presentacion": "Blister",
    "category": "analgesicos",
    "priceUsd": 35.0,
    "costUsd": 22.75,
    "stock": 2,
    "barcode": "7590000000165",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000165.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Omebloc 20 mg",
    "genericName": "Omeprazol",
    "laboratorio": "Omebloc",
    "concentracion": "20 mg",
    "presentacion": "Cap x 10",
    "category": "gastrointestinal",
    "priceUsd": 2.0,
    "costUsd": 1.3,
    "stock": 2,
    "barcode": "7590000000166",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000166.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Omeprazol 40 mg",
    "genericName": "Omeprazol",
    "laboratorio": "Genérico",
    "concentracion": "40 mg",
    "presentacion": "Tab x 10",
    "category": "gastrointestinal",
    "priceUsd": 3.5,
    "costUsd": 2.27,
    "stock": 8,
    "barcode": "7590000000167",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000167.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Omeprazol 40 mg (Genven)",
    "genericName": "Omeprazol",
    "laboratorio": "Genven",
    "concentracion": "40 mg",
    "presentacion": "Tab x 10",
    "category": "gastrointestinal",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 2,
    "barcode": "7590000000168",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000168.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Tachiforte",
    "genericName": "Paracetamol + Cafeína",
    "laboratorio": "Tachiforte",
    "concentracion": "",
    "presentacion": "Tab x 5",
    "category": "analgesicos",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 8,
    "barcode": "7590000000169",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000169.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Talzic",
    "genericName": "Cetirizina",
    "laboratorio": "Talzic",
    "concentracion": "",
    "presentacion": "Tab x 10",
    "category": "antihistaminicos",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 4,
    "barcode": "7590000000170",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000170.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Tetraciclina 500 mg",
    "genericName": "Tetraciclina",
    "laboratorio": "Genérico",
    "concentracion": "500 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 9.0,
    "costUsd": 5.85,
    "stock": 0,
    "barcode": "7590000000171",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000171.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Tamsulosina 0.4 mg",
    "genericName": "Tamsulosina",
    "laboratorio": "Genérico",
    "concentracion": "0.4 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 9,
    "barcode": "7590000000172",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000172.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "La Santé 250 mg",
    "genericName": "Terbinafina",
    "laboratorio": "La Santé",
    "concentracion": "250 mg",
    "presentacion": "Tab x 14",
    "category": "analgesicos",
    "priceUsd": 28.0,
    "costUsd": 18.2,
    "stock": 1,
    "barcode": "7590000000173",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000173.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Tinidazol 500 mg (PlusAndex)",
    "genericName": "Tinidazol",
    "laboratorio": "PlusAndex",
    "concentracion": "500 mg",
    "presentacion": "Tab x 4",
    "category": "antiparasitarios",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 2,
    "barcode": "7590000000174",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000174.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Tinidazol 500 mg (Drotafarma)",
    "genericName": "Tinidazol",
    "laboratorio": "Drotafarma",
    "concentracion": "500 mg",
    "presentacion": "Tab x 4",
    "category": "antiparasitarios",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 5,
    "barcode": "7590000000175",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000175.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Tirzol 5 mg",
    "genericName": "Tiamazol / Metimazol",
    "laboratorio": "Tirzol",
    "concentracion": "5 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 6,
    "barcode": "7590000000176",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000176.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Telmisartán",
    "genericName": "Telmisartán",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 3,
    "barcode": "7590000000177",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000177.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Buka 100 mg",
    "genericName": "Teofilina",
    "laboratorio": "Buka",
    "concentracion": "100 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 13.0,
    "costUsd": 8.45,
    "stock": 2,
    "barcode": "7590000000178",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000178.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Tegrazapín 200 mg",
    "genericName": "Carbamazepina",
    "laboratorio": "Tegrazapín",
    "concentracion": "200 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 3,
    "barcode": "7590000000179",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000179.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Tizanidina 2 mg",
    "genericName": "Tizanidina",
    "laboratorio": "Genérico",
    "concentracion": "2 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 12.0,
    "costUsd": 7.8,
    "stock": 1,
    "barcode": "7590000000180",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000180.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Topiramato 50 mg",
    "genericName": "Topiramato",
    "laboratorio": "Genérico",
    "concentracion": "50 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 8.0,
    "costUsd": 5.2,
    "stock": 2,
    "barcode": "7590000000181",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000181.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Torsilax",
    "genericName": "Relajante Muscular Compuesto",
    "laboratorio": "Torsilax",
    "concentracion": "",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 6,
    "barcode": "7590000000182",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000182.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Tiamina (Vit B1) 300 mg",
    "genericName": "Tiamina (Vit B1)",
    "laboratorio": "Genérico",
    "concentracion": "300 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 2,
    "barcode": "7590000000183",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000183.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Vibazina 25 mg",
    "genericName": "Buclizina",
    "laboratorio": "Vibazina",
    "concentracion": "25 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 15.0,
    "costUsd": 9.75,
    "stock": 1,
    "barcode": "7590000000184",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000184.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Selene 400/70",
    "genericName": "Selenio + Vit E",
    "laboratorio": "Selene",
    "concentracion": "400/70",
    "presentacion": "Cap x 15",
    "category": "analgesicos",
    "priceUsd": 10.0,
    "costUsd": 6.5,
    "stock": 1,
    "barcode": "7590000000185",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000185.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Vitamina E Cap x 10",
    "genericName": "Vitamina E",
    "laboratorio": "Genérico",
    "concentracion": "Cap x 10",
    "presentacion": "Blister",
    "category": "vitaminas",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 5,
    "barcode": "7590000000186",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000186.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Vitamina E 400 UI",
    "genericName": "Vitamina E",
    "laboratorio": "Genérico",
    "concentracion": "400 UI",
    "presentacion": "Tab x 10",
    "category": "vitaminas",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 3,
    "barcode": "7590000000187",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000187.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Vitamina C Masticable",
    "genericName": "Vitamina C Masticable",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Tab x 10",
    "category": "vitaminas",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 4,
    "barcode": "7590000000188",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000188.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Valsartán 80 mg",
    "genericName": "Valsartán",
    "laboratorio": "Genérico",
    "concentracion": "80 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 7,
    "barcode": "7590000000189",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000189.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Vitalit-D 1000 1000 UI",
    "genericName": "Vitamina D3",
    "laboratorio": "Vitalit-D 1000",
    "concentracion": "1000 UI",
    "presentacion": "Tab x 10",
    "category": "vitaminas",
    "priceUsd": 3.0,
    "costUsd": 1.95,
    "stock": 4,
    "barcode": "7590000000190",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000190.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Viagesan",
    "genericName": "Dimenhidrinato",
    "laboratorio": "Viagesan",
    "concentracion": "",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 9.0,
    "costUsd": 5.85,
    "stock": 1,
    "barcode": "7590000000191",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000191.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Valsartán Genérico 80 mg",
    "genericName": "Valsartán Genérico",
    "laboratorio": "Genérico",
    "concentracion": "80 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 1,
    "barcode": "7590000000192",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000192.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Cofasure 80 mg",
    "genericName": "Valsartán",
    "laboratorio": "Cofasure",
    "concentracion": "80 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 3,
    "barcode": "7590000000193",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000193.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Distrilab 160 mg",
    "genericName": "Valsartán",
    "laboratorio": "Distrilab",
    "concentracion": "160 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 7.0,
    "costUsd": 4.55,
    "stock": 3,
    "barcode": "7590000000194",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000194.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Valsartán 160 mg",
    "genericName": "Valsartán",
    "laboratorio": "Genérico",
    "concentracion": "160 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 7.0,
    "costUsd": 4.55,
    "stock": 1,
    "barcode": "7590000000195",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000195.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Valsartán 160 mg (Genven)",
    "genericName": "Valsartán",
    "laboratorio": "Genven",
    "concentracion": "160 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 7.0,
    "costUsd": 4.55,
    "stock": 3,
    "barcode": "7590000000196",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000196.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Valaciclovir 500 mg",
    "genericName": "Valaciclovir",
    "laboratorio": "Genérico",
    "concentracion": "500 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 18.0,
    "costUsd": 11.7,
    "stock": 1,
    "barcode": "7590000000197",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000197.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Trimebutina 200 mg",
    "genericName": "Trimebutina",
    "laboratorio": "Genérico",
    "concentracion": "200 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 5.0,
    "costUsd": 3.25,
    "stock": 3,
    "barcode": "7590000000198",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000198.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Trimetoprim",
    "genericName": "Trimetoprim",
    "laboratorio": "Genérico",
    "concentracion": "",
    "presentacion": "Tab x 10",
    "category": "antibioticos",
    "priceUsd": 4.0,
    "costUsd": 2.6,
    "stock": 8,
    "barcode": "7590000000199",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000199.jpg",
    "originalCategory": "Medicamentos Orales"
  },
  {
    "name": "Tiocolchicósido 4 mg",
    "genericName": "Tiocolchicósido",
    "laboratorio": "Genérico",
    "concentracion": "4 mg",
    "presentacion": "Tab x 10",
    "category": "analgesicos",
    "priceUsd": 6.0,
    "costUsd": 3.9,
    "stock": 5,
    "barcode": "7590000000200",
    "requiresPrescription": false,
    "isControlled": false,
    "image": "/products/7590000000200.jpg",
    "originalCategory": "Medicamentos Orales"
  },
];
